# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 21 (fahdah..fareedah)."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated20 import GLOSSES as _G20

GLOSSES = dict(_G20)
GLOSSES.update({
    "gracious_generous": {"en": "Gracious, generous, kind", "ur": "مہربان، سخی، کریم", "fa": "مهربان، بخشنده، کریم", "hi": "कृपालु, उदार, दयालु", "ps": "مهربان، سخي، کریم", "ar": "الكريم، اللطيف، الجواد"},
    "luminous": {"en": "Luminous, shining, radiant", "ur": "روشن، تابناک، درخشاں", "fa": "درخشان، تابان، فروزان", "hi": "प्रकाशमान, चमकीला, दीप्त", "ps": "روښان، ځلانده، تابناک", "ar": "المضيء، اللامع، المشرق"},
    "quick_swift": {"en": "Quick, swift, fast", "ur": "تیز، چست، پھرتیلا", "fa": "تند، چابک، سریع", "hi": "तेज़, चुस्त, फुर्तीला", "ps": "چټک، ګړندی، تیز", "ar": "السريع، العجول، الخفيف"},
    "gifted_intelligent": {"en": "Gifted, intelligent, talented", "ur": "باصلاحیت، ذہین، ہونہار", "fa": "بااستعداد، هوشمند، تیزهوش", "hi": "प्रतिभाशाली, बुद्धिमान, होनहार", "ps": "ځیرک، بااستعداد، هوښیار", "ar": "الموهوب، الذكي، النابغ"},
    "one_who_understands": {"en": "One who understands, comprehending", "ur": "سمجھنے والا، فہیم", "fa": "فهمنده، درک‌کننده", "hi": "समझने वाला, बोधक", "ps": "پوهېدونکی، فهم کوونکی", "ar": "الفاهم، المدرك، العارف"},
    "woman_of_discernment": {"en": "Woman of discernment, insightful", "ur": "صاحبِ بصیرت خاتون، سمجھدار", "fa": "زن بصیر، خردمند", "hi": "विवेकवती महिला, समझदार", "ps": "بصیرته ښځه، پوهه", "ar": "المرأة الفاهمة، البصيرة"},
    "wise_intelligent": {"en": "Wise, intelligent, sagacious", "ur": "دانا، ذہین، عقلمند", "fa": "دانا، هوشمند، خردمند", "hi": "बुद्धिमान, ज्ञानी, अक़्लमंद", "ps": "پوه، ځیرک، هوښیار", "ar": "الحكيم، الذكي، العاقل"},
    "understanding_comprehension": {"en": "Understanding, comprehension, insight", "ur": "فہم، سمجھ، بصیرت", "fa": "فهم، درک، بصیرت", "hi": "समझ, बोध, अंतर्दृष्टि", "ps": "پوهه، فهم، بصیرت", "ar": "الفهم، الإدراك، البصيرة"},
    "freed": {"en": "Freed, liberated", "ur": "آزاد، رہا، خلاص", "fa": "آزاد، رها، خلاص", "hi": "आज़ाद, मुक्त, रिहा", "ps": "آزاد، خوشې، خلاص", "ar": "الحر، المعتوق، المحرر"},
    "light_bearing": {"en": "Light-bearing, carrying light", "ur": "روشنی لانے والی، نور والی", "fa": "نورآور، روشنی‌بخش", "hi": "प्रकाश लाने वाली, ज्योतिर्मयी", "ps": "رڼا راوړونکې، نور لرونکې", "ar": "حاملة النور، المضيئة"},
    "gain_profit_success": {"en": "Gain, profit, success", "ur": "نفع، فائدہ، کامیابی", "fa": "سود، بهره، کامیابی", "hi": "लाभ, फ़ायदा, सफलता", "ps": "ګټه، فایده، بریا", "ar": "الفائدة، الربح، النجاح"},
    "divine_gift_reward": {"en": "Divine gift, reward", "ur": "الٰہی تحفہ، انعام", "fa": "هدیهٔ الهی، پاداش", "hi": "दैवी उपहार, इनाम", "ps": "الهي ډالۍ، انعام", "ar": "العطاء الإلهي، المكافأة"},
    "trust_faith": {"en": "Trust, faith, confidence", "ur": "بھروسہ، ایمان، اعتماد", "fa": "اعتماد، ایمان، باور", "hi": "भरोसा, ईमान, विश्वास", "ps": "باور، ایمان، اعتماد", "ar": "الثقة، الإيمان، الاعتماد"},
    "success_prosperity": {"en": "Success, prosperity, flourishing", "ur": "کامیابی، خوشحالی، ترقی", "fa": "کامیابی، رفاه، شکوفایی", "hi": "सफलता, समृद्धि, उन्नति", "ps": "بریا، هوساینه، پرمختګ", "ar": "النجاح، الازدهار، الفلاح"},
    "blossoming_blooming": {"en": "Blossoming, blooming, flourishing", "ur": "کھلتا ہوا، پھلتا پھولتا", "fa": "شکوفا، پرثمر، گل‌افشان", "hi": "खिलता हुआ, फलता-फूलता", "ps": "ګل کوونکی، شین شوی", "ar": "المزهر، المزدهر، الناضر"},
    "trustworthy_reliable_faithful": {"en": "Trustworthy, reliable, faithful", "ur": "اماندار، قابل اعتماد، وفادار", "fa": "امانت‌دار، قابل اعتماد، وفادار", "hi": "विश्वसनीय, भरोसेमंद, वफ़ादार", "ps": "امانتدار، باوري، وفادار", "ar": "الأمين، الموثوق، الوفي"},
    "victorious_triumphant": {"en": "Victorious, triumphant", "ur": "فاتح، کامیاب، غالب", "fa": "پیروز، فاتح، کامیاب", "hi": "विजयी, विजेता, कामयाब", "ps": "بریالی، فاتح، کامیاب", "ar": "المنصور، الفائز، الغالب"},
    "deliverer_helper": {"en": "Deliverer, helper, saviour", "ur": "نجات دینے والا، مددگار", "fa": "رهایی‌بخش، یاور", "hi": "उद्धारक, सहायक", "ps": "ژغورونکی، مرستندوی", "ar": "المنقذ، المعين، المخلص"},
    "superior_excellent": {"en": "Superior, excellent, surpassing", "ur": "برتر، بہترین، ممتاز", "fa": "برتر، برجسته، ممتاز", "hi": "श्रेष्ठ, उत्कृष्ट, बेहतर", "ps": "غوره، برتر، ممتاز", "ar": "الفائق، المتفوق، الأفضل"},
    "distinguished_exceptional": {"en": "Distinguished, exceptional, outstanding", "ur": "ممتاز، غیر معمولی، نمایاں", "fa": "ممتاز، برجسته، استثنایی", "hi": "विशिष्ट, असाधारण, उत्कृष्ट", "ps": "ممتاز، ځانګړی، غوره", "ar": "المميز، الاستثنائي، البارز"},
    "victorious_fragrance": {"en": "Victorious fragrance, triumphant perfume", "ur": "فاتح خوشبو، کامیاب عطر", "fa": "رایحهٔ پیروز، عطر فاتح", "hi": "विजयी सुगंध, विजेता ख़ुशबू", "ps": "بریالۍ خوشبویه، فاتح عطر", "ar": "العطر المنتصر، الشذا الفائز"},
    "jewel_precious_gem": {"en": "Jewel, precious gem, turquoise", "ur": "جواہر، قیمتی نگینہ، فیروزہ", "fa": "گوهر، جواهر، فیروزه", "hi": "रत्न, बहुमूल्य मणि, फ़िरोज़ा", "ps": "جواهر، ګران ډبره، فیروزه", "ar": "الجوهرة، الحجر الكريم، الفيروز"},
    "jewel_precious_one": {"en": "Jewel, precious one", "ur": "جواہر، قیمتی، گراں قدر", "fa": "گوهر، گران‌بها، عزیز", "hi": "रत्न, बहुमूल्य, कीमती", "ps": "جواهر، ګران، ارزښتناک", "ar": "الجوهرة، الثمين، النفيس"},
    "decisive": {"en": "Decisive, resolute, judge", "ur": "فیصلہ کن، حاکم، منصف", "fa": "فیصله‌کننده، داور، قاطع", "hi": "निर्णायक, न्यायाधीश, दृढ़", "ps": "فیصله کوونکی، قاضي، ټینګ", "ar": "الفاصل، الحاكم، القاضي"},
    "conqueror": {"en": "Conqueror, victor, one who overcomes", "ur": "فاتح، غالب، سر کرنے والا", "fa": "فاتح، پیروز، چیره‌شونده", "hi": "विजेता, फ़ातिह, विजयी", "ps": "فاتح، بریالی، غلبه کوونکی", "ar": "الفاتح، الغالب، المنتصر"},
    "giver_bestower": {"en": "Giver, bestower, generous", "ur": "دینے والا، عطا کرنے والا، سخی", "fa": "بخشنده، عطاکننده، کریم", "hi": "देने वाला, अता करने वाला, उदार", "ps": "ورکوونکی، عطا کوونکی، سخي", "ar": "المعطي، الواهب، الكريم"},
    "successor_victorious": {"en": "Successor, victorious, successful", "ur": "جانشین، فاتح، کامیاب", "fa": "جانشین، پیروز، کامیاب", "hi": "उत्तराधिकारी, विजयी, कामयाब", "ps": "ځای ناستی، بریالی، کامیاب", "ar": "الخليفة، الفائز، الناجح"},
    "radiant_bright": {"en": "Radiant, bright, luminous", "ur": "تابناک، روشن، درخشاں", "fa": "تابان، درخشان، فروزان", "hi": "दीप्त, चमकीला, प्रकाशमान", "ps": "ځلانده، روښان، تابناک", "ar": "المشرق، اللامع، المضيء"},
    "success_giver_conquering": {"en": "Success, giver, conquering", "ur": "کامیابی، دینے والا، فاتح", "fa": "کامیابی، بخشنده، پیروز", "hi": "सफलता, देने वाला, विजयी", "ps": "بریا، ورکوونکی، فاتح", "ar": "النجاح، المعطي، الغالب"},
    "grace": {"en": "Grace, favour, blessing", "ur": "فضل، کرم، نعمت", "fa": "لطف، فضل، نعمت", "hi": "कृपा, फ़ज़्ल, नेमत", "ps": "لطف، فضل، نعمت", "ar": "الفضل، الكرم، النعمة"},
    "successful_victorious": {"en": "Successful, victorious", "ur": "کامیاب، فاتح، کامران", "fa": "کامیاب، پیروز، بهره‌مند", "hi": "कामयाब, विजयी, सफल", "ps": "کامیاب، بریالی، فاتح", "ar": "الناجح، الفائز، الموفق"},
    "dawn": {"en": "Dawn, daybreak, first light", "ur": "طلوع، صبح، سپیدہ", "fa": "سپیده‌دم، بامداد، پگاه", "hi": "भोर, उषा, प्रभात", "ps": "سهار، سپیده، پگاه", "ar": "الفجر، الصبح، الإشراق"},
    "dawn_dawnbreak": {"en": "Dawn, daybreak", "ur": "طلوعِ صبح، سپیدہ", "fa": "سپیده‌دم، بامداد", "hi": "भोर, प्रभात", "ps": "سهار، سپیده", "ar": "الفجر، الصبح"},
    "pride_glory_dignity": {"en": "Pride, glory, dignity", "ur": "فخر، شان، وقار", "fa": "افتخار، شکوه، وقار", "hi": "गौरव, शान, गरिमा", "ps": "وياړ، شان، وقار", "ar": "الفخر، المجد، الكرامة"},
    "one_who_excels": {"en": "One who excels, prosperous", "ur": "بڑھنے والا، کامیاب، ممتاز", "fa": "برجسته، کامیاب، سرآمد", "hi": "उत्कृष्ट, कामयाब, श्रेष्ठ", "ps": "غوره، کامیاب، ممتاز", "ar": "المتفوق، الناجح، البارز"},
    "honorable_proud": {"en": "Honorable, proud, dignified", "ur": "معزز، فخر کرنے والا، باوقار", "fa": "محترم، سرافراز، باوقار", "hi": "सम्मानित, गौरवान्वित, गरिमापूर्ण", "ps": "معزز، وياړمن، باوقار", "ar": "المحترم، الفخور، الوقور"},
    "gift_of_god2": {"en": "Gift of God, divine gift", "ur": "خدا کا تحفہ، الٰہی عطا", "fa": "هدیهٔ خدا، عطای الهی", "hi": "ईश्वर का उपहार, दैवी अता", "ps": "د خدای ډالۍ، الهي عطا", "ar": "هدية الله، العطاء الإلهي"},
    "proud_honored": {"en": "Proud, honored, dignified", "ur": "فخر کرنے والا، معزز، باوقار", "fa": "سرافراز، محترم، باوقار", "hi": "गौरवान्वित, सम्मानित, गरिमापूर्ण", "ps": "وياړمن، معزز، باوقار", "ar": "الفخور، المكرم، الوقور"},
    "praiseworthy_commendable": {"en": "Praiseworthy, commendable, laudable", "ur": "قابلِ تعریف، مستحسن، لائق", "fa": "ستوده، ستایش‌برانگیز، شایسته", "hi": "प्रशंसनीय, सराहनीय, योग्य", "ps": "د ستاینې وړ، د قدر وړ، غوره", "ar": "المحمود، المستحق، الجدير"},
    "pride_honor": {"en": "Pride, honor, glory", "ur": "فخر، عزت، شان", "fa": "افتخار، عزت، شکوه", "hi": "गौरव, सम्मान, शान", "ps": "وياړ، عزت، شان", "ar": "الفخر، العز، المجد"},
    "pride_glory": {"en": "Pride, glory, honour", "ur": "فخر، شان، عزت", "fa": "افتخار، شکوه، عزت", "hi": "गौरव, शान, सम्मान", "ps": "وياړ، شان، عزت", "ar": "الفخر، المجد، العز"},
    "pride_honour_glory": {"en": "Pride, honour, glory", "ur": "فخر، عزت، شان", "fa": "افتخار، عزت، شکوه", "hi": "गौरव, सम्मान, शान", "ps": "وياړ، عزت، شان", "ar": "الفخر، العز، المجد"},
    "possessing_grace": {"en": "Possessing grace, graceful", "ur": "فضل والی، لطف والی", "fa": "لطف‌مند، صاحب لطف", "hi": "कृपा-युक्त, लालित्यपूर्ण", "ps": "لطف لرونکې، مهربانه", "ar": "ذات اللطف، الحسناء"},
    "pride_or_glory": {"en": "Pride or glory", "ur": "فخر یا شان", "fa": "افتخار یا شکوه", "hi": "गौरव या शान", "ps": "وياړ یا شان", "ar": "الفخر أو المجد"},
    "joy_delight_triumph": {"en": "Joy, delight, triumph", "ur": "خوشی، مسرت، فتح", "fa": "شادی، سرور، پیروزی", "hi": "आनंद, प्रसन्नता, विजय", "ps": "خوښي، مسرت، بریا", "ar": "الفرح، السرور، النصر"},
    "expert_scholar": {"en": "Expert, scholar, knowledgeable", "ur": "ماہر، عالم، واقف", "fa": "متخصص، دانشمند، آگاه", "hi": "विशेषज्ञ, विद्वान, जानकार", "ps": "متخصص، عالم، پوه", "ar": "الخبير، العالم، العارف"},
    "possessor_of_wealth": {"en": "Possessor of wealth, wealthy", "ur": "مالکِ دولت، مالدار", "fa": "دارای ثروت، توانگر", "hi": "धनवान, संपन्न", "ps": "دولت لرونکې، شتمنه", "ar": "ذات الثروة، الغنية"},
    "gods_pride": {"en": "God's pride, divine glory", "ur": "خدا کا فخر، الٰہی شان", "fa": "افتخار خدا، شکوهٔ الهی", "hi": "ईश्वर का गौरव, दैवी शान", "ps": "د خدای وياړ، الهي شان", "ar": "فخر الله، المجد الإلهي"},
    "success_achievement": {"en": "Success, achievement, attainment", "ur": "کامیابی، حصول، کامرانی", "fa": "کامیابی، دستاورد، موفقیت", "hi": "सफलता, उपलब्धि, प्राप्ति", "ps": "بریا، لاسته راوړنه، کامیابي", "ar": "الفلاح، النجاح، الإنجاز"},
    "success_prosperity2": {"en": "Success, prosperity, welfare", "ur": "کامیابی، خوشحالی، بہبود", "fa": "کامیابی، رفاه، بهروزی", "hi": "सफलता, समृद्धि, कल्याण", "ps": "بریا، هوساینه، ښه والی", "ar": "الفلاح، النجاح، الصلاح"},
    "successful_victorious2": {"en": "Successful, victorious, triumphant", "ur": "کامیاب، فاتح، غالب", "fa": "کامیاب، پیروز، فاتح", "hi": "कामयाब, विजयी, विजेता", "ps": "کامیاب، بریالی، فاتح", "ar": "الناجح، الفائز، المنتصر"},
    "star": {"en": "Star, celestial body", "ur": "ستارہ، نجم", "fa": "ستاره، اختر", "hi": "तारा, नक्षत्र", "ps": "ستوری، نجم", "ar": "النجم، الكوكب"},
    "young_falcon": {"en": "Young falcon, fledgling hawk", "ur": "نوجوان باز، چھوٹا شاہین", "fa": "شاهین جوان، باز نو", "hi": "युवा बाज़, नन्हा श्येन", "ps": "ځوان باز، وړوکی ښکاره", "ar": "الصقر الصغير، الباز الفتي"},
    "success_achievement2": {"en": "Success, achievement, prosperity", "ur": "کامیابی، حصول، ترقی", "fa": "کامیابی، دستاورد، رفاه", "hi": "सफलता, उपलब्धि, उन्नति", "ps": "بریا، لاسته راوړنه، پرمختګ", "ar": "الفلاح، النجاح، الإنجاز"},
    "freed_released": {"en": "Freed, released, liberated", "ur": "آزاد، رہا، چھوڑا ہوا", "fa": "آزاد، رها، خلاص‌شده", "hi": "आज़ाद, मुक्त, रिहा", "ps": "آزاد، خوشې، خلاص شوی", "ar": "المعتوق، المحرر، الحر"},
    "detached_separated": {"en": "Detached, separated, distinct", "ur": "الگ، جدا، منفصل", "fa": "جدا، منفصل، متمایز", "hi": "अलग, पृथक, विभक्त", "ps": "جلا، بېل، منفصل", "ar": "الفاصل، المنفصل، المميز"},
    "farmer_hardworking": {"en": "Farmer, hardworking, cultivator", "ur": "کسان، محنتی، کاشتکار", "fa": "کشاورز، زحمتکش، برزگر", "hi": "किसान, मेहनती, कृषक", "ps": "بزګر، زحمتکش، کروندګر", "ar": "الفلاح، المزارع، الكادح"},
    "expander": {"en": "Expander, one who expands", "ur": "پھیلانے والا، وسعت دینے والا", "fa": "گسترش‌دهنده، فراخ‌کننده", "hi": "विस्तारक, फैलाने वाला", "ps": "پراخوونکی، غځوونکی", "ar": "الموسع، الباسط، الناشر"},
    "hidden_secret": {"en": "Hidden secret, concealed mystery", "ur": "پوشیدہ راز، چھپا بھید", "fa": "راز پنهان، سر نهفته", "hi": "छिपा रहस्य, गुप्त भेद", "ps": "پټ راز، پټ سړی", "ar": "السر الخفي، المكتوم"},
    "lighthouse": {"en": "Lighthouse, beacon", "ur": "روشنی کا مینار، منارہ", "fa": "فانوس دریایی، برج نور", "hi": "प्रकाश-स्तंभ, दीपगृह", "ps": "د رڼا مینار، څراغ", "ar": "المنارة، الفنار، البرج"},
    "happiness": {"en": "Happiness, joy, gladness", "ur": "خوشی، مسرت، شادمانی", "fa": "شادی، خوشحالی، سرور", "hi": "ख़ुशी, आनंद, प्रसन्नता", "ps": "خوښي، مسرت، خوشحالي", "ar": "السعادة، الفرح، السرور"},
    "intelligent_wise_rich": {"en": "Intelligent, wise, rich", "ur": "ذہین، دانا، مالدار", "fa": "هوشمند، دانا، توانگر", "hi": "बुद्धिमान, ज्ञानी, धनी", "ps": "ځیرک، پوه، شتمن", "ar": "الذكي، الحكيم، الغني"},
    "expert_islamic_law": {"en": "Expert in Islamic law, jurist", "ur": "فقہ کا ماہر، فقیہ", "fa": "متخصص فقه، فقیه", "hi": "फ़िक़्ह का विशेषज्ञ, फ़क़ीह", "ps": "د فقه متخصص، فقیه", "ar": "الفقيه، العالم بالشريعة"},
    "poor_needy": {"en": "Poor, needy, mendicant", "ur": "غریب، محتاج، فقیر", "fa": "فقیر، نیازمند، تهیدست", "hi": "ग़रीब, ज़रूरतमंद, फ़क़ीर", "ps": "غریب، اړمن، فقیر", "ar": "الفقير، المحتاج، المسكين"},
    "expert_scholar_jurist": {"en": "Expert, scholar, jurist", "ur": "ماہر، عالم، فقیہ", "fa": "متخصص، دانشمند، فقیه", "hi": "विशेषज्ञ, विद्वान, फ़क़ीह", "ps": "متخصص، عالم، فقیه", "ar": "الفقيه، الخبير، العالم"},
    "poor_destitute": {"en": "Poor, destitute, needy", "ur": "غریب، نادار، محتاج", "fa": "فقیر، تهیدست، نیازمند", "hi": "ग़रीब, निर्धन, ज़रूरतमंद", "ps": "غریب، بې وزله، اړمن", "ar": "الفقير، المعدم، المحتاج"},
    "horse": {"en": "Horse, steed", "ur": "گھوڑا، اسپ", "fa": "اسب، باره", "hi": "घोड़ा, अश्व", "ps": "آس، اسپ", "ar": "الفرس، الحصان"},
    "joy_happiness": {"en": "Joy, happiness, gladness", "ur": "خوشی، مسرت، شادمانی", "fa": "شادی، خوشحالی، سرور", "hi": "ख़ुशी, आनंद, प्रसन्नता", "ps": "خوښي، مسرت، خوشحالي", "ar": "الفرح، السعادة، السرور"},
    "protector_preserver": {"en": "Protector, preserver, guardian", "ur": "محافظ، نگہبان، حامی", "fa": "نگهبان، محافظ، پاسدار", "hi": "रक्षक, संरक्षक, पालक", "ps": "ساتونکی، پالونکی، محافظ", "ar": "الحافظ، الراعي، الصائن"},
    "rare_precious_unique": {"en": "Rare, precious, unique", "ur": "نایاب، قیمتی، منفرد", "fa": "کم‌یاب، گران‌بها، بی‌همتا", "hi": "दुर्लभ, बहुमूल्य, अनोखा", "ps": "کم پېښ، ګران، بې ساری", "ar": "النادر، الثمين، الفريد"},
    "joy": {"en": "Joy, gladness, delight", "ur": "خوشی، مسرت، شادمانی", "fa": "شادی، سرور، خوشحالی", "hi": "आनंद, ख़ुशी, प्रसन्नता", "ps": "خوښي، مسرت، خوشحالي", "ar": "الفرح، السرور، البهجة"},
    "joyful_radiant_prosperous": {"en": "Joyful, radiant, prosperous", "ur": "خوش، تابناک، خوشحال", "fa": "شاد، درخشان، بهروز", "hi": "प्रसन्न, दीप्त, समृद्ध", "ps": "خوشحاله، ځلانده، هوسا", "ar": "الفرحان، المشرق، المزدهر"},
    "joy_giver": {"en": "Joy giver, bringer of happiness", "ur": "خوشی دینے والا، مسرت بخشنے والا", "fa": "شادی‌بخش، سرورآفرین", "hi": "आनंद देने वाला, ख़ुशी देने वाला", "ps": "خوښي ورکوونکی، مسرت بخښونکی", "ar": "مانح الفرح، باعث السعادة"},
    "exalted_noble_precious": {"en": "Exalted, noble, precious", "ur": "بلند، نجیب، قیمتی", "fa": "بلندمرتبه، نجیب، گران‌بها", "hi": "उच्च, कुलीन, बहुमूल्य", "ps": "لوړ، نجیب، ګران", "ar": "الرفيع، النبيل، الثمين"},
    "deliverance_relief_joy": {"en": "Deliverance, relief, joy", "ur": "نجات، راحت، خوشی", "fa": "رهایی، آسودگی، شادی", "hi": "मुक्ति, राहत, ख़ुशी", "ps": "خلاصون، آرام، خوښي", "ar": "الفرج، الراحة، الفرح"},
    "far_distance_contentment": {"en": "Far (distance) + contentment", "ur": "دور (فاصلہ) + قناعت", "fa": "دور (فاصله) + خرسندی", "hi": "दूर (दूरी) + संतोष", "ps": "لرې (واټن) + قناعت", "ar": "البعيد (مسافة) + الرضا"},
    "expert_skilled_victorious": {"en": "Expert, skilled, victorious", "ur": "ماہر، ہنرمند، فاتح", "fa": "متخصص، ماهر، پیروز", "hi": "विशेषज्ञ, कुशल, विजयी", "ps": "متخصص، ماهر، بریالی", "ar": "الخبير، الماهر، المنتصر"},
    "jewel_treasure": {"en": "Jewel, treasure, gem", "ur": "جواہر، خزانہ، نگینہ", "fa": "گوهر، گنج، جواهر", "hi": "रत्न, ख़ज़ाना, मणि", "ps": "جواهر، خزانه، ګران ډبره", "ar": "الجوهرة، الكنز، الحجر الكريم"},
    "strong_and_powerful": {"en": "Strong and powerful", "ur": "طاقتور اور زبردست", "fa": "نیرومند و توانا", "hi": "शक्तिशाली और बलवान", "ps": "پیاوړی او ځواکمن", "ar": "القوي والجبار"},
    "little_fox": {"en": "Little fox, fox cub", "ur": "چھوٹا لومڑ، لومڑی کا بچہ", "fa": "روباه کوچک، توله‌روباه", "hi": "छोटी लोमड़ी, लोमड़ी का बच्चा", "ps": "وړوکی لوی، د لوی بچی", "ar": "الثعلب الصغير، جرموز"},
    "determined_resolute": {"en": "Determined, resolute, firm", "ur": "پکا، ثابت قدم، مصمم", "fa": "مصمم، استوار، ثابت‌قدم", "hi": "दृढ़, अटल, संकल्पित", "ps": "ټینګ، ثابت، مصمم", "ar": "الحازم، الثابت، المصمم"},
    "carrier_supporter": {"en": "Carrier, supporter, bearer", "ur": "اٹھانے والا، سہارا دینے والا", "fa": "حامل، پشتیبان، بردار", "hi": "वाहक, सहारा देने वाला", "ps": "وړونکی، ملاتړی، حامل", "ar": "الحامل، الساند، الناصر"},
    "servant": {"en": "Servant, attendant", "ur": "خادم، نوکر، خدمتگار", "fa": "خادم، بنده، خدمتگار", "hi": "सेवक, ख़ादिम, सेवादार", "ps": "خدمتګار، بنده، خادم", "ar": "الخادم، العبد، الخديم"},
    "garden_of_paradise": {"en": "Garden of paradise, highest paradise", "ur": "جنت کا باغ، فردوس", "fa": "باغ بهشت، فردوس", "hi": "जन्नत का बाग़, फ़िरदौस", "ps": "د جنت باغ، فردوس", "ar": "الفردوس، جنة المأوى"},
    "one_who_protects": {"en": "The one who protects, guardian", "ur": "حفاظت کرنے والا، نگہبان", "fa": "نگهبان، محافظ، پاسدار", "hi": "रक्षा करने वाला, संरक्षक", "ps": "ساتونکی، پالونکی، محافظ", "ar": "الحافظ، الراعي، الصائن"},
    "free_independent": {"en": "Free, independent, unique", "ur": "آزاد، خودمختار، منفرد", "fa": "آزاد، مستقل، بی‌همتا", "hi": "आज़ाद, स्वतंत्र, अनोखा", "ps": "آزاد، خپلواک، بې ساری", "ar": "الحر، المستقل، الفريد"},
    "unique": {"en": "Unique, singular, peerless", "ur": "منفرد، بے نظیر، یکتا", "fa": "بی‌همتا، یگانه، منحصربه‌فرد", "hi": "अनोखा, अद्वितीय, बेजोड़", "ps": "بې ساری، یوازینی، ځانګړی", "ar": "الفريد، الوحيد، النادر"},
    "praiseworthy_noble": {"en": "Praiseworthy, noble, excellent", "ur": "قابلِ تعریف، نجیب، بہترین", "fa": "ستوده، نجیب، برجسته", "hi": "प्रशंसनीय, कुलीन, उत्कृष्ट", "ps": "د ستاینې وړ، نجیب، غوره", "ar": "المحمود، النبيل، الفاضل"},
})

GLOSSES.update({
    "batch21_fahdah": {"en": 'Cheetah, leopard'},
    "batch21_faheema": {"en": 'Intelligent, understanding'},
    "batch21_fahid": {"en": 'Cheetah, leopard'},
    "batch21_fahri": {"en": 'Of pride, honorary'},
    "batch21_faid": {"en": 'Beneficial, useful'},
    "batch21_faida": {"en": 'Benefit, advantage, profit'},
    "batch21_faidah": {"en": 'Benefit, profit'},
    "batch21_faih": {"en": 'Diffusing fragrance'},
    "batch21_faiha": {"en": 'Diffusing fragrance'},
    "batch21_faihaa": {"en": 'Diffusing fragrance'},
    "batch21_faik": {"en": 'Superior, surpassing, excellent'},
    "batch21_faika": {"en": 'Superior, surpassing'},
    "batch21_faiqa": {"en": 'Superior, surpassing'},
    "batch21_fairooz": {"en": 'Turquoise; victorious'},
    "batch21_faishal": {"en": 'Decisive, judge'},
    "batch21_faiyaz": {"en": 'Abundantly generous, overflowing'},
    "batch21_faiz": {"en": 'Abundance, overflow, grace'},
    "batch21_faiza": {"en": 'Successful, victorious'},
    "batch21_faizaan": {"en": 'Overflowing, abundance'},
    "batch21_faizah": {"en": 'Successful, victorious'},
    "batch21_faizan": {"en": 'Overflowing, abundance, grace'},
    "batch21_faizel": {"en": 'Virtuous, excellent'},
    "batch21_faizi": {"en": 'Of abundance, related to fayḍ'},
    "batch21_fairuz": {"en": 'Turquoise, precious stone'},
    "batch21_fairuza": {"en": 'Turquoise'},
    "batch21_fakher": {"en": 'Excellent, splendid, luxurious'},
    "batch21_fakhir": {"en": 'Excellent, splendid'},
    "batch21_fakhira": {"en": 'Excellent, splendid'},
    "batch21_fakhirah": {"en": 'Excellent, splendid'},
    "batch21_fakhriya": {"en": 'Of pride, honorary'},
    "batch21_fakhry": {"en": 'Of pride'},
    "batch21_fakira": {"en": 'Poor, needy'},
    "batch21_falak": {"en": 'Celestial sphere, orbit, firmament'},
    "batch21_falaki": {"en": 'Astronomical, celestial'},
    "batch21_faliq": {"en": 'Splitter, one who cleaves'},
    "batch21_fanan": {"en": 'Branches, artistic styles'},
    "batch21_fani": {"en": 'Mortal, transient'},
    "batch21_faouzi": {"en": 'Of victory, triumphant'},
    "batch21_faraaz": {"en": 'Height, ascent, elevation'},
    "batch21_farag": {"en": 'Relief, deliverance, joy'},
    "batch21_farahan": {"en": 'Joyful, glad'},
    "batch21_farahani": {"en": 'Of joy, related to farḥān'},
    "batch21_farahat": {"en": 'Joys, happiness'},
    "batch21_farahin": {"en": 'Related to joy'},
    "batch21_farahmand": {"en": 'Fortunate, blessed, glorious'},
    "batch21_farahnaz": {"en": 'Joy, charm, delight'},
    "batch21_farakh": {"en": 'Wide, spacious, ample'},
    "batch21_faras": {"en": 'Horse, steed'},
    "batch21_farasat": {"en": 'Perspicacity, discernment'},
    "batch21_faraz": {"en": 'Height, ascent, elevation'},
    "batch21_fard": {"en": 'Individual, single, unique'},
    "batch21_fardan": {"en": 'Related to fard; individual, unique'},
    "batch21_fareed": {"en": 'Unique, peerless, singular'},
    "batch21_fareedah": {"en": 'Unique, precious, peerless'},
})

# name -> (ar, ur, fa, hi, ps, gloss, origin, gender, root, quranic, conf, note)
CUR = {
 'fahdah': ('فهدة', 'فہدہ', None, 'फ़हदा', 'فهده', 'batch21_fahdah', 'Arabic', 'Unisex', 'ف ه د', 'not established', 'medium', "Fahda, the feminine of fahd ('cheetah, leopard'). The source record's gloss 'Gracious, Generous' is unsupported."),
 "faheem": ("فهيم", "فہیم", None, "फ़हीम", "فهيم", "wise_knowledgeable", "Arabic", "Male", "ف ه م", "not established", "high", "Fahīm ('one who understands, intelligent'). The source record's gloss 'Wise, Knowledgeable' is a reasonable rendering."),
 'faheema': ('فهيمة', 'فہیمہ', None, 'फ़हीमा', 'فهيمه', 'batch21_faheema', 'Arabic', 'Female', 'ف ه م', 'not established', 'high', "Fahīma ('intelligent, understanding'). The source record's gloss 'Luminous' is unsupported."),
 'fahid': ('فهد', 'فہد', None, 'फ़हिद', 'فهد', 'batch21_fahid', 'Arabic', 'Male', 'ف ه د', 'not established', 'high', "Fahd ('cheetah, leopard'), an animal noted for speed. The source record's gloss 'Quick, Swift' is an approximation."),
 "fahiim": ("فهيم", "فہیم", None, "फ़हीम", "فهيم", "gifted_intelligent", "Arabic", "Male", "ف ه م", "not established", "high", "Variant romanization of فهيم ('intelligent'). The source record's gloss 'Gifted, Intelligent' is a reasonable rendering."),
 "fahim": ("فهيم", "فہیم", None, "फ़हीम", "فهيم", "one_who_understands", "Arabic", "Male", "ف ه م", "not established", "high", "Fahīm ('one who understands'). The source record's gloss 'One who understands' is a reasonable rendering."),
 "fahima": ("فهيمة", "فہیمہ", None, "फ़हीमा", "فهيمه", "woman_of_discernment", "Arabic", "Female", "ف ه م", "not established", "high", "Fahīma ('intelligent, discerning woman'). The source record's gloss 'Woman of discernment' is a reasonable rendering."),
 "fahimah": ("فهيمة", "فہیمہ", None, "फ़हीमा", "فهيمه", "wise_intelligent", "Arabic", "Female", "ف ه م", "not established", "high", "Variant romanization of فهيمة ('intelligent'). The source record's gloss 'Wise, Intelligent' is a reasonable rendering."),
 "fahmi": ("فهمي", "فہمی", None, "फ़हमी", "فهمي", "wise_intelligent", "Arabic", "Male", "ف ه م", "not established", "high", "Fahmī ('of understanding, intellectual'). The source record's gloss 'Wise, Intelligent' is a reasonable rendering."),
 "fahmida": ("فهميدة", "فہمیدہ", None, "फ़हमीदा", "فهميده", "understanding_comprehension", "Arabic", "Female", "ف ه م", "not established", "high", "Fahmīda ('understanding, comprehending'). The source record's gloss 'Understanding, Comprehension' is a reasonable rendering."),
 'fahri': ('فخري', 'فخری', None, 'फ़ख़री', 'فخري', 'batch21_fahri', 'Arabic', 'Male', 'ف خ ر', 'not established', 'high', "Fakhrī ('of pride, honorary'). The source record's gloss 'Freed' is unsupported."),
 "fahrina": ("فخرينة", "فخرینہ", None, "फ़ख़रीना", "فخرينه", "light_bearing", "Unknown", "Female", None, "not established", "low", "The source record's gloss 'Light bearing' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 'faid': ('فائد', 'فائد', None, 'फ़ाइद', 'فائد', 'batch21_faid', 'Arabic', 'Male', 'ف ي د', 'not established', 'medium', "Fāʾid ('beneficial, useful'). The source record's gloss 'Helper' is unsupported."),
 'faida': ('فائدة', 'فائدہ', None, 'फ़ाइदा', 'فائده', 'batch21_faida', 'Arabic', 'Female', 'ف ي د', 'not established', 'high', "Fāʾida ('benefit, advantage, profit'). The source record's gloss 'Gain, Profit, Success' is a reasonable rendering."),
 'faidah': ('فائدة', 'فائدہ', None, 'फ़ाइदा', 'فائده', 'batch21_faidah', 'Arabic', 'Female', 'ف ي د', 'not established', 'high', "Variant romanization of فائدة ('benefit, profit'). The source record's gloss 'Divine gift, reward' is unsupported."),
 'faih': ('فائح', 'فائح', None, 'फ़ाइह', 'فائح', 'batch21_faih', 'Arabic', 'Male', 'ف و ح', 'not established', 'medium', "Fāʾiḥ ('diffusing fragrance'). The source record's gloss 'Trust, Faith' is unsupported."),
 'faiha': ('فائحة', 'فائحہ', None, 'फ़ाइहा', 'فائحه', 'batch21_faiha', 'Arabic', 'Female', 'ف و ح', 'not established', 'medium', "Fāʾiḥa ('diffusing fragrance'). The source record's gloss 'Success, Prosperity' is unsupported."),
 'faihaa': ('فائحة', 'فائحہ', None, 'फ़ाइहा', 'فائحه', 'batch21_faihaa', 'Arabic', 'Female', 'ف و ح', 'not established', 'medium', "Variant romanization of فائحة ('diffusing fragrance'). The source record's gloss 'Blossoming, Blooming' is unsupported."),
 'faik': ('فائق', 'فائق', None, 'फ़ाइक', 'فائق', 'batch21_faik', 'Arabic', 'Male', 'ف و ق', 'not established', 'high', "Fāʾiq ('superior, surpassing, excellent'). The source record's gloss 'Trustworthy, reliable, faithful' is unsupported."),
 'faika': ('فائقة', 'فائقہ', None, 'फ़ाइका', 'فاقه', 'batch21_faika', 'Arabic', 'Female', 'ف و ق', 'not established', 'high', "Fāʾiqa ('superior, surpassing'). The source record's gloss 'Victorious, Triumphant' is unsupported."),
 "faima": ("فيمة", "فیمہ", None, "फ़ाइमा", "فيمه", "deliverer_helper", "Unknown", "Female", None, "not established", "low", "The source record's gloss 'Deliverer, Helper' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "faiq": ("فائق", "فائق", None, "फ़ाइक़", "فائق", "superior_excellent", "Arabic", "Male", "ف و ق", "not established", "high", "Fāʾiq ('superior, excellent, surpassing'). The source record's gloss 'Superior, Excellent' is a reasonable rendering."),
 'faiqa': ('فائقة', 'فائقہ', None, 'फ़ाइक़ा', 'فاقه', 'batch21_faiqa', 'Arabic', 'Female', 'ف و ق', 'not established', 'high', "Fāʾiqa ('superior, surpassing'). The source record's gloss 'Bright, Luminous' is unsupported."),
 "faiqah": ("فائقة", "فائقہ", None, "फ़ाइक़ा", "فاقه", "distinguished_exceptional", "Arabic", "Female", "ف و ق", "not established", "high", "Variant romanization of فائقة ('superior, surpassing'). The source record's gloss 'Distinguished, Exceptional' is a reasonable rendering."),
 'fairooz': ('فيروز', 'فیروز', 'فیروز', 'फ़िरोज़', 'فیروز', 'batch21_fairooz', 'Persian', 'Female', 'Persian fīrūz', 'not established', 'high', "Persian fīrūz ('turquoise'; also 'victorious'). The source record's gloss 'Victorious fragrance' is an unsupported conflation. The source record classified it as Arabic, which is incorrect."),
 'fairoz': ('فيروز', 'فیروز', 'فیروز', 'फ़िरोज़', 'فیروز', 'victorious', 'Persian', 'Male', 'Persian fīrūz', 'not established', 'high', "Persian fīrūz ('victorious'; also 'turquoise'). The source record's gloss 'Victorious' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 'fairuz': ('فيروز', 'فیروز', 'فیروز', 'फ़िरोज़', 'فیروز', 'batch21_fairuz', 'Persian', 'Female', 'Persian fīrūz', 'not established', 'high', "Persian fīrūz ('turquoise'). The source record's gloss 'Jewel, Precious Gem' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 'fairuza': ('فيروزة', 'فیروزہ', 'فیروزه', 'फ़िरोज़ा', 'فیروزه', 'batch21_fairuza', 'Persian', 'Female', 'Persian fīrūza', 'not established', 'high', "Persian fīrūza ('turquoise'). The source record's gloss 'Jewel, Precious one' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 "faisal": ("فيصل", "فیصل", None, "फ़ैसल", "فیصل", "decisive", "Arabic", "Male", "ف ص ل", "not established", "high", "Fayṣal ('decisive, judge, one who separates truth from falsehood'). The source record's gloss 'Decisive' is a reasonable rendering. The source record classified it as Unknown, which is incorrect."),
 'faishal': ('فيصل', 'فیصل', None, 'फ़ैसल', 'فیصل', 'batch21_faishal', 'Arabic', 'Male', 'ف ص ل', 'not established', 'high', "Variant romanization of فيصل ('decisive'). The source record's gloss 'Victorious' is unsupported."),
 'faiyaz': ('فياض', 'فیاض', None, 'फ़ैयाज़', 'فیاض', 'batch21_faiyaz', 'Arabic', 'Male', 'ف ي ض', 'not established', 'high', "Fayyāḍ ('abundantly generous, overflowing'). The source record's gloss 'Conqueror' is unsupported."),
 'faiz': ('فيض', 'فیض', None, 'फ़ैज़', 'فیض', 'batch21_faiz', 'Arabic', 'Male', 'ف ي ض', 'not established', 'high', "Fayḍ ('abundance, overflow, grace'). The source record's gloss 'Giver, Bestower, Successful' is an approximation."),
 'faiza': ('فائزة', 'فائزہ', None, 'फ़ाइज़ा', 'فايزه', 'batch21_faiza', 'Arabic', 'Female', 'ف و ز', 'not established', 'high', "Fāʾiza ('successful, victorious'). The source record's gloss 'Successor, Victorious' is an approximation."),
 'faizaan': ('فيضان', 'فیضان', None, 'फ़ैज़ान', 'فیضان', 'batch21_faizaan', 'Arabic', 'Male', 'ف ي ض', 'not established', 'high', "Fayḍān ('overflowing, abundance'). The source record's gloss 'Radiant, Bright' is unsupported."),
 'faizah': ('فائزة', 'فائزہ', None, 'फ़ाइज़ा', 'فايزه', 'batch21_faizah', 'Arabic', 'Female', 'ف و ز', 'not established', 'high', "Variant romanization of فائزة ('successful'). The source record's gloss 'Success, Giver, Conquering' is an approximation."),
 'faizan': ('فيضان', 'فیضان', None, 'फ़ैज़ान', 'فیضان', 'batch21_faizan', 'Arabic', 'Male', 'ف ي ض', 'not established', 'high', "Fayḍān ('overflowing, abundance, grace'). The source record's gloss 'Grace' is a reasonable rendering. The source record classified it as Unknown, which is incorrect."),
 'faizel': ('فاضل', 'فاضل', None, 'फ़ैज़ेल', 'فاضل', 'batch21_faizel', 'Arabic', 'Male', 'ف ض ل', 'not established', 'high', "Fāḍil ('virtuous, excellent'). The source record's gloss 'Successful, Victorious' is unsupported."),
 'faizi': ('فيضي', 'فیضی', None, 'फ़ैज़ी', 'فیضي', 'batch21_faizi', 'Arabic', 'Male', 'ف ي ض', 'not established', 'high', "Fayḍī ('of abundance, related to fayḍ'). The source record's gloss 'Victorious, Successful' is unsupported."),
 "fajar": ("فجر", "فجر", None, "फ़जर", "فجر", "dawn", "Arabic", "Male", "ف ج ر", "الفجر is a Qur'anic surah name (89)", "high", "Fajr ('dawn, daybreak'), the name of Qur'anic surah 89 and of the dawn prayer. The source record's gloss 'Dawn' is a reasonable rendering."),
 "fajer": ("فجر", "فجر", None, "फ़जर", "فجر", "dawn", "Arabic", "Male", "ف ج ر", "الفجر is a Qur'anic surah name (89)", "high", "Variant romanization of فجر ('dawn'). The source record's gloss 'Dawn' is a reasonable rendering. The source record classified it as Unknown, which is incorrect."),
 "fajr": ("فجر", "فجر", None, "फ़ज्र", "فجر", "dawn", "Arabic", "Male", "ف ج ر", "الفجر is a Qur'anic surah name (89)", "high", "Fajr ('dawn, daybreak'), the name of Qur'anic surah 89. The source record's gloss 'Dawn' is a reasonable rendering. The source record classified it as Unknown, which is incorrect."),
 'fajrul': ('فجر ال', 'فجر ال', None, 'फ़जरुल', 'فجر ال', 'uncertain_form', 'Arabic', 'Male', 'ف ج ر', "الفجر is a Qur'anic surah name (89)", 'low', "Fajr al- ('dawn of the'), a compound prefix rather than a standalone given name. The source record's gloss 'Dawn, Dawnbreak' is a reasonable rendering."),
 "fakhar": ("فخر", "فخر", None, "फ़ख़र", "فخر", "pride_glory_dignity", "Arabic", "Male", "ف خ ر", "not established", "high", "Fakhr ('pride, glory, honour'). The source record's gloss 'Pride, Glory, Dignity' is a reasonable rendering."),
 'fakher': ('فاخر', 'فاخر', None, 'फ़ाख़ेर', 'فاخر', 'batch21_fakher', 'Arabic', 'Male', 'ف خ ر', 'not established', 'high', "Fākhir ('excellent, splendid, luxurious'). The source record's gloss 'One who excels, prosperous' is a reasonable rendering."),
 'fakhir': ('فاخر', 'فاخر', None, 'फ़ाख़िर', 'فاخر', 'batch21_fakhir', 'Arabic', 'Male', 'ف خ ر', 'not established', 'high', "Variant romanization of فاخر ('excellent, splendid'). The source record's gloss 'Honorable, Proud' is an approximation."),
 'fakhira': ('فاخرة', 'فاخرہ', None, 'फ़ाख़िरा', 'فاخره', 'batch21_fakhira', 'Arabic', 'Female', 'ف خ ر', 'not established', 'high', "Fākhira ('excellent, splendid'). The source record's gloss 'Gift of God' is unsupported."),
 'fakhirah': ('فاخرة', 'فاخرہ', None, 'फ़ाख़िरा', 'فاخره', 'batch21_fakhirah', 'Arabic', 'Female', 'ف خ ر', 'not established', 'high', "Variant romanization of فاخرة ('excellent, splendid'). The source record's gloss 'Proud, Honored' is an approximation."),
 "fakhita": ("فخيطة", "فخیتہ", None, "फ़ख़ीता", "فخيته", "praiseworthy_commendable", "Arabic", "Female", "ف خ ر", "not established", "low", "The source record's gloss 'Praiseworthy, Commendable' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "fakhr": ("فخر", "فخر", None, "फ़ख़्र", "فخر", "pride_honor", "Arabic", "Male", "ف خ ر", "not established", "high", "Fakhr ('pride, honour, glory'). The source record's gloss 'Pride, Honor' is a reasonable rendering."),
 "fakhra": ("فخرة", "فخرہ", None, "फ़ख़रा", "فخره", "pride_glory", "Arabic", "Female", "ف خ ر", "not established", "high", "Fakhra, the feminine of fakhr ('pride, glory'). The source record's gloss 'Pride, Glory' is a reasonable rendering."),
 "fakhri": ("فخري", "فخری", None, "फ़ख़री", "فخري", "pride_honour_glory", "Arabic", "Male", "ف خ ر", "not established", "high", "Fakhrī ('of pride, honorary'). The source record's gloss 'Pride, Honour, Glory' is a reasonable rendering."),
 'fakhriya': ('فخرية', 'فخریہ', None, 'फ़ख़रिया', 'فخريه', 'batch21_fakhriya', 'Arabic', 'Female', 'ف خ ر', 'not established', 'high', "Fakhriyya ('of pride, honorary'). The source record's gloss 'Possessing Grace' is unsupported."),
 'fakhrul': ('فخر ال', 'فخر ال', None, 'फ़ख़रुल', 'فخر ال', 'uncertain_form', 'Arabic', 'Male', 'ف خ ر', 'not established', 'low', "Fakhr al- ('pride of the'), a compound prefix rather than a standalone given name. The source record's gloss 'Pride or Glory' is a reasonable rendering."),
 'fakhry': ('فخري', 'فخری', None, 'फ़ख़री', 'فخري', 'batch21_fakhry', 'Arabic', 'Male', 'ف خ ر', 'not established', 'high', "Variant romanization of فخري ('of pride'). The source record's gloss 'Joy, Delight, Triumph' is unsupported."),
 "fakih": ("فقيه", "فقیه", None, "फ़क़ीह", "فقیه", "expert_scholar", "Arabic", "Male", "ف ق ه", "not established", "high", "Faqīh ('jurist, expert in Islamic law'). The source record's gloss 'Expert, Scholar, Knowledgeable' is a reasonable rendering."),
 'fakira': ('فقيرة', 'فقیرہ', None, 'फ़क़ीरा', 'فقيره', 'batch21_fakira', 'Arabic', 'Female', 'ف ق ر', 'not established', 'high', "Faqīra ('poor, needy'). The source record's gloss 'Possessor of Wealth' is the opposite of the lexical meaning and is unsupported."),
 'fakrul': ('فخر ال', 'فخر ال', None, 'फ़क़रुल', 'فخر ال', 'uncertain_form', 'Arabic', 'Male', 'ف خ ر', 'not established', 'low', 'Fakhr al- (\'pride of the\'), a compound prefix rather than a standalone given name. The source record\'s gloss "God\'s Pride" is an unsupported elaboration.'),
 "falaah": ("فلاح", "فلاح", None, "फ़लाह", "فلاح", "success_achievement", "Arabic", "Unisex", "ف ل ح", "not established", "high", "Falāḥ ('success, salvation, prosperity'). The source record's gloss 'Success, achievement' is a reasonable rendering."),
 "falah": ("فلاح", "فلاح", None, "फ़लाह", "فلاح", "success_prosperity2", "Arabic", "Unisex", "ف ل ح", "not established", "high", "Variant romanization of فلاح ('success, prosperity'). The source record's gloss 'Success, prosperity' is a reasonable rendering."),
 "falahi": ("فلاحي", "فلاحی", None, "फ़लाही", "فلاحي", "successful_victorious2", "Arabic", "Unisex", "ف ل ح", "not established", "high", "Falāḥī ('of success, related to falāḥ'). The source record's gloss 'Successful, Victorious' is a reasonable rendering."),
 'falak': ('فلك', 'فلک', None, 'फ़लक', 'فلک', 'batch21_falak', 'Arabic', 'Unisex', 'ف ل ك', 'not established', 'high', "Falak ('celestial sphere, orbit, firmament'). The source record's gloss 'Star' is an approximation. The source record classified it as Unknown, which is incorrect."),
 'falaki': ('فلكي', 'فلکی', None, 'फ़लकी', 'فلکي', 'batch21_falaki', 'Arabic', 'Male', 'ف ل ك', 'not established', 'medium', "Falakī ('astronomical, celestial'). The source record's gloss 'Young Falcon' is unsupported."),
 "falih": ("فالح", "فالح", None, "फ़ालिह", "فالح", "success_achievement2", "Arabic", "Male", "ف ل ح", "not established", "high", "Fāliḥ ('successful, prosperous'). The source record's gloss 'Success, Achievement' is a reasonable rendering."),
 "falilat": ("فليلة", "فلیلت", None, "फ़लीलत", "فليله", "freed_released", "Arabic", "Female", "ف ل ل", "not established", "low", "The source record's gloss 'Freed, released' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 'faliq': ('فالق', 'فالق', None, 'फ़ालिक़', 'فالق', 'batch21_faliq', 'Arabic', 'Male', 'ف ل ق', 'not established', 'high', "Fāliq ('splitter, one who cleaves'). The source record's gloss 'Detached, Separated' is an approximation."),
 "fallah": ("فلاح", "فلاح", None, "फ़ल्लाह", "فلاح", "farmer_hardworking", "Arabic", "Unisex", "ف ل ح", "not established", "high", "Fallāḥ ('farmer, cultivator'). The source record's gloss 'Farmer, Hardworking' is a reasonable rendering."),
 "famida": ("فميدة", "فمیدہ", None, "फ़मीदा", "فميده", "expander", "Unknown", "Female", None, "not established", "low", "The source record's gloss 'Expander' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 'fanan': ('فنان', 'فنان', None, 'फ़नान', 'فنان', 'batch21_fanan', 'Arabic', 'Male', 'ف ن ن', 'not established', 'medium', "Fanan ('branches, artistic styles'). The source record's gloss 'Hidden secret' is unsupported."),
 "fanar": ("فنار", "فنار", None, "फ़नार", "فنار", "lighthouse", "Arabic", "Unisex", "ف ن ر", "not established", "high", "Fanār ('lighthouse, beacon'). The source record's gloss 'Lighthouse' is a reasonable rendering."),
 'fani': ('فاني', 'فانی', None, 'फ़ानी', 'فاني', 'batch21_fani', 'Arabic', 'Female', 'ف ن ي', 'not established', 'high', "Fānī ('mortal, transient'). The source record's gloss 'Happiness' is unsupported."),
 'faouzi': ('فوزي', 'فوزی', None, 'फ़ौज़ी', 'فوزي', 'batch21_faouzi', 'Arabic', 'Male', 'ف و ز', 'not established', 'high', "Fawzī ('of victory, triumphant'). The source record's gloss 'Intelligent, Wise, Rich' is unsupported."),
 "faqeeh": ("فقيه", "فقیه", None, "फ़क़ीह", "فقیه", "expert_islamic_law", "Arabic", "Male", "ف ق ه", "not established", "high", "Faqīh ('jurist, expert in Islamic law'). The source record's gloss 'Expert in Islamic law' is a reasonable rendering."),
 "faqeer": ("فقير", "فقیر", None, "फ़क़ीर", "فقیر", "poor_needy", "Arabic", "Unisex", "ف ق ر", "not established", "high", "Faqīr ('poor, needy, mendicant'). The source record's gloss 'Poor, needy, mendicant' is a reasonable rendering."),
 "faqih": ("فقيه", "فقیه", None, "फ़क़ीह", "فقیه", "expert_scholar_jurist", "Arabic", "Male", "ف ق ه", "not established", "high", "Variant romanization of فقيه ('jurist'). The source record's gloss 'Expert, Scholar, Jurist' is a reasonable rendering."),
 "faqir": ("فقير", "فقیر", None, "फ़क़ीर", "فقیر", "poor_destitute", "Arabic", "Male", "ف ق ر", "not established", "high", "Variant romanization of فقير ('poor, needy'). The source record's gloss 'Poor, destitute, needy' is a reasonable rendering."),
 "fara": ("فرح", "فرح", None, "फ़रा", "فرح", "horse", "Arabic", "Unisex", "ف ر س", "not established", "low", "The source record's gloss 'Horse' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "faraah": ("فرح", "فرح", None, "फ़राह", "فرح", "joy_happiness", "Arabic", "Female", "ف ر ح", "not established", "high", "Faraḥ ('joy, gladness, happiness'). The source record's gloss 'Joy, Happiness' is a reasonable rendering."),
 'faraaz': ('فراز', 'فراز', 'فراز', 'फ़राज़', 'فراز', 'batch21_faraaz', 'Persian', 'Male', 'Persian farāz', 'not established', 'high', "Persian farāz ('height, ascent, elevation'). The source record's gloss 'Protector, Preserver' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'farag': ('فرج', 'فرج', None, 'फ़राग', 'فرج', 'batch21_farag', 'Arabic', 'Male', 'ف ر ج', 'not established', 'high', "Faraj ('relief, deliverance, joy'). The source record's gloss 'Rare, precious, unique' is unsupported."),
 "farah": ("فرح", "فرح", None, "फ़रह", "فرح", "joy", "Arabic", "Female", "ف ر ح", "not established", "high", "Faraḥ ('joy, gladness'). The source record's gloss 'Joy' is a reasonable rendering. The source record classified it as Unknown, which is incorrect."),
 'farahan': ('فرحان', 'فرحان', None, 'फ़रहान', 'فرحان', 'batch21_farahan', 'Arabic', 'Male', 'ف ر ح', 'not established', 'high', "Farḥān ('joyful, glad'). The source record's gloss 'Joyful, Radiant, or Prosperous' is an approximation."),
 'farahani': ('فرحاني', 'فرحانی', None, 'फ़रहानी', 'فرحاني', 'batch21_farahani', 'Arabic', 'Female', 'ف ر ح', 'not established', 'medium', "Farḥānī ('of joy, related to farḥān'). The source record's gloss 'Joy Giver' is an approximation."),
 'farahat': ('فرحات', 'فرحات', None, 'फ़रहात', 'فرحات', 'batch21_farahat', 'Arabic', 'Unisex', 'ف ر ح', 'not established', 'high', "Farḥāt, a plural form related to faraḥ ('joy'). The source record's gloss 'Joy Giver' is an approximation."),
 'farahin': ('فرحين', 'فرحین', None, 'फ़रहीन', 'فرحين', 'batch21_farahin', 'Arabic', 'Unisex', 'ف ر ح', 'not established', 'medium', "Farḥīn, related to faraḥ ('joy'). The source record's gloss 'Joy Giver' is an approximation."),
 'farahmand': ('فرهمند', 'فرہمند', 'فرهمند', 'फ़रहमंद', 'فرهمند', 'batch21_farahmand', 'Persian', 'Male', 'Persian farahmand', 'not established', 'high', "Persian farahmand ('fortunate, blessed, glorious'). The source record's gloss 'Joy giver' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'farahnaz': ('فرحناز', 'فرحناز', 'فرحناز', 'फ़रहनाज़', 'فرحناز', 'batch21_farahnaz', 'Persian', 'Female', 'Arabic faraḥ + Persian nāz', 'not established', 'high', "Persian Farahnāz, from Arabic faraḥ ('joy') and Persian nāz ('charm, delight'). The source record's gloss 'Exalted, Noble, Precious' is unsupported. The source record classified it as Arabic, which is incorrect."),
 "faraj": ("فرج", "فرج", None, "फ़रज", "فرج", "deliverance_relief_joy", "Arabic", "Male", "ف ر ج", "not established", "high", "Faraj ('relief, deliverance, joy'). The source record's gloss 'Deliverance, relief, joy' is a reasonable rendering."),
 'farakh': ('فراخ', 'فراخ', 'فراخ', 'फ़राख़', 'فراخ', 'batch21_farakh', 'Persian', 'Male', 'Persian farākh', 'not established', 'medium', "Persian farākh ('wide, spacious, ample'). The source record's gloss 'Far (distance) + Rah (contentment)' is a folk segmentation and is unsupported. The source record classified it as Arabic, which is incorrect."),
 'faramarz': ('فرامرز', 'فرامرز', 'فرامرز', 'फ़रामर्ज़', 'فرامرز', 'uncertain_form', 'Persian', 'Male', 'Persian Farāmarz', 'not established', 'low', "Farāmarz, a hero of Ferdowsi's Shahnameh, son of Rostam. The source record's gloss 'Expert, Skilled, Victorious' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'farangis': ('فرنگیس', 'فرنگیس', 'فرنگیس', 'फ़रंगीस', 'فرنگیس', 'uncertain_form', 'Persian', 'Female', 'Persian Farangīs', 'not established', 'low', "Farangīs, a female character in Ferdowsi's Shahnameh, wife of Siyāvash. The source record's gloss 'Jewel, Treasure' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'faras': ('فرس', 'فرس', None, 'फ़रस', 'فرس', 'batch21_faras', 'Arabic', 'Male', 'ف ر س', 'not established', 'high', "Faras ('horse, steed'). The source record's gloss 'Strong and powerful' is an approximation."),
 'farasat': ('فراسة', 'فراست', None, 'फ़रासत', 'فراست', 'batch21_farasat', 'Arabic', 'Male', 'ف ر س', 'not established', 'high', "Farāsa ('perspicacity, discernment'). The source record's gloss 'Little Fox' is unsupported."),
 'faraz': ('فراز', 'فراز', 'فراز', 'फ़राज़', 'فراز', 'batch21_faraz', 'Persian', 'Male', 'Persian farāz', 'not established', 'high', "Persian farāz ('height, ascent, elevation'). The source record's gloss 'Determined, Resolute' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'fard': ('فرد', 'فرد', None, 'फ़र्द', 'فرد', 'batch21_fard', 'Arabic', 'Male', 'ف ر د', 'not established', 'high', "Fard ('individual, single, unique'). The source record's gloss 'Carrier, Supporter' is unsupported."),
 'fardan': ('فردان', 'فردان', None, 'फ़र्दान', 'فردان', 'batch21_fardan', 'Arabic', 'Male', 'ف ر د', 'not established', 'medium', "Fardān, related to fard ('individual, unique'). The source record's gloss 'Servant' is unsupported."),
 "fardaws": ("فردوس", "فردوس", "فردوس", "फ़िरदौस", "فردوس", "garden_of_paradise", "Arabic", "Male", "ف ر د س", "الفردوس occurs in the Qur'an (e.g. 18:107)", "high", "Firdaws ('paradise, the highest garden'), occurring in the Qur'an. The source record's gloss 'Garden of paradise' is a reasonable rendering."),
 'fardeen': ('فردين', 'فردین', 'فردین', 'फ़र्दीन', 'فردین', 'uncertain_form', 'Persian', 'Male', 'Persian fardīn', 'not established', 'low', "Fardīn, a Persian name. The source record's gloss 'The One Who Protects' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'fareed': ('فريد', 'فرید', None, 'फ़रीद', 'فرید', 'batch21_fareed', 'Arabic', 'Male', 'ف ر د', 'not established', 'high', "Farīd ('unique, peerless, singular'). The source record's gloss 'Free, Independent' is unsupported."),
 "fareeda": ("فريدة", "فریدہ", None, "फ़रीदा", "فریده", "unique", "Arabic", "Female", "ف ر د", "not established", "high", "Farīda ('unique, precious, peerless'). The source record's gloss 'Unique' is a reasonable rendering. The source record classified it as Unknown, which is incorrect."),
 'fareedah': ('فريدة', 'فریدہ', None, 'फ़रीदा', 'فریده', 'batch21_fareedah', 'Arabic', 'Female', 'ف ر د', 'not established', 'high', "Variant romanization of فريدة ('unique, precious'). The source record's gloss 'Praiseworthy, noble' is unsupported."),
}
