# -*- coding: utf-8 -*-
"""Curated, confidence-graded knowledge table for the islamic batch 22 (fareeha..fateem)."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curated21 import GLOSSES as _G21

GLOSSES = dict(_G21)
GLOSSES.update({
    "happiness_joy": {"en": "Happiness, joy, gladness", "ur": "خوشی، مسرت، شادمانی", "fa": "شادی، خوشحالی، سرور", "hi": "ख़ुशी, आनंद, प्रसन्नता", "ps": "خوښي، مسرت، خوشحالي", "ar": "السعادة، الفرح، السرور"},
    "light_radiant": {"en": "Light, radiant, luminous", "ur": "روشنی، تابناک، درخشاں", "fa": "نور، تابان، درخشان", "hi": "प्रकाश, दीप्त, चमकीला", "ps": "رڼا، ځلانده، تابناک", "ar": "النور، المضيء، اللامع"},
    "light_free": {"en": "Light, free", "ur": "روشنی، آزاد", "fa": "نور، آزاد", "hi": "प्रकाश, आज़ाद", "ps": "رڼا، آزاد", "ar": "النور، الحر"},
    "light_radiant_free": {"en": "Light, radiant, free", "ur": "روشنی، تابناک، آزاد", "fa": "نور، درخشان، آزاد", "hi": "प्रकाश, दीप्त, आज़ाद", "ps": "رڼا، ځلانده، آزاد", "ar": "النور، المضيء، الحر"},
    "rare_precious": {"en": "Rare, precious, unique", "ur": "نایاب، قیمتی، منفرد", "fa": "کم‌یاب، گران‌بها، بی‌همتا", "hi": "दुर्लभ, बहुमूल्य, अनोखा", "ps": "کم پېښ، ګران، بې ساری", "ar": "النادر، الثمين، الفريد"},
    "morning_mist": {"en": "Morning mist, dawn haze", "ur": "صبح کی دھند، بھور کی کہر", "fa": "مه صبحگاهی، بخار بامداد", "hi": "भोर की धुंध, प्रभात की कुहासा", "ps": "د سهار لندې، د سپیده خټه", "ar": "ضباب الصباح، ندى الفجر"},
    "luminous_radiant": {"en": "Luminous, radiant, shining", "ur": "روشن، تابناک، درخشاں", "fa": "درخشان، تابان، فروزان", "hi": "प्रकाशमान, दीप्त, चमकीला", "ps": "روښان، ځلانده، تابناک", "ar": "المضيء، اللامع، المشرق"},
    "traveler_voyager": {"en": "Traveler, voyager, wayfarer", "ur": "مسافر، راہی، سیاح", "fa": "مسافر، رهرو، سیاح", "hi": "यात्री, पथिक, सैलानी", "ps": "مسافر، لاروی، سیاح", "ar": "المسافر، الراحل، السائح"},
    "bringer_of_good_news": {"en": "Bringer of good news, herald", "ur": "خوشخبری دینے والا، مبشر", "fa": "مژده‌آور، بشارت‌دهنده", "hi": "शुभ समाचार देने वाला, सुसंवाददाता", "ps": "زیرې ورکوونکی، مبشر", "ar": "المبشر، حامل البشارة"},
    "moonlight_joyous": {"en": "Moonlight, joyous", "ur": "چاندنی، خوش", "fa": "مهتاب، شادمان", "hi": "चाँदनी, प्रसन्न", "ps": "سپوږمۍ رڼا، خوشحاله", "ar": "ضوء القمر، الفرحان"},
    "unique_precious": {"en": "Unique, precious, peerless", "ur": "منفرد، قیمتی، بے نظیر", "fa": "بی‌همتا، گران‌بها، یگانه", "hi": "अनोखा, बहुमूल्य, अद्वितीय", "ps": "بې ساری، ګران، یوازینی", "ar": "الفريد، الثمين، النادر"},
    "gentle_breeze": {"en": "Gentle breeze, soft wind", "ur": "نرم ہوا، خوشگوار باد", "fa": "نسیم ملایم، باد خوش", "hi": "मंद पवन, कोमल हवा", "ps": "نرمه باد، خوږه باد", "ar": "النسيم، الريح اللطيفة"},
    "protector": {"en": "Protector, guardian, defender", "ur": "محافظ، نگہبان، حامی", "fa": "نگهبان، محافظ، پاسدار", "hi": "रक्षक, संरक्षक, पालक", "ps": "ساتونکی، پالونکی، محافظ", "ar": "الحافظ، الراعي، الصائن"},
    "happy": {"en": "Happy, glad, joyful", "ur": "خوش، شادمان، مسرور", "fa": "شاد، خوشحال، مسرور", "hi": "प्रसन्न, ख़ुश, आनंदित", "ps": "خوشحاله، خوش، مسرور", "ar": "السعيد، الفرحان، المسرور"},
    "moonlight_radiant_one": {"en": "Moonlight, radiant one", "ur": "چاندنی، تابناک", "fa": "مهتاب، درخشان", "hi": "चाँदनी, दीप्त", "ps": "سپوږمۍ رڼا، ځلانده", "ar": "ضوء القمر، المضيء"},
    "joyful_content_delighted": {"en": "Joyful, content, delighted", "ur": "خوش، مطمئن، شادمان", "fa": "شاد، خرسند، مسرور", "hi": "प्रसन्न, संतुष्ट, आनंदित", "ps": "خوشحاله، قناعت کوونکی، مسرور", "ar": "الفرحان، الراضي، المسرور"},
    "wise_knowledgeable_scholar": {"en": "Wise, knowledgeable, scholar", "ur": "دانا، عالم، دانشور", "fa": "دانا، دانشمند، خردمند", "hi": "बुद्धिमान, विद्वान, ज्ञानी", "ps": "پوه، عالم، هوښیار", "ar": "الحكيم، العالم، العارف"},
    "happiness_joy2": {"en": "Happiness, joy", "ur": "خوشی، مسرت", "fa": "شادی، سرور", "hi": "ख़ुशी, आनंद", "ps": "خوښي، مسرت", "ar": "السعادة، الفرح"},
    "joy_happiness2": {"en": "Joy, happiness", "ur": "خوشی، مسرت", "fa": "شادی، خوشحالی", "hi": "आनंद, ख़ुशी", "ps": "خوښي، خوشحالي", "ar": "الفرح، السعادة"},
    "joy_giver2": {"en": "Joy giver, bringer of joy", "ur": "خوشی دینے والا، مسرت بخشنے والا", "fa": "شادی‌بخش، سرورآفرین", "hi": "आनंद देने वाला, ख़ुशी देने वाला", "ps": "خوښي ورکوونکی، مسرت بخښونکی", "ar": "مانح الفرح، باعث السعادة"},
    "bright_radiant_one": {"en": "Bright, radiant one", "ur": "روشن، تابناک", "fa": "درخشان، تابان", "hi": "चमकीला, दीप्त", "ps": "ځلانده، روښان", "ar": "المضيء، اللامع"},
    "fragrant_or_precious": {"en": "Fragrant or precious", "ur": "خوشبودار یا قیمتی", "fa": "خوشبو یا گران‌بها", "hi": "सुगंधित या बहुमूल्य", "ps": "خوشبویه یا ګران", "ar": "العطري أو الثمين"},
    "gifted_rare": {"en": "Gifted, rare", "ur": "باصلاحیت، نایاب", "fa": "بااستعداد، کم‌یاب", "hi": "प्रतिभाशाली, दुर्लभ", "ps": "بااستعداد، کم پېښ", "ar": "الموهوب، النادر"},
    "beautiful_joyful": {"en": "Beautiful, joyful", "ur": "خوبصورت، خوش", "fa": "زیبا، شادمان", "hi": "सुंदर, प्रसन्न", "ps": "ښکلی، خوشحاله", "ar": "الجميل، الفرحان"},
    "glorious_radiant": {"en": "Glorious, radiant", "ur": "شاندار، تابناک", "fa": "شکوهمند، درخشان", "hi": "गौरवशाली, दीप्त", "ps": "شکوهمن، ځلانده", "ar": "المجيد، المضيء"},
    "light_of_the_sky": {"en": "Light of the sky", "ur": "آسمان کی روشنی", "fa": "نور آسمان", "hi": "आकाश का प्रकाश", "ps": "د آسمان رڼا", "ar": "نور السماء"},
    "gentle_beautiful": {"en": "Gentle, beautiful", "ur": "نرم، خوبصورت", "fa": "ملایم، زیبا", "hi": "कोमल, सुंदर", "ps": "نرم، ښکلی", "ar": "اللطيف، الجميل"},
    "brave_victorious": {"en": "Brave, victorious", "ur": "بہادر، فاتح", "fa": "دلیر، پیروز", "hi": "बहादुर, विजयी", "ps": "زړور، بریالی", "ar": "الشجاع، المنتصر"},
    "precious_rare_unique": {"en": "Precious, rare, unique", "ur": "قیمتی، نایاب، منفرد", "fa": "گران‌بها، کم‌یاب، بی‌همتا", "hi": "बहुमूल्य, दुर्लभ, अनोखा", "ps": "ګران، کم پېښ، بې ساری", "ar": "الثمين، النادر، الفريد"},
    "rare_precious_unique2": {"en": "Rare, precious, unique", "ur": "نایاب، قیمتی، منفرد", "fa": "کم‌یاب، گران‌بها، بی‌همتا", "hi": "दुर्लभ, बहुमूल्य, अनोखा", "ps": "کم پېښ، ګران، بې ساری", "ar": "النادر، الثمين، الفريد"},
    "precious_unique": {"en": "Precious, unique", "ur": "قیمتی، منفرد", "fa": "گران‌بها، بی‌همتا", "hi": "बहुमूल्य, अनोखा", "ps": "ګران، بې ساری", "ar": "الثمين، الفريد"},
    "unique_distinguished": {"en": "Unique, distinguished", "ur": "منفرد، ممتاز", "fa": "بی‌همتا، برجسته", "hi": "अनोखा, विशिष्ट", "ps": "بې ساری، ممتاز", "ar": "الفريد، المميز"},
    "victorious": {"en": "Victorious, triumphant", "ur": "فاتح، کامیاب", "fa": "پیروز، فاتح", "hi": "विजयी, विजेता", "ps": "بریالی، فاتح", "ar": "المنصور، الفائز"},
    "joyful_happy": {"en": "Joyful, happy", "ur": "خوش، شادمان", "fa": "شاد، خوشحال", "hi": "प्रसन्न, ख़ुश", "ps": "خوشحاله، خوش", "ar": "الفرحان، السعيد"},
    "joyful": {"en": "Joyful, glad", "ur": "خوش، شادمان", "fa": "شاد، مسرور", "hi": "प्रसन्न, आनंदित", "ps": "خوشحاله، مسرور", "ar": "الفرحان، المسرور"},
    "exalted_noble_one": {"en": "Exalted, noble one", "ur": "بلند، نجیب", "fa": "بلندمرتبه، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "الرفيع، النبيل"},
    "little_fine": {"en": "Little, fine, delicate", "ur": "چھوٹا، نفیس، باریک", "fa": "کوچک، نازک، لطیف", "hi": "छोटा, महीन, नाज़ुक", "ps": "وړوکی، نازک، نری", "ar": "الصغير، الرقيق، اللطيف"},
    "jewel_treasure2": {"en": "Jewel, treasure", "ur": "جواہر، خزانہ", "fa": "گوهر، گنج", "hi": "रत्न, ख़ज़ाना", "ps": "جواهر، خزانه", "ar": "الجوهرة، الكنز"},
    "wise_judge": {"en": "Wise judge, discerning", "ur": "دانا منصف، فیصلہ کرنے والا", "fa": "داور دانا، فیصله‌کننده", "hi": "बुद्धिमान न्यायाधीश, विवेकी", "ps": "پوه قاضي، فیصله کوونکی", "ar": "القاضي الحكيم، الفاصل"},
    "knight": {"en": "Knight, horseman, cavalier", "ur": "شہسوار، گھڑسوار، بہادر", "fa": "سوار، پهلوان، دلیر", "hi": "शूरवीर, घुड़सवार, बहादुर", "ps": "سپور، زړور، اتل", "ar": "الفارس، الشجاع، البطل"},
    "light_bright_radiant": {"en": "Light, bright, radiant", "ur": "روشنی، روشن، تابناک", "fa": "نور، روشن، درخشان", "hi": "प्रकाश, चमकीला, दीप्त", "ps": "رڼا، روښان، ځلانده", "ar": "النور، المضيء، اللامع"},
    "angel_messenger": {"en": "Angel, messenger", "ur": "فرشتہ، پیغام لانے والا", "fa": "فرشته، پیام‌آور", "hi": "देवदूत, संदेशवाहक", "ps": "پرښته، پیغام رسوونکی", "ar": "الملاك، الرسول"},
    "luminous_radiant2": {"en": "Luminous, radiant", "ur": "روشن، تابناک", "fa": "درخشان، تابان", "hi": "प्रकाशमान, दीप्त", "ps": "روښان، ځلانده", "ar": "المضيء، اللامع"},
    "joyful2": {"en": "Joyful, happy", "ur": "خوش، شادمان", "fa": "شاد، خوشحال", "hi": "प्रसन्न, ख़ुश", "ps": "خوشحاله، خوش", "ar": "الفرحان، السعيد"},
    "free_independent2": {"en": "Free, independent", "ur": "آزاد، خودمختار", "fa": "آزاد، مستقل", "hi": "आज़ाद, स्वतंत्र", "ps": "آزاد، خپلواک", "ar": "الحر، المستقل"},
    "jasmine_or_fragrant": {"en": "Jasmine or fragrant", "ur": "چنبیلی یا خوشبودار", "fa": "یاس یا خوشبو", "hi": "चमेली या सुगंधित", "ps": "یاسمین یا خوشبویه", "ar": "الياسمين أو العطري"},
    "free_independent3": {"en": "Free, independent", "ur": "آزاد، خودمختار", "fa": "آزاد، مستقل", "hi": "आज़ाद, स्वतंत्र", "ps": "آزاد، خپلواک", "ar": "الحر، المستقل"},
    "wise_righteous": {"en": "Wise, righteous", "ur": "دانا، نیک", "fa": "دانا، نیکوکار", "hi": "बुद्धिमान, धर्मात्मा", "ps": "پوه، نیک", "ar": "الحكيم، الصالح"},
    "victorious_triumphant2": {"en": "Victorious, triumphant", "ur": "فاتح، کامیاب", "fa": "پیروز، فاتح", "hi": "विजयी, विजेता", "ps": "بریالی، فاتح", "ar": "المنصور، الفائز"},
    "blessed_and_fortunate": {"en": "Blessed and fortunate", "ur": "بابرکت اور خوش نصیب", "fa": "فرخنده و نیک‌بخت", "hi": "धन्य और भाग्यशाली", "ps": "برکت والا او نیکمرغه", "ar": "المبارك، المحظوظ"},
    "highly_praiseworthy": {"en": "Highly praiseworthy", "ur": "بہت قابلِ تعریف", "fa": "بسیار ستوده", "hi": "अत्यंत प्रशंसनीय", "ps": "ډېر د ستاینې وړ", "ar": "المحمود جداً، المستحق"},
    "command_decree_edict": {"en": "Command, decree, edict", "ur": "حکم، فرمان، ارشاد", "fa": "فرمان، دستور، حکم", "hi": "आदेश, फ़रमान, हुक्म", "ps": "حکم، فرمان، امر", "ar": "الأمر، الحكم، المرسوم"},
    "excellent_noble": {"en": "Excellent, noble", "ur": "بہترین، نجیب", "fa": "برجسته، نجیب", "hi": "उत्कृष्ट, कुलीन", "ps": "غوره، نجیب", "ar": "الفاضل، النبيل"},
    "road_travel": {"en": "Road, travel, journey", "ur": "راستہ، سفر", "fa": "راه، سفر", "hi": "मार्ग, यात्रा", "ps": "لار، سفر", "ar": "الطريق، السفر"},
    "gentle_beautiful2": {"en": "Gentle, beautiful", "ur": "نرم، خوبصورت", "fa": "ملایم، زیبا", "hi": "कोमल, सुंदर", "ps": "نرم، ښکلی", "ar": "اللطيف، الجميل"},
    "gardener_of_the_garden": {"en": "Gardener of the garden", "ur": "باغ کا مالی", "fa": "باغبان باغ", "hi": "बाग़ का माली", "ps": "د باغ باغوان", "ar": "بستاني الحديقة"},
    "ruler_king": {"en": "Ruler, king", "ur": "حکمران، بادشاہ", "fa": "فرمانروا، شاه", "hi": "शासक, राजा", "ps": "واکمن، پاچا", "ar": "الحاكم، الملك"},
    "lord_master": {"en": "Lord, master", "ur": "مالک، سردار", "fa": "سرور، خداوند", "hi": "स्वामी, मालिक", "ps": "مالک، سردار", "ar": "السيد، المولى"},
    "liberator_free_from_evil": {"en": "Liberator, free from evil", "ur": "آزاد کرنے والا، برائی سے پاک", "fa": "رهایی‌بخش، پاک از بدی", "hi": "मुक्तिदाता, बुराई से मुक्त", "ps": "خوشې کوونکی، له بدۍ پاک", "ar": "المحرر، المنقذ"},
    "one_who_distinguishes": {"en": "One who distinguishes right from wrong", "ur": "حق و باطل میں فرق کرنے والا", "fa": "جداکنندهٔ حق از باطل", "hi": "सत्य-असत्य में भेद करने वाला", "ps": "د حق او باطل توپیر کوونکی", "ar": "الفاروق، المفرق بين الحق والباطل"},
    "owner_of_the_great_fortress": {"en": "Owner of the great fortress", "ur": "عظیم قلعے کا مالک", "fa": "دارندهٔ دژ بزرگ", "hi": "महान किले का स्वामी", "ps": "د لوی کلا مالک", "ar": "صاحب الحصن العظيم"},
    "discriminator_between_truth_and_falsehood": {"en": "Discriminator between truth and falsehood", "ur": "حق و باطل میں فرق کرنے والا", "fa": "جداکنندهٔ حق از باطل", "hi": "सत्य और असत्य में भेद करने वाला", "ps": "د حق او باطل توپیر کوونکی", "ar": "الفاروق، المفرق بين الحق والباطل"},
    "determined_victorious": {"en": "Determined, victorious", "ur": "پکا، فاتح", "fa": "مصمم، پیروز", "hi": "दृढ़, विजयी", "ps": "ټینګ، بریالی", "ar": "الحازم، المنتصر"},
    "a_type_of_palm_tree": {"en": "A type of palm tree", "ur": "ایک قسم کا کھجور کا درخت", "fa": "نوعی درخت نخل", "hi": "एक प्रकार का ताड़ वृक्ष", "ps": "د خرما یو ډول ونه", "ar": "نوع من النخيل"},
    "fragrant_delightful": {"en": "Fragrant, delightful", "ur": "خوشبودار، دلکش", "fa": "خوشبو، دلپذیر", "hi": "सुगंधित, आनंददायक", "ps": "خوشبویه، خوږ", "ar": "العطري، اللذيذ"},
    "horses": {"en": "Horses, steeds", "ur": "گھوڑے، اسپ", "fa": "اسب‌ها، باره‌ها", "hi": "घोड़े, अश्व", "ps": "آسونه، اسپان", "ar": "الخيول، الأفراس"},
    "bringer_of_good_fortune": {"en": "Bringer of good fortune", "ur": "خوش نصیبی لانے والا", "fa": "نیک‌بختی‌آور", "hi": "सौभाग्य लाने वाला", "ps": "نیکمرغۍ راوړونکی", "ar": "جالب الحظ، السعيد"},
    "happy_prosperous": {"en": "Happy, prosperous", "ur": "خوش، خوشحال", "fa": "شاد، بهروز", "hi": "प्रसन्न, समृद्ध", "ps": "خوشحاله، هوسا", "ar": "السعيد، المزدهر"},
    "brave_warrior": {"en": "Brave warrior", "ur": "بہادر جنگجو", "fa": "جنگاور دلیر", "hi": "बहादुर योद्धा", "ps": "زړور جنګیالی", "ar": "المحارب الشجاع"},
    "victorious_one": {"en": "Victorious one", "ur": "فاتح، کامیاب", "fa": "پیروز، فاتح", "hi": "विजयी, विजेता", "ps": "بریالی، فاتح", "ar": "المنصور، الفائز"},
    "brave_victorious2": {"en": "Brave, victorious", "ur": "بہادر، فاتح", "fa": "دلیر، پیروز", "hi": "बहादुर, विजयी", "ps": "زړور، بریالی", "ar": "الشجاع، المنتصر"},
    "one_who_distinguishes_between_truth_and_falsehood": {"en": "One who distinguishes between truth and falsehood", "ur": "حق و باطل میں فرق کرنے والا", "fa": "جداکنندهٔ حق از باطل", "hi": "सत्य और असत्य में भेद करने वाला", "ps": "د حق او باطل توپیر کوونکی", "ar": "الفاروق، المفرق بين الحق والباطل"},
    "coldness_of_water": {"en": "Coldness of water, cool water", "ur": "پانی کی ٹھنڈک، ٹھنڈا پانی", "fa": "سردی آب، آب خنک", "hi": "जल की शीतलता, ठंडा जल", "ps": "د اوبو ساړه، یخ اوبه", "ar": "برودة الماء، الماء البارد"},
    "free_liberated": {"en": "Free, liberated", "ur": "آزاد، رہا", "fa": "آزاد، رها", "hi": "आज़ाद, मुक्त", "ps": "آزاد، خوشې", "ar": "الحر، المعتوق"},
    "cry_for_help": {"en": "Cry for help, appeal", "ur": "مدد کی پکار، فریاد", "fa": "فریاد، دادخواهی", "hi": "सहायता की पुकार, फ़रियाद", "ps": "د مرستې چیغه، فریاد", "ar": "الاستغاثة، الصرخة"},
    "moon_light": {"en": "Moonlight", "ur": "چاندنی، مہتاب", "fa": "مهتاب، نور ماه", "hi": "चाँदनी, चंद्र-प्रकाश", "ps": "سپوږمۍ رڼا، مهتاب", "ar": "ضوء القمر، ضياء القمر"},
    "journey_adventure": {"en": "Journey, adventure", "ur": "سفر، مہم", "fa": "سفر، ماجرا", "hi": "यात्रा, साहसिक कार्य", "ps": "سفر، ماجرا", "ar": "الرحلة، المغامرة"},
    "adorned_with_precious_gems": {"en": "Adorned with precious gems", "ur": "قیمتی جواہرات سے آراستہ", "fa": "آراسته به گوهرهای گران‌بها", "hi": "बहुमूल्य रत्नों से सुसज्जित", "ps": "د ګران جواهرو سره ښکلی شوی", "ar": "المزين بالجواهر الثمينة"},
    "strong_ambitious_valiant": {"en": "Strong, ambitious, valiant", "ur": "طاقتور، بلند ہمت، بہادر", "fa": "نیرومند، بلندهمت، دلیر", "hi": "शक्तिशाली, महत्वाकांक्षी, वीर", "ps": "پیاوړی، هیلهمند، زړور", "ar": "القوي، الطموح، الشجاع"},
    "exalted_noble2": {"en": "Exalted, noble", "ur": "بلند، نجیب", "fa": "بلندمرتبه، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "الرفيع، النبيل"},
    "protector_defender": {"en": "Protector, defender", "ur": "محافظ، مدافع", "fa": "نگهبان، مدافع", "hi": "रक्षक, रक्षावाहक", "ps": "ساتونکی، مدافع", "ar": "الحافظ، المدافع"},
    "one_who_performs_obligations": {"en": "One who performs obligations", "ur": "فرائض ادا کرنے والا", "fa": "انجام‌دهندهٔ واجبات", "hi": "कर्तव्य निभाने वाला", "ps": "د فرایضو ادا کوونکی", "ar": "المؤدي للواجبات"},
    "gardener": {"en": "Gardener", "ur": "مالی، باغبان", "fa": "باغبان", "hi": "माली, बाग़बान", "ps": "باغوان", "ar": "البستاني"},
    "prince_heir": {"en": "Prince, heir", "ur": "شہزادہ، وارث", "fa": "شاهزاده، وارث", "hi": "राजकुमार, उत्तराधिकारी", "ps": "شهزاده، وارث", "ar": "الأمير، الوارث"},
    "exalted_noble3": {"en": "Exalted, noble", "ur": "بلند، نجیب", "fa": "بلندمرتبه، نجیب", "hi": "उच्च, कुलीन", "ps": "لوړ، نجیب", "ar": "الرفيع، النبيل"},
    "wise_intelligent_knowledgeable": {"en": "Wise, intelligent, knowledgeable", "ur": "دانا، ذہین، عالم", "fa": "دانا، هوشمند، دانشمند", "hi": "बुद्धिमान, ज्ञानी, विद्वान", "ps": "پوه، ځیرک، عالم", "ar": "الحكيم، الذكي، العالم"},
    "lady_of_paradise": {"en": "Lady of paradise", "ur": "جنت کی خاتون", "fa": "بانوی بهشت", "hi": "जन्नत की महिला", "ps": "د جنت ښځه", "ar": "سيدة الجنة، الحوراء"},
    "wise_intelligent_bright": {"en": "Wise, intelligent, bright", "ur": "دانا، ذہین، روشن", "fa": "دانا، هوشمند، درخشان", "hi": "बुद्धिमान, ज्ञानी, चमकीला", "ps": "پوه، ځیرک، روښان", "ar": "الحكيم، الذكي، المضيء"},
    "intelligent_wise_knowledgeable": {"en": "Intelligent, wise, knowledgeable", "ur": "ذہین، دانا، عالم", "fa": "هوشمند، دانا، دانشمند", "hi": "बुद्धिमान, ज्ञानी, विद्वान", "ps": "ځیرک، پوه، عالم", "ar": "الذكي، الحكيم، العالم"},
    "healer_helper": {"en": "Healer, helper", "ur": "شفا دینے والا، مددگار", "fa": "شفابخش، یاور", "hi": "चिकित्सक, सहायक", "ps": "شفا ورکوونکی، مرستندوی", "ar": "الشافي، المعين"},
    "wise_knowledgeable": {"en": "Wise, knowledgeable", "ur": "دانا، عالم", "fa": "دانا، دانشمند", "hi": "बुद्धिमान, विद्वान", "ps": "پوه، عالم", "ar": "الحكيم، العالم"},
    "wise_intelligent2": {"en": "Wise, intelligent", "ur": "دانا، ذہین", "fa": "دانا، هوشمند", "hi": "बुद्धिमान, ज्ञानी", "ps": "پوه، ځیرک", "ar": "الحكيم، الذكي"},
    "healer": {"en": "Healer", "ur": "شفا دینے والا", "fa": "شفابخش", "hi": "चिकित्सक", "ps": "شفا ورکوونکی", "ar": "الشافي"},
    "slender_agile": {"en": "Slender, agile", "ur": "پتلا، پھرتیلا", "fa": "باریک، چابک", "hi": "पतला, फुर्तीला", "ps": "نری، چټک", "ar": "النحيف، الرشيق"},
    "conquering": {"en": "Conquering, victorious", "ur": "فاتح، غالب", "fa": "فاتح، پیروز", "hi": "विजयी, विजेता", "ps": "فاتح، بریالی", "ar": "الغالب، المنتصر"},
    "little_one_young_girl": {"en": "Little one, young girl", "ur": "چھوٹی، ننھی بچی", "fa": "کوچک، دخترک", "hi": "नन्ही, छोटी बालिका", "ps": "وړوکې، ننګوله", "ar": "الصغيرة، الفتاة"},
    "successor_opener": {"en": "Successor, opener", "ur": "جانشین، کھولنے والا", "fa": "جانشین، گشاینده", "hi": "उत्तराधिकारी, उद्घाटक", "ps": "ځای ناستی، پرانیستونکی", "ar": "الخليفة، الفاتح"},
})

GLOSSES.update({
    "batch22_fareena": {"en": 'Related to splendour, light'},
    "batch22_farees": {"en": 'Related to horses, steeds'},
    "batch22_fareh": {"en": 'Joyful, glad'},
    "batch22_fareha": {"en": 'Joy, happiness'},
    "batch22_farehah": {"en": 'Joy, happiness'},
    "batch22_farehan": {"en": 'Joyful, glad'},
    "batch22_fares": {"en": 'Knight, horseman, cavalier'},
    "batch22_farha": {"en": 'Joy, gladness'},
    "batch22_farhaad": {"en": 'Merited, obtained'},
    "batch22_farhaan": {"en": 'Joyful, glad'},
    "batch22_farhad": {"en": 'Merited, obtained'},
    "batch22_farhadi": {"en": 'Of or related to Farhād'},
    "batch22_farhah": {"en": 'Joy, gladness'},
    "batch22_farhang": {"en": 'Culture, education, dictionary'},
    "batch22_farhi": {"en": 'Related to joy'},
    "batch22_farhiya": {"en": 'Related to joy'},
    "batch22_faria": {"en": 'Eminent, high'},
    "batch22_farih": {"en": 'Joyful, glad'},
    "batch22_farinaz": {"en": 'Splendour, charm'},
    "batch22_fariq": {"en": 'One who distinguishes, separator'},
    "batch22_fariz": {"en": 'Related to duty, obligation'},
    "batch22_fariza": {"en": 'Duty, obligation'},
    "batch22_farjad": {"en": 'Earned, gained; wise'},
    "batch22_farjam": {"en": 'Conclusion, end, outcome'},
    "batch22_farkhunda": {"en": 'Fortunate, blessed'},
    "batch22_farnaz": {"en": 'Splendour, charm'},
    "batch22_farokh": {"en": 'Happy, auspicious, fortunate'},
    "batch22_farookh": {"en": 'Happy, auspicious, fortunate'},
    "batch22_farouk": {"en": 'One who distinguishes right from wrong'},
    "batch22_farqad": {"en": 'Calf; star name'},
    "batch22_farraj": {"en": 'One who relieves'},
    "batch22_farras": {"en": 'Related to horses, steeds'},
    "batch22_farrokh": {"en": 'Happy, auspicious, fortunate'},
    "batch22_farsheed": {"en": 'Splendour, light'},
    "batch22_farwa": {"en": 'Fur, pelt'},
    "batch22_farzaana": {"en": 'Wise, learned, intelligent'},
    "batch22_farzad": {"en": 'Splendid birth'},
    "batch22_farzam": {"en": 'Worthy, deserving'},
    "batch22_farzan": {"en": 'Wise, intelligent'},
    "batch22_farzana": {"en": 'Wise, learned, intelligent'},
    "batch22_farzanah": {"en": 'Wise, learned'},
    "batch22_farzand": {"en": 'Child, offspring, son'},
    "batch22_farzaneh": {"en": 'Wise, learned, intelligent'},
    "batch22_farzeena": {"en": 'Related to Farzīn, wise'},
    "batch22_faseeh": {"en": 'Eloquent, articulate'},
    "batch22_faseeha": {"en": 'Eloquent, articulate'},
    "batch22_fasih": {"en": 'Eloquent, articulate'},
    "batch22_fasiha": {"en": 'Eloquent, articulate'},
    "batch22_fatan": {"en": 'Charming, alluring'},
    "batch22_fatanah": {"en": 'Charming, alluring'},
    "batch22_fariba": {"en": 'Charming, captivating, enchanting'},
})

GLOSSES.update({"batch22_farhana": {"en": "Joyful"}})

# name -> (ar, ur, fa, hi, ps, gloss, origin, gender, root, quranic, conf, note)
CUR = {
 "fareeha": ("فريحة", "فریحہ", None, "फ़रीहा", "فريحه", "happiness_joy", "Arabic", "Female", "ف ر ح", "not established", "high", "Farīḥa, the diminutive of faraḥ ('joy, happiness'). The source record's gloss 'Happiness' is a reasonable rendering."),
 "fareen": ("فرين", "فرین", "فرین", "फ़रीन", "فرین", "light_radiant", "Persian", "Female", "Persian far", "not established", "medium", "Persian farīn ('bright, radiant'). The source record's gloss 'Light, Radiant' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 'fareena': ('فرينة', 'فرینہ', 'فرینه', 'फ़रीना', 'فرینه', 'batch22_fareena', 'Persian', 'Female', 'Persian far', 'not established', 'medium', "Persian farīna, related to far ('splendour, light'). The source record's gloss 'Light, Free' is an approximation. The source record classified it as Arabic, which is incorrect."),
 'farees': ('فريس', 'فریس', None, 'फ़रीस', 'فريس', 'batch22_farees', 'Arabic', 'Male', 'ف ر س', 'not established', 'medium', "Firīs, related to faras ('horse, steed'). The source record's gloss 'Light, radiant, free' is unsupported."),
 'fareh': ('فارح', 'فارح', None, 'फ़ारेह', 'فارح', 'batch22_fareh', 'Arabic', 'Male', 'ف ر ح', 'not established', 'medium', "Fāriḥ ('joyful, glad'). The source record's gloss 'Rare, precious' is unsupported."),
 'fareha': ('فريحة', 'فریحہ', None, 'फ़रीहा', 'فريحه', 'batch22_fareha', 'Arabic', 'Female', 'ف ر ح', 'not established', 'medium', "Farīḥa, diminutive of faraḥ ('joy'). The source record's gloss 'Morning Mist' is unsupported."),
 'farehah': ('فريحة', 'فریحہ', None, 'फ़रीहा', 'فريحه', 'batch22_farehah', 'Arabic', 'Female', 'ف ر ح', 'not established', 'medium', "Variant romanization of فريحة, diminutive of faraḥ ('joy'). The source record's gloss 'Light, Radiant' is unsupported."),
 'farehan': ('فرهان', 'فرہان', None, 'फ़रहान', 'فرحان', 'batch22_farehan', 'Arabic', 'Male', 'ف ر ح', 'not established', 'medium', "Farhān ('joyful, glad'). The source record's gloss 'Luminous, Radiant' is unsupported."),
 'fares': ('فارس', 'فارس', None, 'फ़ारेस', 'فارس', 'batch22_fares', 'Arabic', 'Male', 'ف ر س', 'not established', 'high', "Fāris ('knight, horseman, cavalier'). The source record's gloss 'Traveler, Voyager' is unsupported."),
 'farha': ('فرحة', 'فرحہ', None, 'फ़रहा', 'فرحه', 'batch22_farha', 'Arabic', 'Female', 'ف ر ح', 'not established', 'high', "Farḥa ('joy, gladness'). The source record's gloss 'Light, Radiant' is unsupported."),
 'farhaad': ('فرهاد', 'فرہاد', 'فرهاد', 'फ़रहाद', 'فرهاد', 'batch22_farhaad', 'Persian', 'Male', 'Old Iranian fra-hāta', 'not established', 'high', "Persian Farhād, from Old Iranian fra-hāta- ('merited, obtained'), borne by Parthian kings. The source record's gloss 'Bringer of good news' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'farhaan': ('فرحان', 'فرحان', None, 'फ़रहान', 'فرحان', 'batch22_farhaan', 'Arabic', 'Male', 'ف ر ح', 'not established', 'high', "Farḥān ('joyful, glad'). The source record's gloss 'Moonlight, Joyous' is an approximation."),
 'farhad': ('فرهاد', 'فرہاد', 'فرهاد', 'फ़रहाद', 'فرهاد', 'batch22_farhad', 'Persian', 'Male', 'Old Iranian fra-hāta', 'not established', 'high', "Persian Farhād, from Old Iranian fra-hāta- ('merited, obtained'). The source record's gloss 'Unique, Precious' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'farhadi': ('فرهادی', 'فرہادی', 'فرهادی', 'फ़रहादी', 'فرهادي', 'batch22_farhadi', 'Persian', 'Male', 'Old Iranian fra-hāta', 'not established', 'medium', "Persian Farhādī, the nisba of Farhād. The source record's gloss 'Unique, Precious' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'farhah': ('فرحة', 'فرحہ', None, 'फ़रहा', 'فرحه', 'batch22_farhah', 'Arabic', 'Female', 'ف ر ح', 'not established', 'high', "Farḥa ('joy, gladness'). The source record's gloss 'Gentle Breeze' is unsupported."),
 "farham": ("فرهام", "فرہام", None, "फ़रहाम", "فرهام", "protector", "Unknown", "Male", None, "not established", "low", "The source record's gloss 'Protector' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "farhan": ("فرحان", "فرحان", None, "फ़रहान", "فرحان", "happy", "Arabic", "Male", "ف ر ح", "not established", "high", "Farḥān ('joyful, glad, happy'). The source record's gloss 'Happy' is a reasonable rendering. The source record classified it as Unknown, which is incorrect."),
 'farhana': ('فرحانة', 'فرحانہ', None, 'फ़रहाना', 'فرحانه', 'batch22_farhana', 'Arabic', 'Female', 'ف ر ح', 'not established', 'high', "Farḥāna, the feminine of farḥān ('joyful'). The source record's gloss 'Moonlight, radiant one' is unsupported."),
 "farhanah": ("فرحانة", "فرحانہ", None, "फ़रहाना", "فرحانه", "joyful_content_delighted", "Arabic", "Female", "ف ر ح", "not established", "high", "Variant romanization of فرحانة, feminine of farḥān ('joyful'). The source record's gloss 'Joyful, content, delighted' is a reasonable rendering."),
 'farhang': ('فرهنگ', 'فرہنگ', 'فرهنگ', 'फ़रहंग', 'فرهنګ', 'batch22_farhang', 'Persian', 'Male', 'Persian farhang', 'not established', 'high', "Persian farhang ('culture, education, dictionary'). The source record's gloss 'Wise, Knowledgeable, Scholar' is an approximation. The source record classified it as Arabic, which is incorrect."),
 "farhat": ("فرحة", "فرحت", None, "फ़रहत", "فرحت", "happiness_joy2", "Arabic", "Unisex", "ف ر ح", "not established", "high", "Farḥat ('joy, gladness, delight'). The source record's gloss 'Happiness, Joy' is a reasonable rendering."),
 "farhath": ("فرحة", "فرحت", None, "फ़रहत", "فرحت", "joy_happiness2", "Arabic", "Unisex", "ف ر ح", "not established", "high", "Variant romanization of فرحت ('joy, gladness'). The source record's gloss 'Joy, Happiness' is a reasonable rendering."),
 "farhatun": ("فرحتون", "فرحتون", None, "फ़रहतुन", "فرحتون", "joy_giver2", "Arabic", "Female", "ف ر ح", "not established", "low", "The source record's gloss 'Joy Giver' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "farheen": ("فرحين", "فرحین", "فرحین", "फ़रहीन", "فرحین", "bright_radiant_one", "Persian", "Female", "Persian far", "not established", "medium", "Persian farhīn, related to far ('splendour, light'). The source record's gloss 'Bright, radiant one' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 'farhi': ('فرحي', 'فرحی', None, 'फ़रही', 'فرحي', 'batch22_farhi', 'Arabic', 'Female', 'ف ر ح', 'not established', 'medium', "Farḥī, related to faraḥ ('joy'). The source record's gloss 'Fragrant or Precious' is unsupported."),
 'farhiya': ('فرحية', 'فرحیہ', None, 'फ़रहिया', 'فرحيه', 'batch22_farhiya', 'Arabic', 'Female', 'ف ر ح', 'not established', 'medium', "Farḥiyya, related to faraḥ ('joy'). The source record's gloss 'Gifted, Rare' is unsupported."),
 "fari": ("فاري", "فاری", None, "फ़ारी", "فاري", "beautiful_joyful", "Unknown", "Female", None, "not established", "low", "The source record's gloss 'Beautiful, Joyful' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 'faria': ('فريعة', 'فریعہ', None, 'फ़रीआ', 'فريعه', 'batch22_faria', 'Arabic', 'Female', 'ف ر ع', 'not established', 'medium', "Farīʿa ('eminent, high'). The source record's gloss 'Glorious, Radiant' is unsupported."),
 "fariah": ("فارية", "فاریہ", None, "फ़ारिया", "فاريه", "light_of_the_sky", "Unknown", "Female", None, "not established", "low", "The source record's gloss 'Light of the sky' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 'fariba': ('فريبا', 'فریبا', 'فریبا', 'फ़रीबा', 'فریبا', 'batch22_fariba', 'Persian', 'Female', 'Persian farībā', 'not established', 'high', "Persian farībā ('charming, captivating, enchanting'). The source record's gloss 'Gentle, Beautiful' is an approximation. The source record classified it as Arabic, which is incorrect."),
 "fariborz": ("فريبورز", "فریبرز", "فریبرز", "फ़रीबोर्ज़", "فریبرز", "brave_victorious", "Persian", "Male", "Persian Farīburz", "not established", "high", "Farīburz, a hero of Ferdowsi's Shahnameh, son of Kay Kavus. The source record's gloss 'Brave, Victorious' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 "farid": ("فريد", "فرید", None, "फ़रीद", "فرید", "precious_rare_unique", "Arabic", "Male", "ف ر د", "not established", "high", "Farīd ('unique, peerless, precious'). The source record's gloss 'precious, rare, unique' is a reasonable rendering."),
 "farida": ("فريدة", "فریدہ", None, "फ़रीदा", "فریده", "rare_precious_unique2", "Arabic", "Female", "ف ر د", "not established", "high", "Farīda ('unique, precious, peerless'). The source record's gloss 'Rare, Precious, Unique' is a reasonable rendering."),
 "faridah": ("فريدة", "فریدہ", None, "फ़रीदा", "فریده", "precious_unique", "Arabic", "Unisex", "ف ر د", "not established", "high", "Variant romanization of فريدة ('unique, precious'). The source record's gloss 'Precious, Unique' is a reasonable rendering."),
 'faridun': ('فريدون', 'فریدون', 'فریدون', 'फ़रीदून', 'فریدون', 'uncertain_form', 'Persian', 'Male', 'Old Iranian Thraitauna', 'not established', 'low', "Fereydūn/Farīdūn, from Old Iranian Thraitauna, a king in the Shahnameh. The source record's gloss 'Unique, Distinguished' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'farih': ('فارح', 'فارح', None, 'फ़ारिह', 'فارح', 'batch22_farih', 'Arabic', 'Male', 'ف ر ح', 'not established', 'high', "Fāriḥ ('joyful, glad'). The source record's gloss 'Victorious' is unsupported."),
 "fariha": ("فريحة", "فریحہ", None, "फ़रीहा", "فريحه", "joyful_happy", "Arabic", "Female", "ف ر ح", "not established", "high", "Farīḥa, diminutive of faraḥ ('joy'). The source record's gloss 'Joyful, Happy' is a reasonable rendering."),
 "farihah": ("فريحة", "فریحہ", None, "फ़रीहा", "فريحه", "joyful", "Arabic", "Female", "ف ر ح", "not established", "high", "Variant romanization of فريحة ('joyful'). The source record's gloss 'Joyful' is a reasonable rendering."),
 "farimah": ("فریمه", "فریمہ", "فریمه", "फ़रीमा", "فریمه", "exalted_noble_one", "Persian", "Female", "Persian far", "not established", "low", "The source record's gloss 'Exalted, Noble One' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "farin": ("فرين", "فرین", "فرین", "फ़रीन", "فرین", "little_fine", "Persian", "Unisex", "Persian far", "not established", "medium", "Persian farīn ('delicate, fine'). The source record's gloss 'Little, Fine' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 'farinaz': ('فريناز', 'فریناز', 'فریناز', 'फ़रीनाज़', 'فریناز', 'batch22_farinaz', 'Persian', 'Female', 'Persian far + nāz', 'not established', 'medium', "Persian Farīnāz, from far ('splendour') and nāz ('charm'). The source record's gloss 'Jewel, treasure' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'fariq': ('فارق', 'فارق', None, 'फ़ारिक़', 'فارق', 'batch22_fariq', 'Arabic', 'Male', 'ف ر ق', 'not established', 'high', "Fāriq ('one who distinguishes, separator'). The source record's gloss 'Wise Judge' is an approximation."),
 "faris": ("فارس", "فارس", None, "फ़ारिस", "فارس", "knight", "Arabic", "Male", "ف ر س", "not established", "high", "Fāris ('knight, horseman, cavalier'). The source record's gloss 'Knight' is a reasonable rendering. The source record classified it as Unknown, which is incorrect."),
 "farisha": ("فريشة", "فریشہ", None, "फ़रीशा", "فريشه", "light_bright_radiant", "Unknown", "Female", None, "not established", "low", "The source record's gloss 'Light, Bright, Radiant' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "farishta": ("فرشته", "فرشتہ", "فرشته", "फ़रिश्ता", "فرشته", "angel_messenger", "Persian", "Unisex", "Persian fereshte", "not established", "high", "Persian fereshte ('angel, messenger'). The source record's gloss 'Angel Messenger' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 "farivar": ("فريور", "فریور", "فریور", "फ़रीवर", "فریور", "luminous_radiant2", "Persian", "Unisex", "Persian far", "not established", "low", "The source record's gloss 'Luminous, radiant' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "fariya": ("فريعة", "فریعہ", None, "फ़रीया", "فريعه", "joyful2", "Unknown", "Female", None, "not established", "low", "The source record's gloss 'Joyful' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 'fariz': ('فريز', 'فریز', None, 'फ़रीज़', 'فريز', 'batch22_fariz', 'Arabic', 'Male', 'ف ر ز', 'not established', 'medium', "Farīz, related to farz ('duty, obligation'). The source record's gloss 'Free, independent' is unsupported."),
 'fariza': ('فريزة', 'فریزہ', None, 'फ़रीज़ा', 'فريزه', 'batch22_fariza', 'Arabic', 'Female', 'ف ر ز', 'not established', 'medium', "Farīza, related to farz ('duty'). The source record's gloss 'Jasmine or Fragrant' is unsupported."),
 'farizah': ('فريزة', 'فریزہ', None, 'फ़रीज़ा', 'فريزه', 'uncertain_form', 'Arabic', 'Female', 'ف ر ز', 'not established', 'low', "Variant romanization of فريزة. The source record's gloss 'Free, Independent' is unsupported."),
 'farjad': ('فرجاد', 'فرجاد', 'فرجاد', 'फ़रजाद', 'فرجاد', 'batch22_farjad', 'Persian', 'Male', 'Persian farjad', 'not established', 'medium', "Persian farjad ('earned, gained'; also 'wise'). The source record's gloss 'Wise, righteous' is an approximation. The source record classified it as Arabic, which is incorrect."),
 'farjam': ('فرجام', 'فرجام', 'فرجام', 'फ़रजाम', 'فرجام', 'batch22_farjam', 'Persian', 'Male', 'Persian farjām', 'not established', 'medium', "Persian farjām ('conclusion, end, outcome'). The source record's gloss 'Victorious, Triumphant' is unsupported. The source record classified it as Arabic, which is incorrect."),
 "farkhanda": ("فرخنده", "فرخندہ", "فرخنده", "फ़रख़ंदा", "فرخنده", "blessed_and_fortunate", "Persian", "Female", "Persian farkhonda", "not established", "high", "Persian farkhonda ('fortunate, blessed, auspicious'). The source record's gloss 'Blessed and fortunate' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 'farkhunda': ('فرخنده', 'فرخندہ', 'فرخنده', 'फ़रख़ुंदा', 'فرخنده', 'batch22_farkhunda', 'Persian', 'Unisex', 'Persian farkhonda', 'not established', 'high', "Variant romanization of فرخنده ('fortunate, blessed'). The source record's gloss 'Highly Praiseworthy' is unsupported. The source record classified it as Arabic, which is incorrect."),
 "farman": ("فرمان", "فرمان", "فرمان", "फ़रमान", "فرمان", "command_decree_edict", "Persian", "Male", "Persian farmān", "not established", "high", "Persian farmān ('command, decree, edict'). The source record's gloss 'Command, decree, edict' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 "farnad": ("فرناد", "فرناد", "فرناد", "फ़रनाद", "فرناد", "excellent_noble", "Persian", "Male", "Persian farnād", "not established", "low", "The source record's gloss 'Excellent, Noble' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "farnam": ("فرنام", "فرنام", "فرنام", "फ़रनाम", "فرنام", "road_travel", "Persian", "Unisex", "Persian farnām", "not established", "low", "The source record's gloss 'Road, Travel' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 'farnaz': ('فرناز', 'فرناز', 'فرناز', 'फ़रनाज़', 'فرناز', 'batch22_farnaz', 'Persian', 'Female', 'Persian farr + nāz', 'not established', 'high', "Persian Farnāz, from farr ('splendour') and nāz ('charm'). The source record's gloss 'Gentle, beautiful' is an approximation. The source record classified it as Arabic, which is incorrect."),
 "farniya": ("فرنیا", "فرنیا", "فرنیا", "फ़रनिया", "فرنیا", "gardener_of_the_garden", "Persian", "Female", "Persian far", "not established", "low", "The source record's gloss 'Gardener of the Garden' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "farnoud": ("فرنود", "فرنود", "فرنود", "फ़रनूद", "فرنود", "ruler_king", "Persian", "Male", "Persian farnūd", "not established", "low", "The source record's gloss 'Ruler, King' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 'farokh': ('فروخ', 'فروخ', 'فروخ', 'फ़रोख़', 'فروخ', 'batch22_farokh', 'Persian', 'Male', 'Persian farrokh', 'not established', 'high', "Persian farrokh ('happy, auspicious, fortunate'). The source record's gloss 'Lord, Master' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'farookh': ('فروخ', 'فروخ', 'فروخ', 'फ़रूख़', 'فروخ', 'batch22_farookh', 'Persian', 'Male', 'Persian farrokh', 'not established', 'high', "Variant romanization of Persian farrokh ('happy, auspicious'). The source record's gloss 'Liberator, Free from evil' is unsupported. The source record classified it as Arabic, which is incorrect."),
 "farooq": ("فاروق", "فاروق", None, "फ़ारूक़", "فاروق", "one_who_distinguishes", "Arabic", "Male", "ف ر ق", "not established", "high", "Fārūq ('one who distinguishes right from wrong'), the title of Caliph Umar. The source record's gloss 'One Who Distinguishes' is a reasonable rendering. The source record classified it as Unknown, which is incorrect."),
 'farouk': ('فاروق', 'فاروق', None, 'फ़ारूक', 'فاروق', 'batch22_farouk', 'Arabic', 'Male', 'ف ر ق', 'not established', 'high', "Variant romanization of فاروق ('one who distinguishes right from wrong'). The source record's gloss 'The owner of the great fortress' is unsupported."),
 "farouq": ("فاروق", "فاروق", None, "फ़ारूक़", "فاروق", "discriminator_between_truth_and_falsehood", "Arabic", "Male", "ف ر ق", "not established", "high", "Variant romanization of فاروق ('one who distinguishes right from wrong'). The source record's gloss is a reasonable rendering."),
 'farqad': ('فرقد', 'فرقد', None, 'फ़रक़द', 'فرقد', 'batch22_farqad', 'Arabic', 'Male', 'ف ر ق د', 'not established', 'medium', "Farqad ('calf'; also a star name). The source record's gloss 'Determined, Victorious' is unsupported."),
 'farraj': ('فراج', 'فراج', None, 'फ़र्राज', 'فراج', 'batch22_farraj', 'Arabic', 'Male', 'ف ر ج', 'not established', 'medium', "Farrāj ('one who relieves'; also a palm variety). The source record's gloss 'A type of palm tree' is an approximation."),
 "farran": ("فران", "فران", None, "फ़र्रान", "فران", "fragrant_delightful", "Arabic", "Male", "ف ر ن", "not established", "low", "The source record's gloss 'Fragrant, Delightful' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 'farras': ('فراس', 'فراس', None, 'फ़र्रास', 'فراس', 'batch22_farras', 'Arabic', 'Male', 'ف ر س', 'not established', 'medium', "Farrās, related to faras ('horse'). The source record's gloss 'Horses' is an approximation."),
 'farrokh': ('فرخ', 'فرخ', 'فرخ', 'फ़र्रोख़', 'فرخ', 'batch22_farrokh', 'Persian', 'Male', 'Persian farrokh', 'not established', 'high', "Persian farrokh ('happy, auspicious, fortunate'). The source record's gloss 'Bringer of Good Fortune' is an approximation. The source record classified it as Arabic, which is incorrect."),
 "farrukh": ("فرخ", "فرخ", "فرخ", "फ़र्रुख़", "فرخ", "happy_prosperous", "Persian", "Male", "Persian farrokh", "not established", "high", "Variant romanization of Persian farrokh ('happy, auspicious'). The source record's gloss 'Happy, Prosperous' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 "farsad": ("فرساد", "فرساد", "فرساد", "फ़रसाद", "فرساد", "brave_warrior", "Persian", "Male", "Persian farsād", "not established", "low", "The source record's gloss 'Brave warrior' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 'farsheed': ('فرشید', 'فرشید', 'فرشید', 'फ़रशीद', 'فرشید', 'batch22_farsheed', 'Persian', 'Male', 'Persian farr + shid', 'not established', 'high', "Persian Farshīd, from farr ('splendour') and shīd ('shine, light'). The source record's gloss 'Victorious one' is unsupported. The source record classified it as Arabic, which is incorrect."),
 "fartash": ("فرتاش", "فرتاش", "فرتاش", "फ़रताश", "فرتاش", "brave_victorious2", "Persian", "Male", "Persian fartāsh", "not established", "low", "The source record's gloss 'Brave, Victorious' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "faruq": ("فاروق", "فاروق", None, "फ़ारूक़", "فاروق", "one_who_distinguishes_between_truth_and_falsehood", "Arabic", "Male", "ف ر ق", "not established", "high", "Variant romanization of فاروق ('one who distinguishes right from wrong'). The source record's gloss is a reasonable rendering."),
 'farwa': ('فروة', 'فروہ', None, 'फ़रवा', 'فروه', 'batch22_farwa', 'Arabic', 'Female', 'ف ر و', 'not established', 'medium', "Farwa ('fur, pelt'). The source record's gloss 'Coldness of water' is unsupported."),
 "farya": ("فريا", "فریا", "فریا", "फ़रया", "فریا", "free_liberated", "Persian", "Female", "Persian farya", "not established", "low", "The source record's gloss 'Free, Liberated' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 "faryad": ("فریاد", "فریاد", "فریاد", "फ़रयाद", "فریاد", "cry_for_help", "Persian", "Unisex", "Persian faryād", "not established", "high", "Persian faryād ('cry, appeal, call for help'). The source record's gloss 'Cry for help' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 "faryal": ("فریال", "فریال", "فریال", "फ़रयाल", "فریال", "moon_light", "Persian", "Female", "Persian faryāl", "not established", "medium", "Persian faryāl, associated with moonlight. The source record's gloss 'Moon Light' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 "faryar": ("فریار", "فریار", "فریار", "फ़रयार", "فریار", "journey_adventure", "Persian", "Male", "Persian faryār", "not established", "low", "The source record's gloss 'Journey, adventure' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 'farzaana': ('فرزانة', 'فرزانہ', 'فرزانه', 'फ़रज़ाना', 'فرزانه', 'batch22_farzaana', 'Persian', 'Female', 'Persian farzāna', 'not established', 'high', "Persian farzāna ('wise, learned, intelligent'). The source record's gloss 'Adorned with precious gems' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'farzad': ('فرزاد', 'فرزاد', 'فرزاد', 'फ़रज़ाद', 'فرزاد', 'batch22_farzad', 'Persian', 'Male', 'Persian farzād', 'not established', 'high', "Persian farzād ('splendid birth'). The source record's gloss 'Strong, Ambitious, Valiant' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'farzam': ('فرزام', 'فرزام', 'فرزام', 'फ़रज़ाम', 'فرزام', 'batch22_farzam', 'Persian', 'Male', 'Persian farzām', 'not established', 'medium', "Persian farzām ('worthy, deserving'). The source record's gloss 'Exalted, Noble' is an approximation. The source record classified it as Arabic, which is incorrect."),
 'farzan': ('فرزان', 'فرزان', 'فرزان', 'फ़रज़ान', 'فرزان', 'batch22_farzan', 'Persian', 'Male', 'Persian farzān', 'not established', 'high', "Persian farzān ('wise, intelligent'). The source record's gloss 'Protector, Defender' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'farzana': ('فرزانة', 'فرزانہ', 'فرزانه', 'फ़रज़ाना', 'فرزانه', 'batch22_farzana', 'Persian', 'Female', 'Persian farzāna', 'not established', 'high', "Persian farzāna ('wise, learned, intelligent'). The source record's gloss 'One who Performs Obligations' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'farzanah': ('فرزانة', 'فرزانہ', 'فرزانه', 'फ़रज़ाना', 'فرزانه', 'batch22_farzanah', 'Persian', 'Female', 'Persian farzāna', 'not established', 'high', "Variant romanization of Persian farzāna ('wise, learned'). The source record's gloss 'Gardener' is unsupported. The source record classified it as Arabic, which is incorrect."),
 'farzand': ('فرزند', 'فرزند', 'فرزند', 'फ़रज़ंद', 'فرزند', 'batch22_farzand', 'Persian', 'Male', 'Persian farzand', 'not established', 'high', "Persian farzand ('child, offspring, son'). The source record's gloss 'Prince, Heir' is an approximation. The source record classified it as Arabic, which is incorrect."),
 'farzaneh': ('فرزانه', 'فرزانہ', 'فرزانه', 'फ़रज़ानेह', 'فرزانه', 'batch22_farzaneh', 'Persian', 'Female', 'Persian farzāna', 'not established', 'high', "Variant romanization of Persian farzāna ('wise, learned, intelligent'). The source record's gloss 'Exalted, Noble' is unsupported. The source record classified it as Arabic, which is incorrect."),
 "farzeen": ("فرزين", "فرزین", "فرزین", "फ़रज़ीन", "فرزین", "wise_intelligent_knowledgeable", "Persian", "Unisex", "Persian farzīn", "not established", "high", "Persian farzīn ('wise, learned'). The source record's gloss 'Wise, Intelligent, Knowledgeable' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 'farzeena': ('فرزينة', 'فرزینہ', 'فرزینه', 'फ़रज़ीना', 'فرزینه', 'batch22_farzeena', 'Persian', 'Female', 'Persian farzīn', 'not established', 'medium', "Persian farzīna, related to farzīn ('wise'). The source record's gloss 'Lady of Paradise' is unsupported. The source record classified it as Arabic, which is incorrect."),
 "farzin": ("فرزين", "فرزین", "فرزین", "फ़रज़ीन", "فرزین", "wise_intelligent_bright", "Persian", "Male", "Persian farzīn", "not established", "high", "Persian farzīn ('wise, learned'). The source record's gloss 'Wise, Intelligent, Bright' is a reasonable rendering. The source record classified it as Arabic, which is incorrect."),
 'faseeh': ('فصيح', 'فصیح', None, 'फ़सीह', 'فصيح', 'batch22_faseeh', 'Arabic', 'Male', 'ف ص ح', 'not established', 'high', "Faṣīḥ ('eloquent, articulate'). The source record's gloss 'Intelligent, Wise, Knowledgeable' is an approximation."),
 'faseeha': ('فصيحة', 'فصیحہ', None, 'फ़सीहा', 'فصيحه', 'batch22_faseeha', 'Arabic', 'Female', 'ف ص ح', 'not established', 'high', "Faṣīḥa ('eloquent, articulate'). The source record's gloss 'Healer, Helper' is unsupported."),
 'fasih': ('فصيح', 'فصیح', None, 'फ़सीह', 'فصيح', 'batch22_fasih', 'Arabic', 'Male', 'ف ص ح', 'not established', 'high', "Variant romanization of فصيح ('eloquent, articulate'). The source record's gloss 'Wise, Knowledgeable' is an approximation."),
 'fasiha': ('فصيحة', 'فصیحہ', None, 'फ़सीहा', 'فصيحه', 'batch22_fasiha', 'Arabic', 'Female', 'ف ص ح', 'not established', 'high', "Variant romanization of فصيحة ('eloquent'). The source record's gloss 'Wise, Intelligent' is an approximation."),
 "fasiya": ("فاصية", "فاسیہ", None, "फ़ासिया", "فاسيه", "healer", "Unknown", "Female", None, "not established", "low", "The source record's gloss 'Healer' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
 'fatan': ('فتان', 'فتان', None, 'फ़तान', 'فتان', 'batch22_fatan', 'Arabic', 'Female', 'ف ت ن', 'not established', 'medium', "Fattān ('charming, alluring'). The source record's gloss 'Slender, Agile' is unsupported."),
 'fatanah': ('فتانة', 'فتانہ', None, 'फ़ताना', 'فتانه', 'batch22_fatanah', 'Arabic', 'Female', 'ف ت ن', 'not established', 'medium', "Fattāna ('charming, alluring'). The source record's gloss 'Conquering' is unsupported."),
 "fatat": ("فتاة", "فتات", None, "फ़तात", "فتات", "little_one_young_girl", "Arabic", "Female", "ف ت ي", "not established", "high", "Fatāt ('young girl, maiden'). The source record's gloss 'Little one, Young girl' is a reasonable rendering."),
 "fateem": ("فاتم", "فاتم", None, "फ़ातीम", "فاتم", "successor_opener", "Unknown", "Female", None, "not established", "low", "The source record's gloss 'Successor, Opener' could not be matched to a Tier-A/B lexical source. The identification is uncertain."),
}
