# -*- coding: utf-8 -*-
"""Curated HIGH specs for one-by-one HIGH upgrades, batches #2-#10.

v8.1 covers the batch #1-#2 entries (tracker rows #1-#20); v8.2 covers the
batch #3+ entries appended below (tracker rows #21 onward).

SAFETY RULE: Arabic-script content is composed programmatically from each
record's own bytes (lexical_form, root letters) wherever possible. Short
literal strings (roots, surgery words, Persian glosses) are guarded by
assertions in the engine (upgrade_one_high._patch_spec) and reviewed via
repr dumps before commit.

kinds: fem_participle | masc_participle | fem_plural | fem_adj | noun
surgery opcodes:
  ('suf', lang, old, suffix)  -> replace old with old+suffix in meaning+long
  ('set', lang, old, new)     -> replace old with new in meaning+long
  ('ur_ta_fem', lang, old)    -> تا -> ت+Urdu-yeh (U+06CC from own template)
  ('ps_yeh_fem', lang, old)   -> final char -> donor feminine ې (U+06D0)
"""

SPECS = {
    "aaminaat": {
        "kind": "fem_plural",
        "gloss": "Trustworthy, faithful, honest",
        "root": "أ م ن",
        "root_tr": "ʾ-m-n",
        "vow": ["F", "K", None, "F", None, None],
        "voc_tr": "ʾamīnāt",
        "verb_mid": "i",
        "verb_tr": "ʾamina",
        "fem_tr": "ʾamīnah",
        "masc_tr": "ʾamīn",
        "masc_gloss": "'trustworthy, faithful'",
        "variant": None,
        "usage": "The plural is used as a given name in some South Asian communities.",
        "fa_from": "urdu",
        "fa_meaning": "امین، قابل اعتماد، وفادار",
        "surgeries": [
            ("suf", "arabic", "أمين", "ات"),
            ("suf", "arabic", "موثوق", "ات"),
            ("suf", "arabic", "مخلص", "ات"),
        ],
    },
    "aamirat": {
        "kind": "fem_plural",
        "gloss": "Inhabited, flourishing, prosperous",
        "root": "ع م ر",
        "root_tr": "ʿ-m-r",
        "vow": ["F", None, "K", "F", None, None],
        "voc_tr": "ʿāmirāt",
        "verb_mid": "a",
        "verb_tr": "ʿamara",
        "fem_tr": "ʿāmirah",
        "masc_tr": "ʿāmir",
        "masc_gloss": "'flourishing, inhabited'",
        "variant": None,
        "usage": None,
        "fa_from": "urdu",
        "fa_meaning": "آباد، شکوفا، پررونق",
        "surgeries": [
            ("suf", "arabic", "عامر", "ات"),
            ("suf", "arabic", "مأهول", "ات"),
            ("suf", "arabic", "مزدهر", "ات"),
            ("ur_ta_fem", "urdu", "پھلتا پھولتا"),
            ("set", "hindi", "फलता-फूलता", "फलती-फूलती"),
            ("ps_yeh_fem", "pashto", "پرمختللی"),
        ],
    },
    "aamrah": {
        "kind": "fem_participle",
        "gloss": "Inhabited, flourishing, prosperous",
        "root": "ع م ر",
        "root_tr": "ʿ-m-r",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāmirah",
        "verb_mid": "a",
        "verb_tr": "ʿamara",
        "verb_gloss_short": "'to inhabit, to build'",
        "masc_tr": "ʿāmir",
        "variant": "Aamrah is a variant romanization of Aamira/Aamirah.",
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "آباد، شکوفا، پررونق",
        "surgeries": [
            ("suf", "arabic", "عامر", "ة"),
            ("suf", "arabic", "مأهول", "ة"),
            ("suf", "arabic", "مزدهر", "ة"),
            ("ur_ta_fem", "urdu", "پھلتا پھولتا"),
            ("set", "hindi", "फलता-फूलता", "फलती-फूलती"),
            ("ps_yeh_fem", "pashto", "پرمختللی"),
        ],
    },
    "aanisa": {
        "kind": "fem_adj",
        "gloss": "Friendly, sociable, companionable",
        "root": "أ ن س",
        "root_tr": "ʾ-n-s",
        "vow": ["F", "K", None, "F", None],
        "voc_tr": "ʾanīsah",
        "verb_mid": "i",
        "verb_tr": "ʾanisa",
        "masc_tr": "ʾanīs",
        "masc_gloss": "'friendly, sociable'",
        "variant": None,
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "مهربان، اجتماعی، مونس",
        "surgeries": [
            ("suf", "arabic", "أنيس", "ة"),
            ("suf", "arabic", "ودود", "ة"),
            ("suf", "arabic", "مؤنس", "ة"),
            ("ps_yeh_fem", "pashto", "ملګری"),
        ],
    },
    "aanisah": {
        "kind": "fem_adj",
        "gloss": "Friendly, sociable, companionable",
        "root": "أ ن س",
        "root_tr": "ʾ-n-s",
        "vow": ["F", "K", None, "F", None],
        "voc_tr": "ʾanīsah",
        "verb_mid": "i",
        "verb_tr": "ʾanisa",
        "masc_tr": "ʾanīs",
        "masc_gloss": "'friendly, sociable'",
        "variant": "Aanisah is a variant romanization of Aanisa.",
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "مهربان، اجتماعی، مونس",
        "surgeries": [
            ("suf", "arabic", "أنيس", "ة"),
            ("suf", "arabic", "ودود", "ة"),
            ("suf", "arabic", "مؤنس", "ة"),
            ("ps_yeh_fem", "pashto", "ملګری"),
        ],
    },
    "aaqib": {
        "kind": "masc_participle",
        "gloss": "Successor, follower, one who comes after",
        "root": "ع ق ب",
        "root_tr": "ʿ-q-b",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāqib",
        "verb_mid": "a",
        "verb_tr": "ʿaqaba",
        "verb_gloss_short": "'to follow, to succeed'",
        "variant": None,
        "usage": None,
        "fa_from": "urdu",
        "fa_meaning": "جانشین، پیرو، تالی",
        "surgeries": [],
    },
    "aaqiba": {
        "kind": "noun",
        "gloss": "Consequence, outcome, end result",
        "root": "ع ق ب",
        "root_tr": "ʿ-q-b",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāqibah",
        "verb_mid": None,
        "verb_tr": None,
        "variant": None,
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "پیامد، نتیجه، فرجام",
        "surgeries": [],
    },
    "aaqibah": {
        "kind": "noun",
        "gloss": "Consequence, outcome, result",
        "root": "ع ق ب",
        "root_tr": "ʿ-q-b",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāqibah",
        "verb_mid": None,
        "verb_tr": None,
        "variant": "Aaqibah is a variant romanization of Aaqiba.",
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "پیامد، نتیجه، فرجام",
        "surgeries": [],
    },
    "aaqif": {
        "kind": "masc_participle",
        "gloss": "Devoted, steadfast, staying",
        "root": "ع ك ف",
        "root_tr": "ʿ-k-f",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿākif",
        "verb_mid": "a",
        "verb_tr": "ʿakafa",
        "verb_gloss_short": "'to stay, to devote oneself'",
        "variant": None,
        "usage": None,
        "fa_from": "urdu",
        "fa_meaning": "پایبند، ثابت‌قدم، مقیم",
        "surgeries": [],
    },
    # ---------------- batch 2 (#11-#20) ----------------
    "aaraf": {
        "kind": "noun",
        "gloss": "Elevated place, crest",
        "root": "ع ر ف",
        "root_tr": "ʿ-r-f",
        "vow": ["F", "S", "F", None, None],
        "voc_tr": "ʾaʿrāf",
        "verb_mid": None,
        "verb_tr": None,
        "variant": None,
        "usage": "Its use as a personal name is reported but not verified.",
        "morph_t": "Broken plural (afʿāl pattern) of عُرْف ('crest, elevated place'), from the root {root}.",
        "body_t": "{name} is Arabic {voc} ({voc_tr}) '{short}', the broken plural of عُرْف (ʿurf, 'crest, ridge, elevated place') from the root {root} ({root_tr}); {lex} is also the title of sūra 7 (al-Aʿrāf).{tail}",
        "etym_t": "The form {lex} is an established Arabic lexical item — the broken plural of عرف — and {name} is the word itself used as a personal name rather than a derived or diminutive form.",
        "apposition": "broken plural of عرف",
        "fa_from": "urdu",
        "fa_meaning": "بلندی، تیغ، قله",
        "surgeries": [],
    },
    "aarefa": {
        "kind": "fem_participle",
        "gloss": "Knowing, aware, learned",
        "root": "ع ر ف",
        "root_tr": "ʿ-r-f",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿārifah",
        "verb_mid": "a",
        "verb_tr": "ʿarafa",
        "verb_gloss_short": "'to know, to recognize'",
        "masc_tr": "ʿārif",
        "variant": None,
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "دانا، آگاه، دانشمند",
        "surgeries": [
            ("set", "urdu", "جاننے والا", "جاننے والی"),
            ("set", "hindi", "विद्वान", "विदुषी"),
            ("suf", "pashto", "عالم", "ه"),
            ("suf", "arabic", "عارف", "ة"),
            ("suf", "arabic", "عليم", "ة"),
            ("suf", "arabic", "خبير", "ة"),
        ],
    },
    "aarifin": {
        "kind": "noun",
        "gloss": "Knowing, aware, learned",
        "root": "ع ر ف",
        "root_tr": "ʿ-r-f",
        "vow": ["F", None, "K", "K", None, None],
        "voc_tr": "ʿārifīn",
        "verb_mid": None,
        "verb_tr": None,
        "variant": None,
        "usage": "The plural is used as a given name in some South Asian communities.",
        "morph_t": "Sound masculine plural (oblique -īn ending, nominative -ūn) of عارف, built on the root {root}.",
        "body_t": "{name} is Arabic {voc} ({voc_tr}) '{short}', the sound masculine plural of عَارِف (ʿārif, 'knowing, learned') from the root {root} ({root_tr}).{tail}",
        "etym_t": "The form {lex} is an established Arabic lexical item — the sound masculine plural of عارف — and {name} is the word itself used as a personal name rather than a derived or diminutive form.",
        "apposition": "sound masculine plural of عارف",
        "fa_from": "urdu",
        "fa_meaning": "دانا، آگاه، دانشمند",
        "surgeries": [
            ("suf", "arabic", "عارف", "ون"),
            ("suf", "arabic", "عليم", "ون"),
            ("suf", "arabic", "خبير", "ون"),
        ],
    },
    "aasal": {
        "kind": "noun",
        "gloss": "Honey",
        "root": "ع س ل",
        "root_tr": "ʿ-s-l",
        "vow": ["F", "F", None],
        "voc_tr": "ʿasal",
        "verb_mid": None,
        "verb_tr": None,
        "variant": None,
        "usage": "Its use as a personal name is reported but requires separate frequency evidence.",
        "morph_t": "Simple lexical noun from the root {root}.",
        "body_t": "{name} is Arabic {voc} ({voc_tr}) '{short}', the established word for honey, from the root {root} ({root_tr}).{tail}",
        "etym_t": "The form {lex} is an established Arabic lexical item — the word for 'honey' — and {name} is the word itself used as a personal name rather than a derived form.",
        "apposition": "established word for 'honey'",
        "fa_from": "urdu",
        "fa_meaning": "عسل، انگبین",
        "surgeries": [],
    },
    "aasfa": {
        "kind": "noun",
        "gloss": "Storm, tempest",
        "root": "ع ص ف",
        "root_tr": "ʿ-ṣ-f",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāṣifah",
        "verb_mid": "a",
        "verb_tr": "ʿaṣafa",
        "variant": None,
        "usage": None,
        "morph_t": "Established noun (also the feminine of the active participle {base}) from the root {root}.",
        "body_t": "{name} is Arabic {voc} ({voc_tr}) '{short}', the established word for a storm, from the root {root} ({root_tr}); it is also the feminine of the active participle عَاصِف (ʿāṣif, 'stormy') of {verb} ({verb_tr}, 'to storm, to rage').{tail}",
        "etym_t": "The form {lex} is an established Arabic lexical item — the storm-word of the root {root} — and {name} is the word itself used as a personal name rather than a derived or diminutive form.",
        "apposition": "established storm-word",
        "fa_from": "pashto",
        "fa_meaning": "توفان، تندباد",
        "surgeries": [],
    },
    "aashik": {
        "kind": "masc_participle",
        "gloss": "Lover, one passionately devoted",
        "root": "ع ش ق",
        "root_tr": "ʿ-sh-q",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāshiq",
        "verb_mid": "i",
        "verb_tr": "ʿashiqa",
        "verb_gloss_short": "'to love passionately'",
        "variant": None,
        "usage": "Widely used in Urdu and Persian literary culture.",
        "fa_from": "urdu",
        "fa_meaning": "عاشق، شیفته، دلداده",
        "surgeries": [],
    },
    "aashiq": {
        "kind": "masc_participle",
        "gloss": "Lover, devoted admirer, passionate one",
        "root": "ع ش ق",
        "root_tr": "ʿ-sh-q",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāshiq",
        "verb_mid": "i",
        "verb_tr": "ʿashiqa",
        "verb_gloss_short": "'to love passionately'",
        "variant": "Aashiq is a variant romanization of Aashik.",
        "usage": None,
        "fa_from": "urdu",
        "fa_meaning": "عاشق، شیفته، دلداده",
        "surgeries": [],
    },
    "aashir": {
        "kind": "noun",
        "gloss": "One who associates with",
        "root": "ع ش ر",
        "root_tr": "ʿ-sh-r",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāshir",
        "verb_mid": "a",
        "verb_tr": "ʿashara",
        "variant": None,
        "usage": None,
        "morph_t": "Active participle (fāʿil pattern) of {verb}, built on the root {root}; also the ordinal 'tenth'.",
        "body_t": "{name} is Arabic {voc} ({voc_tr}) '{short}', the active participle of {verb} ({verb_tr}, 'to take a tenth') from the root {root} ({root_tr}); {lex} doubles as the ordinal 'tenth', and the naming gloss 'one who associates with' reflects the root's companionship cluster.{tail}",
        "etym_t": "The form {lex} is an established Arabic lexical item — the active participle of {root_compact} — and {name} is the word itself used as a personal name rather than a derived or diminutive form.",
        "apposition": "active participle of {verb}",
        "fa_from": "urdu",
        "fa_meaning": "همراه، همنشین، مصاحب",
        "surgeries": [],
    },
    "aasif": {
        "kind": "masc_participle",
        "gloss": "Stormy, tempestuous",
        "root": "ع ص ف",
        "root_tr": "ʿ-ṣ-f",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāṣif",
        "verb_mid": "a",
        "verb_tr": "ʿaṣafa",
        "verb_gloss_short": "'to storm, to rage'",
        "variant": None,
        "usage": None,
        "fa_from": "urdu",
        "fa_meaning": "توفانی، توفنده",
        "surgeries": [],
    },
    "aasifah": {
        "kind": "noun",
        "gloss": "Storm, tempest, strong wind",
        "root": "ع ص ف",
        "root_tr": "ʿ-ṣ-f",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāṣifah",
        "verb_mid": "a",
        "verb_tr": "ʿaṣafa",
        "variant": "Aasifah is a variant romanization of Aasfa.",
        "usage": None,
        "morph_t": "Established noun (also the feminine of the active participle {base}) from the root {root}.",
        "body_t": "{name} is Arabic {voc} ({voc_tr}) '{short}', the established word for a storm, from the root {root} ({root_tr}); it is also the feminine of the active participle عَاصِف (ʿāṣif, 'stormy') of {verb} ({verb_tr}, 'to storm, to rage').{tail}",
        "etym_t": "The form {lex} is an established Arabic lexical item — the storm-word of the root {root} — and {name} is the word itself used as a personal name rather than a derived or diminutive form.",
        "apposition": "established storm-word",
        "fa_from": "pashto",
        "fa_meaning": "توفان، تندباد",
        "surgeries": [],
    },

    # ------------------------------------------------------------------
    # Batch #3 (tracker rows #21-#30) - content_revision v8.2
    # ------------------------------------------------------------------
    "aasim": {
        "kind": "masc_participle",
        "gloss": "Protector, guardian, keeper",
        "root": "ع ص م",
        "root_tr": "ʿ-ṣ-m",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāṣim",
        "verb_mid": "a",
        "verb_tr": "ʿaṣama",
        "verb_gloss_short": "'to protect, to preserve'",
        "variant": None,
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "محافظ، نگهبان، حامی",
        "surgeries": [],
    },
    "aasimah": {
        "kind": "fem_participle",
        "gloss": "Protector, guardian, keeper",
        "root": "ع ص م",
        "root_tr": "ʿ-ṣ-m",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāṣimah",
        "verb_mid": "a",
        "verb_tr": "ʿaṣama",
        "verb_gloss_short": "'to protect, to preserve'",
        "masc_tr": "ʿāṣim",
        "variant": "Aasimah is a variant romanization of Aasima.",
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "محافظ، نگهبان، حامی",
        "surgeries": [
            ("suf", "arabic", "حافظ", "ة"),
            ("suf", "arabic", "حامي", "ة"),
            ("set", "hindi", "हिफ़ाज़त करने वाला", "हिफ़ाज़त करने वाली"),
            ("ps_yeh_fem", "pashto", "ساتونکی"),
            ("ps_yeh_fem", "pashto", "ملاتړی"),
        ],
    },
    "aasimat": {
        "kind": "fem_plural",
        "gloss": "Protector, guardian, keeper",
        "root": "ع ص م",
        "root_tr": "ʿ-ṣ-m",
        "vow": ["F", None, "K", "F", None, None],
        "voc_tr": "ʿāṣimāt",
        "verb_mid": None,
        "verb_tr": None,
        "fem_tr": "ʿāṣimah",
        "masc_tr": "ʿāṣim",
        "masc_gloss": "'protector, guardian'",
        "variant": None,
        "usage": "The plural form is used as a given name in some South Asian communities.",
        "fa_from": "arabic",
        "fa_meaning": "محافظان، نگهبانان، حامیان",
        "surgeries": [
            ("suf", "arabic", "حافظ", "ات"),
            ("suf", "arabic", "حامي", "ات"),
            ("set", "hindi", "हिफ़ाज़त करने वाला", "हिफ़ाज़त करने वाली"),
            ("ps_yeh_fem", "pashto", "ساتونکی"),
            ("ps_yeh_fem", "pashto", "ملاتړی"),
        ],
    },
    "aateqa": {
        "kind": "fem_participle",
        "gloss": "Free, liberated",
        "root": "ع ت ق",
        "root_tr": "ʿ-t-q",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿātiqah",
        "verb_mid": "a",
        "verb_tr": "ʿataqa",
        "verb_gloss_short": "'to be free, to be freed'",
        "masc_tr": "ʿātiq",
        "variant": "Aateqa is a variant romanization of Atika.",
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "آزاد، رها، مستقل",
        "surgeries": [
            ("suf", "arabic", "حر", "ة"),
            ("suf", "arabic", "طليق", "ة"),
            ("suf", "arabic", "مستقل", "ة"),
        ],
    },
    "aatir": {
        "kind": "masc_participle",
        "gloss": "Fragrant, perfumed",
        "root": "ع ط ر",
        "root_tr": "ʿ-ṭ-r",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāṭir",
        "verb_mid": "i",
        "verb_tr": "ʿaṭira",
        "verb_gloss_short": "'to be fragrant, to be perfumed'",
        "variant": None,
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "خوشبودار، معطر، عطرآگین",
        "surgeries": [],
    },
    "aatira": {
        "kind": "fem_participle",
        "gloss": "Fragrant, perfumed, scented",
        "root": "ع ط ر",
        "root_tr": "ʿ-ṭ-r",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāṭirah",
        "verb_mid": "i",
        "verb_tr": "ʿaṭira",
        "verb_gloss_short": "'to be fragrant, to be perfumed'",
        "masc_tr": "ʿāṭir",
        "variant": "Aatira is a variant romanization of Aatirah.",
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "خوشبودار، معطر، عطرآگین",
        "surgeries": [
            ("suf", "arabic", "عاطر", "ة"),
        ],
    },
    "aatirah": {
        "kind": "fem_participle",
        "gloss": "Fragrant, perfumed, scented",
        "root": "ع ط ر",
        "root_tr": "ʿ-ṭ-r",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāṭirah",
        "verb_mid": "i",
        "verb_tr": "ʿaṭira",
        "verb_gloss_short": "'to be fragrant, to be perfumed'",
        "masc_tr": "ʿāṭir",
        "variant": None,
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "خوشبودار، معطر، عطرآگین",
        "surgeries": [
            ("suf", "arabic", "عاطر", "ة"),
        ],
    },
    "abid": {
        "kind": "masc_participle",
        "gloss": "Worshipper, devout servant",
        "root": "ع ب د",
        "root_tr": "ʿ-b-d",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿābid",
        "verb_mid": "a",
        "verb_tr": "ʿabada",
        "verb_gloss_short": "'to worship, to serve'",
        "variant": None,
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "عبادت کننده، پرستنده، بنده",
        "surgeries": [],
    },
    "abidah": {
        "kind": "fem_participle",
        "gloss": "Worshipper of God",
        "root": "ع ب د",
        "root_tr": "ʿ-b-d",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿābidah",
        "verb_mid": "a",
        "verb_tr": "ʿabada",
        "verb_gloss_short": "'to worship, to serve'",
        "masc_tr": "ʿābid",
        "variant": None,
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "عبادت کننده، بنده، پرستنده",
        "surgeries": [
            ("set", "urdu", "خدا کا عابد", "خدا کی عابدہ"),
            ("set", "hindi", "ईश्वर का उपासक", "ईश्वर की उपासिका"),
            ("ps_yeh_fem", "pashto", "د خدای عبادت کوونکی"),
        ],
    },
    "abidat": {
        "kind": "fem_plural",
        "gloss": "Servants, worshippers (of God)",
        "root": "ع ب د",
        "root_tr": "ʿ-b-d",
        "vow": ["F", None, "K", "F", None, None],
        "voc_tr": "ʿābidāt",
        "verb_mid": None,
        "verb_tr": None,
        "fem_tr": "ʿābidah",
        "masc_tr": "ʿābid",
        "masc_gloss": "'worshipper, devout servant'",
        "variant": None,
        "usage": "The plural form is used as a given name in some South Asian communities.",
        "fa_from": "arabic",
        "fa_meaning": "بندگان، عبادت کنندگان، پرستندگان",
        "surgeries": [
            ("set", "urdu", "عبادت کرنے والے", "عبادت کرنے والیاں"),
            ("set", "hindi", "दास", "दासियाँ"),
            ("set", "pashto", "عبادت کوونکي", "عبادت کوونکې"),
        ],
    },
}
