# -*- coding: utf-8 -*-
"""Curated HIGH specs for one-by-one v8.1 upgrades, batch #2-#10.

SAFETY RULE: Arabic-script content is composed programmatically from each
record's own bytes (lexical_form, root letters) wherever possible. Short
literal strings (roots, surgery words, Persian glosses) are guarded by
assertions in the engine (upgrade_one_high._patch_spec) and reviewed via
repr dumps before commit.

kinds: fem_participle | masc_participle | fem_plural | fem_adj | noun
surgery opcodes:
  ('suf', lang, old, suffix)  -> replace old with old+suffix in meaning+long
  ('set', lang, old, new)     -> replace old with new in meaning+long
  ('ur_ta_fem', lang, old)    -> تا -> ت+Urdu-yeh (U+06CC from own template)
  ('ps_yeh_fem', lang, old)   -> final char -> donor feminine ې (U+06D0)
"""

SPECS = {
    "aaminaat": {
        "kind": "fem_plural",
        "gloss": "Trustworthy, faithful, honest",
        "root": "أ م ن",
        "root_tr": "ʾ-m-n",
        "vow": ["F", "K", None, "F", None, None],
        "voc_tr": "ʾamīnāt",
        "verb_mid": "i",
        "verb_tr": "ʾamina",
        "fem_tr": "ʾamīnah",
        "masc_tr": "ʾamīn",
        "masc_gloss": "'trustworthy, faithful'",
        "variant": None,
        "usage": "The plural is used as a given name in some South Asian communities.",
        "fa_from": "urdu",
        "fa_meaning": "امین، قابل اعتماد، وفادار",
        "surgeries": [
            ("suf", "arabic", "أمين", "ات"),
            ("suf", "arabic", "موثوق", "ات"),
            ("suf", "arabic", "مخلص", "ات"),
        ],
    },
    "aamirat": {
        "kind": "fem_plural",
        "gloss": "Inhabited, flourishing, prosperous",
        "root": "ع م ر",
        "root_tr": "ʿ-m-r",
        "vow": ["F", None, "K", "F", None, None],
        "voc_tr": "ʿāmirāt",
        "verb_mid": "a",
        "verb_tr": "ʿamara",
        "fem_tr": "ʿāmirah",
        "masc_tr": "ʿāmir",
        "masc_gloss": "'flourishing, inhabited'",
        "variant": None,
        "usage": None,
        "fa_from": "urdu",
        "fa_meaning": "آباد، شکوفا، پررونق",
        "surgeries": [
            ("suf", "arabic", "عامر", "ات"),
            ("suf", "arabic", "مأهول", "ات"),
            ("suf", "arabic", "مزدهر", "ات"),
            ("ur_ta_fem", "urdu", "پھلتا پھولتا"),
            ("set", "hindi", "फलता-फूलता", "फलती-फूलती"),
            ("ps_yeh_fem", "pashto", "پرمختللی"),
        ],
    },
    "aamrah": {
        "kind": "fem_participle",
        "gloss": "Inhabited, flourishing, prosperous",
        "root": "ع م ر",
        "root_tr": "ʿ-m-r",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāmirah",
        "verb_mid": "a",
        "verb_tr": "ʿamara",
        "verb_gloss_short": "'to inhabit, to build'",
        "masc_tr": "ʿāmir",
        "variant": "Aamrah is a variant romanization of Aamira/Aamirah.",
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "آباد، شکوفا، پررونق",
        "surgeries": [
            ("suf", "arabic", "عامر", "ة"),
            ("suf", "arabic", "مأهول", "ة"),
            ("suf", "arabic", "مزدهر", "ة"),
            ("ur_ta_fem", "urdu", "پھلتا پھولتا"),
            ("set", "hindi", "फलता-फूलता", "फलती-फूलती"),
            ("ps_yeh_fem", "pashto", "پرمختللی"),
        ],
    },
    "aanisa": {
        "kind": "fem_adj",
        "gloss": "Friendly, sociable, companionable",
        "root": "أ ن س",
        "root_tr": "ʾ-n-s",
        "vow": ["F", "K", None, "F", None],
        "voc_tr": "ʾanīsah",
        "verb_mid": "i",
        "verb_tr": "ʾanisa",
        "masc_tr": "ʾanīs",
        "masc_gloss": "'friendly, sociable'",
        "variant": None,
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "مهربان، اجتماعی، مونس",
        "surgeries": [
            ("suf", "arabic", "أنيس", "ة"),
            ("suf", "arabic", "ودود", "ة"),
            ("suf", "arabic", "مؤنس", "ة"),
            ("ps_yeh_fem", "pashto", "ملګری"),
        ],
    },
    "aanisah": {
        "kind": "fem_adj",
        "gloss": "Friendly, sociable, companionable",
        "root": "أ ن س",
        "root_tr": "ʾ-n-s",
        "vow": ["F", "K", None, "F", None],
        "voc_tr": "ʾanīsah",
        "verb_mid": "i",
        "verb_tr": "ʾanisa",
        "masc_tr": "ʾanīs",
        "masc_gloss": "'friendly, sociable'",
        "variant": "Aanisah is a variant romanization of Aanisa.",
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "مهربان، اجتماعی، مونس",
        "surgeries": [
            ("suf", "arabic", "أنيس", "ة"),
            ("suf", "arabic", "ودود", "ة"),
            ("suf", "arabic", "مؤنس", "ة"),
            ("ps_yeh_fem", "pashto", "ملګری"),
        ],
    },
    "aaqib": {
        "kind": "masc_participle",
        "gloss": "Successor, follower, one who comes after",
        "root": "ع ق ب",
        "root_tr": "ʿ-q-b",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāqib",
        "verb_mid": "a",
        "verb_tr": "ʿaqaba",
        "verb_gloss_short": "'to follow, to succeed'",
        "variant": None,
        "usage": None,
        "fa_from": "urdu",
        "fa_meaning": "جانشین، پیرو، تالی",
        "surgeries": [],
    },
    "aaqiba": {
        "kind": "noun",
        "gloss": "Consequence, outcome, end result",
        "root": "ع ق ب",
        "root_tr": "ʿ-q-b",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāqibah",
        "verb_mid": None,
        "verb_tr": None,
        "variant": None,
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "پیامد، نتیجه، فرجام",
        "surgeries": [],
    },
    "aaqibah": {
        "kind": "noun",
        "gloss": "Consequence, outcome, result",
        "root": "ع ق ب",
        "root_tr": "ʿ-q-b",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāqibah",
        "verb_mid": None,
        "verb_tr": None,
        "variant": "Aaqibah is a variant romanization of Aaqiba.",
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "پیامد، نتیجه، فرجام",
        "surgeries": [],
    },
    "aaqif": {
        "kind": "masc_participle",
        "gloss": "Devoted, steadfast, staying",
        "root": "ع ك ف",
        "root_tr": "ʿ-k-f",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿākif",
        "verb_mid": "a",
        "verb_tr": "ʿakafa",
        "verb_gloss_short": "'to stay, to devote oneself'",
        "variant": None,
        "usage": None,
        "fa_from": "urdu",
        "fa_meaning": "پایبند، ثابت‌قدم، مقیم",
        "surgeries": [],
    },
}
