# -*- coding: utf-8 -*-
"""Curated HIGH specs for one-by-one HIGH upgrades, batches #2-#10.

v8.1 covers the batch #1-#2 entries (tracker rows #1-#20); v8.2 covers the
batch #3+ entries appended below (tracker rows #21 onward).

SAFETY RULE: Arabic-script content is composed programmatically from each
record's own bytes (lexical_form, root letters) wherever possible. Short
literal strings (roots, surgery words, Persian glosses) are guarded by
assertions in the engine (upgrade_one_high._patch_spec) and reviewed via
repr dumps before commit.

kinds: fem_participle | masc_participle | fem_plural | fem_adj | noun
surgery opcodes:
  ('suf', lang, old, suffix)  -> replace old with old+suffix in meaning+long
  ('set', lang, old, new)     -> replace old with new in meaning+long
  ('ur_ta_fem', lang, old)    -> تا -> ت+Urdu-yeh (U+06CC from own template)
  ('ps_yeh_fem', lang, old)   -> final char -> donor feminine ې (U+06D0)
"""

SPECS = {
    "aaminaat": {
        "kind": "fem_plural",
        "gloss": "Trustworthy, faithful, honest",
        "root": "أ م ن",
        "root_tr": "ʾ-m-n",
        "vow": ["F", "K", None, "F", None, None],
        "voc_tr": "ʾamīnāt",
        "verb_mid": "i",
        "verb_tr": "ʾamina",
        "fem_tr": "ʾamīnah",
        "masc_tr": "ʾamīn",
        "masc_gloss": "'trustworthy, faithful'",
        "variant": None,
        "usage": "The plural is used as a given name in some South Asian communities.",
        "fa_from": "urdu",
        "fa_meaning": "امین، قابل اعتماد، وفادار",
        "surgeries": [
            ("suf", "arabic", "أمين", "ات"),
            ("suf", "arabic", "موثوق", "ات"),
            ("suf", "arabic", "مخلص", "ات"),
        ],
    },
    "aamirat": {
        "kind": "fem_plural",
        "gloss": "Inhabited, flourishing, prosperous",
        "root": "ع م ر",
        "root_tr": "ʿ-m-r",
        "vow": ["F", None, "K", "F", None, None],
        "voc_tr": "ʿāmirāt",
        "verb_mid": "a",
        "verb_tr": "ʿamara",
        "fem_tr": "ʿāmirah",
        "masc_tr": "ʿāmir",
        "masc_gloss": "'flourishing, inhabited'",
        "variant": None,
        "usage": None,
        "fa_from": "urdu",
        "fa_meaning": "آباد، شکوفا، پررونق",
        "surgeries": [
            ("suf", "arabic", "عامر", "ات"),
            ("suf", "arabic", "مأهول", "ات"),
            ("suf", "arabic", "مزدهر", "ات"),
            ("ur_ta_fem", "urdu", "پھلتا پھولتا"),
            ("set", "hindi", "फलता-फूलता", "फलती-फूलती"),
            ("ps_yeh_fem", "pashto", "پرمختللی"),
        ],
    },
    "aamrah": {
        "kind": "fem_participle",
        "gloss": "Inhabited, flourishing, prosperous",
        "root": "ع م ر",
        "root_tr": "ʿ-m-r",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāmirah",
        "verb_mid": "a",
        "verb_tr": "ʿamara",
        "verb_gloss_short": "'to inhabit, to build'",
        "masc_tr": "ʿāmir",
        "variant": "Aamrah is a variant romanization of Aamira/Aamirah.",
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "آباد، شکوفا، پررونق",
        "surgeries": [
            ("suf", "arabic", "عامر", "ة"),
            ("suf", "arabic", "مأهول", "ة"),
            ("suf", "arabic", "مزدهر", "ة"),
            ("ur_ta_fem", "urdu", "پھلتا پھولتا"),
            ("set", "hindi", "फलता-फूलता", "फलती-फूलती"),
            ("ps_yeh_fem", "pashto", "پرمختللی"),
        ],
    },
    "aanisa": {
        "kind": "fem_adj",
        "gloss": "Friendly, sociable, companionable",
        "root": "أ ن س",
        "root_tr": "ʾ-n-s",
        "vow": ["F", "K", None, "F", None],
        "voc_tr": "ʾanīsah",
        "verb_mid": "i",
        "verb_tr": "ʾanisa",
        "masc_tr": "ʾanīs",
        "masc_gloss": "'friendly, sociable'",
        "variant": None,
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "مهربان، اجتماعی، مونس",
        "surgeries": [
            ("suf", "arabic", "أنيس", "ة"),
            ("suf", "arabic", "ودود", "ة"),
            ("suf", "arabic", "مؤنس", "ة"),
            ("ps_yeh_fem", "pashto", "ملګری"),
        ],
    },
    "aanisah": {
        "kind": "fem_adj",
        "gloss": "Friendly, sociable, companionable",
        "root": "أ ن س",
        "root_tr": "ʾ-n-s",
        "vow": ["F", "K", None, "F", None],
        "voc_tr": "ʾanīsah",
        "verb_mid": "i",
        "verb_tr": "ʾanisa",
        "masc_tr": "ʾanīs",
        "masc_gloss": "'friendly, sociable'",
        "variant": "Aanisah is a variant romanization of Aanisa.",
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "مهربان، اجتماعی، مونس",
        "surgeries": [
            ("suf", "arabic", "أنيس", "ة"),
            ("suf", "arabic", "ودود", "ة"),
            ("suf", "arabic", "مؤنس", "ة"),
            ("ps_yeh_fem", "pashto", "ملګری"),
        ],
    },
    "aaqib": {
        "kind": "masc_participle",
        "gloss": "Successor, follower, one who comes after",
        "root": "ع ق ب",
        "root_tr": "ʿ-q-b",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāqib",
        "verb_mid": "a",
        "verb_tr": "ʿaqaba",
        "verb_gloss_short": "'to follow, to succeed'",
        "variant": None,
        "usage": None,
        "fa_from": "urdu",
        "fa_meaning": "جانشین، پیرو، تالی",
        "surgeries": [],
    },
    "aaqiba": {
        "kind": "noun",
        "gloss": "Consequence, outcome, end result",
        "root": "ع ق ب",
        "root_tr": "ʿ-q-b",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāqibah",
        "verb_mid": None,
        "verb_tr": None,
        "variant": None,
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "پیامد، نتیجه، فرجام",
        "surgeries": [],
    },
    "aaqibah": {
        "kind": "noun",
        "gloss": "Consequence, outcome, result",
        "root": "ع ق ب",
        "root_tr": "ʿ-q-b",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāqibah",
        "verb_mid": None,
        "verb_tr": None,
        "variant": "Aaqibah is a variant romanization of Aaqiba.",
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "پیامد، نتیجه، فرجام",
        "surgeries": [],
    },
    "aaqif": {
        "kind": "masc_participle",
        "gloss": "Devoted, steadfast, staying",
        "root": "ع ك ف",
        "root_tr": "ʿ-k-f",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿākif",
        "verb_mid": "a",
        "verb_tr": "ʿakafa",
        "verb_gloss_short": "'to stay, to devote oneself'",
        "variant": None,
        "usage": None,
        "fa_from": "urdu",
        "fa_meaning": "پایبند، ثابت‌قدم، مقیم",
        "surgeries": [],
    },
    # ---------------- batch 2 (#11-#20) ----------------
    "aaraf": {
        "kind": "noun",
        "gloss": "Elevated place, crest",
        "root": "ع ر ف",
        "root_tr": "ʿ-r-f",
        "vow": ["F", "S", "F", None, None],
        "voc_tr": "ʾaʿrāf",
        "verb_mid": None,
        "verb_tr": None,
        "variant": None,
        "usage": "Its use as a personal name is reported but not verified.",
        "morph_t": "Broken plural (afʿāl pattern) of عُرْف ('crest, elevated place'), from the root {root}.",
        "body_t": "{name} is Arabic {voc} ({voc_tr}) '{short}', the broken plural of عُرْف (ʿurf, 'crest, ridge, elevated place') from the root {root} ({root_tr}); {lex} is also the title of sūra 7 (al-Aʿrāf).{tail}",
        "etym_t": "The form {lex} is an established Arabic lexical item — the broken plural of عرف — and {name} is the word itself used as a personal name rather than a derived or diminutive form.",
        "apposition": "broken plural of عرف",
        "fa_from": "urdu",
        "fa_meaning": "بلندی، تیغ، قله",
        "surgeries": [],
    },
    "aarefa": {
        "kind": "fem_participle",
        "gloss": "Knowing, aware, learned",
        "root": "ع ر ف",
        "root_tr": "ʿ-r-f",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿārifah",
        "verb_mid": "a",
        "verb_tr": "ʿarafa",
        "verb_gloss_short": "'to know, to recognize'",
        "masc_tr": "ʿārif",
        "variant": None,
        "usage": None,
        "fa_from": "pashto",
        "fa_meaning": "دانا، آگاه، دانشمند",
        "surgeries": [
            ("set", "urdu", "جاننے والا", "جاننے والی"),
            ("set", "hindi", "विद्वान", "विदुषी"),
            ("suf", "pashto", "عالم", "ه"),
            ("suf", "arabic", "عارف", "ة"),
            ("suf", "arabic", "عليم", "ة"),
            ("suf", "arabic", "خبير", "ة"),
        ],
    },
    "aarifin": {
        "kind": "noun",
        "gloss": "Knowing, aware, learned",
        "root": "ع ر ف",
        "root_tr": "ʿ-r-f",
        "vow": ["F", None, "K", "K", None, None],
        "voc_tr": "ʿārifīn",
        "verb_mid": None,
        "verb_tr": None,
        "variant": None,
        "usage": "The plural is used as a given name in some South Asian communities.",
        "morph_t": "Sound masculine plural (oblique -īn ending, nominative -ūn) of عارف, built on the root {root}.",
        "body_t": "{name} is Arabic {voc} ({voc_tr}) '{short}', the sound masculine plural of عَارِف (ʿārif, 'knowing, learned') from the root {root} ({root_tr}).{tail}",
        "etym_t": "The form {lex} is an established Arabic lexical item — the sound masculine plural of عارف — and {name} is the word itself used as a personal name rather than a derived or diminutive form.",
        "apposition": "sound masculine plural of عارف",
        "fa_from": "urdu",
        "fa_meaning": "دانا، آگاه، دانشمند",
        "surgeries": [
            ("suf", "arabic", "عارف", "ون"),
            ("suf", "arabic", "عليم", "ون"),
            ("suf", "arabic", "خبير", "ون"),
        ],
    },
    "aasal": {
        "kind": "noun",
        "gloss": "Honey",
        "root": "ع س ل",
        "root_tr": "ʿ-s-l",
        "vow": ["F", "F", None],
        "voc_tr": "ʿasal",
        "verb_mid": None,
        "verb_tr": None,
        "variant": None,
        "usage": "Its use as a personal name is reported but requires separate frequency evidence.",
        "morph_t": "Simple lexical noun from the root {root}.",
        "body_t": "{name} is Arabic {voc} ({voc_tr}) '{short}', the established word for honey, from the root {root} ({root_tr}).{tail}",
        "etym_t": "The form {lex} is an established Arabic lexical item — the word for 'honey' — and {name} is the word itself used as a personal name rather than a derived form.",
        "apposition": "established word for 'honey'",
        "fa_from": "urdu",
        "fa_meaning": "عسل، انگبین",
        "surgeries": [],
    },
    "aasfa": {
        "kind": "noun",
        "gloss": "Storm, tempest",
        "root": "ع ص ف",
        "root_tr": "ʿ-ṣ-f",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāṣifah",
        "verb_mid": "a",
        "verb_tr": "ʿaṣafa",
        "variant": None,
        "usage": None,
        "morph_t": "Established noun (also the feminine of the active participle {base}) from the root {root}.",
        "body_t": "{name} is Arabic {voc} ({voc_tr}) '{short}', the established word for a storm, from the root {root} ({root_tr}); it is also the feminine of the active participle عَاصِف (ʿāṣif, 'stormy') of {verb} ({verb_tr}, 'to storm, to rage').{tail}",
        "etym_t": "The form {lex} is an established Arabic lexical item — the storm-word of the root {root} — and {name} is the word itself used as a personal name rather than a derived or diminutive form.",
        "apposition": "established storm-word",
        "fa_from": "pashto",
        "fa_meaning": "توفان، تندباد",
        "surgeries": [],
    },
    "aashik": {
        "kind": "masc_participle",
        "gloss": "Lover, one passionately devoted",
        "root": "ع ش ق",
        "root_tr": "ʿ-sh-q",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāshiq",
        "verb_mid": "i",
        "verb_tr": "ʿashiqa",
        "verb_gloss_short": "'to love passionately'",
        "variant": None,
        "usage": "Widely used in Urdu and Persian literary culture.",
        "fa_from": "urdu",
        "fa_meaning": "عاشق، شیفته، دلداده",
        "surgeries": [],
    },
    "aashiq": {
        "kind": "masc_participle",
        "gloss": "Lover, devoted admirer, passionate one",
        "root": "ع ش ق",
        "root_tr": "ʿ-sh-q",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāshiq",
        "verb_mid": "i",
        "verb_tr": "ʿashiqa",
        "verb_gloss_short": "'to love passionately'",
        "variant": "Aashiq is a variant romanization of Aashik.",
        "usage": None,
        "fa_from": "urdu",
        "fa_meaning": "عاشق، شیفته، دلداده",
        "surgeries": [],
    },
    "aashir": {
        "kind": "noun",
        "gloss": "One who associates with",
        "root": "ع ش ر",
        "root_tr": "ʿ-sh-r",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāshir",
        "verb_mid": "a",
        "verb_tr": "ʿashara",
        "variant": None,
        "usage": None,
        "morph_t": "Active participle (fāʿil pattern) of {verb}, built on the root {root}; also the ordinal 'tenth'.",
        "body_t": "{name} is Arabic {voc} ({voc_tr}) '{short}', the active participle of {verb} ({verb_tr}, 'to take a tenth') from the root {root} ({root_tr}); {lex} doubles as the ordinal 'tenth', and the naming gloss 'one who associates with' reflects the root's companionship cluster.{tail}",
        "etym_t": "The form {lex} is an established Arabic lexical item — the active participle of {root_compact} — and {name} is the word itself used as a personal name rather than a derived or diminutive form.",
        "apposition": "active participle of {verb}",
        "fa_from": "urdu",
        "fa_meaning": "همراه، همنشین، مصاحب",
        "surgeries": [],
    },
    "aasif": {
        "kind": "masc_participle",
        "gloss": "Stormy, tempestuous",
        "root": "ع ص ف",
        "root_tr": "ʿ-ṣ-f",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāṣif",
        "verb_mid": "a",
        "verb_tr": "ʿaṣafa",
        "verb_gloss_short": "'to storm, to rage'",
        "variant": None,
        "usage": None,
        "fa_from": "urdu",
        "fa_meaning": "توفانی، توفنده",
        "surgeries": [],
    },
    "aasifah": {
        "kind": "noun",
        "gloss": "Storm, tempest, strong wind",
        "root": "ع ص ف",
        "root_tr": "ʿ-ṣ-f",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāṣifah",
        "verb_mid": "a",
        "verb_tr": "ʿaṣafa",
        "variant": "Aasifah is a variant romanization of Aasfa.",
        "usage": None,
        "morph_t": "Established noun (also the feminine of the active participle {base}) from the root {root}.",
        "body_t": "{name} is Arabic {voc} ({voc_tr}) '{short}', the established word for a storm, from the root {root} ({root_tr}); it is also the feminine of the active participle عَاصِف (ʿāṣif, 'stormy') of {verb} ({verb_tr}, 'to storm, to rage').{tail}",
        "etym_t": "The form {lex} is an established Arabic lexical item — the storm-word of the root {root} — and {name} is the word itself used as a personal name rather than a derived or diminutive form.",
        "apposition": "established storm-word",
        "fa_from": "pashto",
        "fa_meaning": "توفان، تندباد",
        "surgeries": [],
    },

    # ------------------------------------------------------------------
    # Batch #3 (tracker rows #21-#30) - content_revision v8.2
    # ------------------------------------------------------------------
    "aasim": {
        "kind": "masc_participle",
        "gloss": "Protector, guardian, keeper",
        "root": "ع ص م",
        "root_tr": "ʿ-ṣ-m",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāṣim",
        "verb_mid": "a",
        "verb_tr": "ʿaṣama",
        "verb_gloss_short": "'to protect, to preserve'",
        "variant": None,
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "محافظ، نگهبان، حامی",
        "surgeries": [],
    },
    "aasimah": {
        "kind": "fem_participle",
        "gloss": "Protector, guardian, keeper",
        "root": "ع ص م",
        "root_tr": "ʿ-ṣ-m",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāṣimah",
        "verb_mid": "a",
        "verb_tr": "ʿaṣama",
        "verb_gloss_short": "'to protect, to preserve'",
        "masc_tr": "ʿāṣim",
        "variant": "Aasimah is a variant romanization of Aasima.",
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "محافظ، نگهبان، حامی",
        "surgeries": [
            ("suf", "arabic", "حافظ", "ة"),
            ("suf", "arabic", "حامي", "ة"),
            ("set", "hindi", "हिफ़ाज़त करने वाला", "हिफ़ाज़त करने वाली"),
            ("ps_yeh_fem", "pashto", "ساتونکی"),
            ("ps_yeh_fem", "pashto", "ملاتړی"),
        ],
    },
    "aasimat": {
        "kind": "fem_plural",
        "gloss": "Protector, guardian, keeper",
        "root": "ع ص م",
        "root_tr": "ʿ-ṣ-m",
        "vow": ["F", None, "K", "F", None, None],
        "voc_tr": "ʿāṣimāt",
        "verb_mid": None,
        "verb_tr": None,
        "fem_tr": "ʿāṣimah",
        "masc_tr": "ʿāṣim",
        "masc_gloss": "'protector, guardian'",
        "variant": None,
        "usage": "The plural form is used as a given name in some South Asian communities.",
        "fa_from": "arabic",
        "fa_meaning": "محافظان، نگهبانان، حامیان",
        "surgeries": [
            ("suf", "arabic", "حافظ", "ات"),
            ("suf", "arabic", "حامي", "ات"),
            ("set", "hindi", "हिफ़ाज़त करने वाला", "हिफ़ाज़त करने वाली"),
            ("ps_yeh_fem", "pashto", "ساتونکی"),
            ("ps_yeh_fem", "pashto", "ملاتړی"),
        ],
    },
    "aateqa": {
        "kind": "fem_participle",
        "gloss": "Free, liberated",
        "root": "ع ت ق",
        "root_tr": "ʿ-t-q",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿātiqah",
        "verb_mid": "a",
        "verb_tr": "ʿataqa",
        "verb_gloss_short": "'to be free, to be freed'",
        "masc_tr": "ʿātiq",
        "variant": "Aateqa is a variant romanization of Atika.",
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "آزاد، رها، مستقل",
        "surgeries": [
            ("suf", "arabic", "حر", "ة"),
            ("suf", "arabic", "طليق", "ة"),
            ("suf", "arabic", "مستقل", "ة"),
        ],
    },
    "aatir": {
        "kind": "masc_participle",
        "gloss": "Fragrant, perfumed",
        "root": "ع ط ر",
        "root_tr": "ʿ-ṭ-r",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿāṭir",
        "verb_mid": "i",
        "verb_tr": "ʿaṭira",
        "verb_gloss_short": "'to be fragrant, to be perfumed'",
        "variant": None,
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "خوشبودار، معطر، عطرآگین",
        "surgeries": [],
    },
    "aatira": {
        "kind": "fem_participle",
        "gloss": "Fragrant, perfumed, scented",
        "root": "ع ط ر",
        "root_tr": "ʿ-ṭ-r",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāṭirah",
        "verb_mid": "i",
        "verb_tr": "ʿaṭira",
        "verb_gloss_short": "'to be fragrant, to be perfumed'",
        "masc_tr": "ʿāṭir",
        "variant": "Aatira is a variant romanization of Aatirah.",
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "خوشبودار، معطر، عطرآگین",
        "surgeries": [
            ("suf", "arabic", "عاطر", "ة"),
        ],
    },
    "aatirah": {
        "kind": "fem_participle",
        "gloss": "Fragrant, perfumed, scented",
        "root": "ع ط ر",
        "root_tr": "ʿ-ṭ-r",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿāṭirah",
        "verb_mid": "i",
        "verb_tr": "ʿaṭira",
        "verb_gloss_short": "'to be fragrant, to be perfumed'",
        "masc_tr": "ʿāṭir",
        "variant": None,
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "خوشبودار، معطر، عطرآگین",
        "surgeries": [
            ("suf", "arabic", "عاطر", "ة"),
        ],
    },
    "abid": {
        "kind": "masc_participle",
        "gloss": "Worshipper, devout servant",
        "root": "ع ب د",
        "root_tr": "ʿ-b-d",
        "vow": ["F", None, "K", None],
        "voc_tr": "ʿābid",
        "verb_mid": "a",
        "verb_tr": "ʿabada",
        "verb_gloss_short": "'to worship, to serve'",
        "variant": None,
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "عبادت کننده، پرستنده، بنده",
        "surgeries": [],
    },
    "abidah": {
        "kind": "fem_participle",
        "gloss": "Worshipper of God",
        "root": "ع ب د",
        "root_tr": "ʿ-b-d",
        "vow": ["F", None, "K", "F", None],
        "voc_tr": "ʿābidah",
        "verb_mid": "a",
        "verb_tr": "ʿabada",
        "verb_gloss_short": "'to worship, to serve'",
        "masc_tr": "ʿābid",
        "variant": None,
        "usage": None,
        "fa_from": "arabic",
        "fa_meaning": "عبادت کننده، بنده، پرستنده",
        "surgeries": [
            ("set", "urdu", "خدا کا عابد", "خدا کی عابدہ"),
            ("set", "hindi", "ईश्वर का उपासक", "ईश्वर की उपासिका"),
            ("ps_yeh_fem", "pashto", "د خدای عبادت کوونکی"),
        ],
    },
    "abidat": {
        "kind": "fem_plural",
        "gloss": "Servants, worshippers (of God)",
        "root": "ع ب د",
        "root_tr": "ʿ-b-d",
        "vow": ["F", None, "K", "F", None, None],
        "voc_tr": "ʿābidāt",
        "verb_mid": None,
        "verb_tr": None,
        "fem_tr": "ʿābidah",
        "masc_tr": "ʿābid",
        "masc_gloss": "'worshipper, devout servant'",
        "variant": None,
        "usage": "The plural form is used as a given name in some South Asian communities.",
        "fa_from": "arabic",
        "fa_meaning": "بندگان، عبادت کنندگان، پرستندگان",
        "surgeries": [
            ("set", "urdu", "عبادت کرنے والے", "عبادت کرنے والیاں"),
            ("set", "hindi", "दास", "दासियाँ"),
            ("set", "pashto", "عبادت کوونکي", "عبادت کوونکې"),
        ],
    },

    # ------------------------------------------------------------------
    # Batch #4 (tracker rows #31-#40) - content_revision v8.2
    # ------------------------------------------------------------------
    'abir': {'kind': 'noun',
             'gloss': 'Fragrance',
             'root': 'ع ب ر',
             'root_tr': 'ʿ-b-r',
             'vow': ['F', 'K', None, None],
             'voc_tr': 'ʿabīr',
             'verb_mid': None,
             'verb_tr': None,
             'variant': None,
             'usage': None,
             'morph_t': 'Verbal-noun pattern (faʿīl) from the root {root}.',
             'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the established word for "
                       'fragrance, from the root {root} ({root_tr}).{tail}',
             'etym_t': 'The form {lex} is an established Arabic lexical item — the word for '
                       "'fragrance' — and {name} is the word itself used as a personal name "
                       'rather than a derived or diminutive form.',
             'apposition': "established word for 'fragrance'",
             'fa_from': 'arabic',
             'fa_meaning': 'خوشبو، عطر، رایحه',
             'surgeries': []},
    'adal': {'kind': 'noun',
             'gloss': 'Justice, equity',
             'root': 'ع د ل',
             'root_tr': 'ʿ-d-l',
             'vow': ['F', 'S', None],
             'voc_tr': 'ʿadl',
             'verb_mid': None,
             'verb_tr': None,
             'variant': None,
             'usage': None,
             'morph_t': "Verbal noun (maṣdar) of عَدَلَ (ʿadala, 'to be just, to act justly'), "
                        'from the root {root}.',
             'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the verbal noun of عَدَلَ "
                       "(ʿadala, 'to be just, to act justly') from the root {root} "
                       '({root_tr}).{tail}',
             'etym_t': 'The form {lex} is an established Arabic lexical item — the verbal noun of '
                       'the root {root} — and {name} is the word itself used as a personal name '
                       'rather than a derived or diminutive form.',
             'apposition': 'verbal noun of عَدَلَ',
             'fa_from': 'arabic',
             'fa_meaning': 'عدل، انصاف، داد',
             'surgeries': []},
    'adala': {'kind': 'noun',
              'gloss': 'Justice, fairness',
              'root': 'ع د ل',
              'root_tr': 'ʿ-d-l',
              'vow': ['F', 'F', None, 'F', None],
              'voc_tr': 'ʿadālah',
              'verb_mid': None,
              'verb_tr': None,
              'variant': None,
              'usage': None,
              'morph_t': 'Feminine abstract noun (faʿālah pattern) built on عَدْل (ʿadl, '
                         "'justice') and the root {root}.",
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the abstract noun of "
                        'justice built from عَدْل (ʿadl) on the root {root} ({root_tr}).{tail}',
              'etym_t': 'The form {lex} is an established Arabic lexical item — the abstract noun '
                        'of the root {root} — and {name} is the word itself used as a personal '
                        'name rather than a derived or diminutive form.',
              'apposition': 'abstract noun of عَدْل',
              'fa_from': 'arabic',
              'fa_meaning': 'عدالت، انصاف',
              'surgeries': []},
    'adalat': {'kind': 'noun',
               'gloss': 'Justice',
               'root': 'ع د ل',
               'root_tr': 'ʿ-d-l',
               'vow': ['F', 'F', None, 'F', None],
               'voc_tr': 'ʿadālah',
               'verb_mid': None,
               'verb_tr': None,
               'variant': 'Adalat is a variant romanization of Adala.',
               'usage': None,
               'morph_t': 'Feminine abstract noun (faʿālah pattern) built on عَدْل (ʿadl, '
                          "'justice') and the root {root}.",
               'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the abstract noun of "
                         'justice built from عَدْل (ʿadl) on the root {root} ({root_tr}).{tail}',
               'etym_t': 'The form {lex} is an established Arabic lexical item — the abstract '
                         'noun of the root {root} — and {name} is the word itself used as a '
                         'personal name rather than a derived or diminutive form.',
               'apposition': 'abstract noun of عَدْل',
               'fa_from': 'arabic',
               'fa_meaning': 'عدالت، انصاف',
               'surgeries': []},
    'adil': {'kind': 'masc_participle',
             'gloss': 'Just, fair, honest',
             'root': 'ع د ل',
             'root_tr': 'ʿ-d-l',
             'vow': ['F', None, 'K', None],
             'voc_tr': 'ʿādil',
             'verb_mid': 'a',
             'verb_tr': 'ʿadala',
             'verb_gloss_short': "'to be just, to act justly'",
             'variant': None,
             'usage': None,
             'fa_from': 'arabic',
             'fa_meaning': 'عادل، منصف، درستکار',
             'surgeries': []},
    'adl': {'kind': 'noun',
            'gloss': 'Justice, fairness',
            'root': 'ع د ل',
            'root_tr': 'ʿ-d-l',
            'vow': ['F', 'S', None],
            'voc_tr': 'ʿadl',
            'verb_mid': None,
            'verb_tr': None,
            'variant': 'Adl is a variant romanization of Adal.',
            'usage': None,
            'morph_t': "Verbal noun (maṣdar) of عَدَلَ (ʿadala, 'to be just, to act justly'), "
                       'from the root {root}.',
            'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the verbal noun of عَدَلَ "
                      "(ʿadala, 'to be just, to act justly') from the root {root} "
                      '({root_tr}).{tail}',
            'etym_t': 'The form {lex} is an established Arabic lexical item — the verbal noun of '
                      'the root {root} — and {name} is the word itself used as a personal name '
                      'rather than a derived or diminutive form.',
            'apposition': 'verbal noun of عَدَلَ',
            'fa_from': 'arabic',
            'fa_meaning': 'عدل، انصاف، داد',
            'surgeries': []},
    'adla': {'kind': 'noun',
             'gloss': 'Justice, fairness',
             'root': 'ع د ل',
             'root_tr': 'ʿ-d-l',
             'vow': ['F', 'S', 'F', None],
             'voc_tr': 'ʿadlah',
             'verb_mid': None,
             'verb_tr': None,
             'variant': None,
             'usage': None,
             'morph_t': "Feminine noun (faʿlah pattern) built on عَدْل (ʿadl, 'justice') and the "
                        'root {root}.',
             'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', a feminine noun of justice "
                       'built from عَدْل (ʿadl) on the root {root} ({root_tr}).{tail}',
             'etym_t': 'The form {lex} is an established Arabic lexical item — a feminine noun of '
                       'the root {root} — and {name} is the word itself used as a personal name '
                       'rather than a derived or diminutive form.',
             'apposition': 'feminine noun of عَدْل',
             'fa_from': 'arabic',
             'fa_meaning': 'عدالت، انصاف',
             'surgeries': []},
    'adlah': {'kind': 'noun',
              'gloss': 'Justice, fairness',
              'root': 'ع د ل',
              'root_tr': 'ʿ-d-l',
              'vow': ['F', 'S', 'F', None],
              'voc_tr': 'ʿadlah',
              'verb_mid': None,
              'verb_tr': None,
              'variant': 'Adlah is a variant romanization of Adla.',
              'usage': None,
              'morph_t': "Feminine noun (faʿlah pattern) built on عَدْل (ʿadl, 'justice') and the "
                         'root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', a feminine noun of justice "
                        'built from عَدْل (ʿadl) on the root {root} ({root_tr}).{tail}',
              'etym_t': 'The form {lex} is an established Arabic lexical item — a feminine noun '
                        'of the root {root} — and {name} is the word itself used as a personal '
                        'name rather than a derived or diminutive form.',
              'apposition': 'feminine noun of عَدْل',
              'fa_from': 'arabic',
              'fa_meaning': 'عدالت، انصاف',
              'surgeries': []},
    'adnan': {'kind': 'noun',
              'gloss': 'Settler, one who dwells',
              'root': 'ع د ن',
              'root_tr': 'ʿ-d-n',
              'vow': ['F', 'S', 'F', None, None],
              'voc_tr': 'ʿadnān',
              'verb_mid': None,
              'verb_tr': None,
              'variant': None,
              'usage': None,
              'morph_t': "Extended adjective (faʿlān pattern) from عَدَنَ (ʿadana, 'to settle, to "
                         "dwell'), built on the root {root}.",
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the faʿlān-pattern "
                        "adjective from عَدَنَ (ʿadana, 'to settle, to dwell') on the root {root} "
                        '({root_tr}).{tail}',
              'etym_t': 'The form {lex} is an established Arabic lexical item — the '
                        'faʿlān-pattern adjective of the root {root} — and {name} is the word '
                        'itself used as a personal name rather than a derived or diminutive form.',
              'apposition': 'faʿlān-pattern adjective of عَدَنَ',
              'fa_from': 'arabic',
              'fa_meaning': 'ساکن، مقیم، مستوطن',
              'surgeries': []},
    'afaaf': {'kind': 'noun',
              'gloss': 'Chastity, modesty, virtue',
              'root': 'ع ف ف',
              'root_tr': 'ʿ-f-f',
              'vow': ['K', 'F', None, None],
              'voc_tr': 'ʿifāf',
              'verb_mid': None,
              'verb_tr': None,
              'variant': None,
              'usage': None,
              'morph_t': "Verbal noun (maṣdar) of عَفّ (ʿaffa, 'to abstain, to be chaste'), from "
                         'the geminate root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the verbal noun of عَفّ "
                        "(ʿaffa, 'to abstain, to be chaste') from the geminate root {root} "
                        '({root_tr}).{tail}',
              'etym_t': 'The form {lex} is an established Arabic lexical item — the verbal noun '
                        'of the root {root} — and {name} is the word itself used as a personal '
                        'name rather than a derived or diminutive form.',
              'apposition': 'verbal noun of عَفّ',
              'fa_from': 'arabic',
              'fa_meaning': 'عفت، پاکدامنی، پرهیزگاری',
              'surgeries': []},

    # ------------------------------------------------------------------
    # Batch #5 (tracker rows #41-#50) - content_revision v8.2
    # ------------------------------------------------------------------
    'afdal': {'kind': 'noun',
              'gloss': 'Better, best',
              'root': 'ف ض ل',
              'root_tr': 'f-ḍ-l',
              'vow': ['F', 'S', 'F', None],
              'voc_tr': 'afḍal',
              'verb_mid': None,
              'verb_tr': None,
              'variant': 'Afdal is a variant romanization of Afzal.',
              'usage': None,
              'morph_t': 'Elative adjective (afʿal pattern) built on the root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the elative ('better, "
                        "best') form built on the root {root} ({root_tr}).{tail}",
              'etym_t': 'The form {lex} is an established Arabic lexical item — the elative of '
                        'the root {root} — and {name} is the word itself used as a personal name '
                        'rather than a derived or diminutive form.',
              'apposition': 'elative form',
              'fa_from': 'arabic',
              'fa_meaning': 'برتری، فضیلت، کمال',
              'surgeries': []},
    'afzal': {'kind': 'noun',
              'gloss': 'Better, best, superior',
              'root': 'ف ض ل',
              'root_tr': 'f-ḍ-l',
              'vow': ['F', 'S', 'F', None],
              'voc_tr': 'afḍal',
              'verb_mid': None,
              'verb_tr': None,
              'variant': None,
              'usage': None,
              'morph_t': 'Elative adjective (afʿal pattern) built on the root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the elative ('better, "
                        "best') form built on the root {root} ({root_tr}).{tail}",
              'etym_t': 'The form {lex} is an established Arabic lexical item — the elative of '
                        'the root {root} — and {name} is the word itself used as a personal name '
                        'rather than a derived or diminutive form.',
              'apposition': 'elative form',
              'fa_from': 'arabic',
              'fa_meaning': 'برتر، فاضل، برگزیده',
              'surgeries': []},
    'afeef': {'kind': 'noun',
              'gloss': 'Chaste, virtuous, modest',
              'root': 'ع ف ف',
              'root_tr': 'ʿ-f-f',
              'vow': ['F', 'K', None, None],
              'voc_tr': 'ʿafīf',
              'verb_mid': None,
              'verb_tr': None,
              'variant': 'Afeef is a variant romanization of Afif.',
              'usage': None,
              'morph_t': 'Faʿīl-pattern stative adjective built on the root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the faʿīl-pattern adjective "
                        'of chastity built on the root {root} ({root_tr}).{tail}',
              'etym_t': 'The form {lex} is an established Arabic lexical item — the faʿīl-pattern '
                        'adjective of the root {root} — and {name} is the word itself used as a '
                        'personal name rather than a derived or diminutive form.',
              'apposition': 'faʿīl-pattern adjective',
              'fa_from': 'arabic',
              'fa_meaning': 'پاکدامن، عفیف، پارسا',
              'surgeries': []},
    'afif': {'kind': 'noun',
             'gloss': 'Chaste, virtuous',
             'root': 'ع ف ف',
             'root_tr': 'ʿ-f-f',
             'vow': ['F', 'K', None, None],
             'voc_tr': 'ʿafīf',
             'verb_mid': None,
             'verb_tr': None,
             'variant': None,
             'usage': None,
             'morph_t': 'Faʿīl-pattern stative adjective built on the root {root}.',
             'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the faʿīl-pattern adjective "
                       'of chastity built on the root {root} ({root_tr}).{tail}',
             'etym_t': 'The form {lex} is an established Arabic lexical item — the faʿīl-pattern '
                       'adjective of the root {root} — and {name} is the word itself used as a '
                       'personal name rather than a derived or diminutive form.',
             'apposition': 'faʿīl-pattern adjective',
             'fa_from': 'arabic',
             'fa_meaning': 'پاکدامن، عفیف، پارسا',
             'surgeries': []},
    'afeefa': {'kind': 'noun',
               'gloss': 'Pure and chaste',
               'root': 'ع ف ف',
               'root_tr': 'ʿ-f-f',
               'vow': ['F', 'K', None, 'F', None],
               'voc_tr': 'ʿafīfah',
               'verb_mid': None,
               'verb_tr': None,
               'variant': 'Afeefa is a variant romanization of Afifa.',
               'usage': None,
               'morph_t': 'Feminine of the faʿīl-pattern adjective {base} (ʿafīf), built on the '
                          'root {root}.',
               'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the feminine of the "
                         'faʿīl-pattern adjective {base} (ʿafīf) built on the root {root} '
                         '({root_tr}).{tail}',
               'etym_t': 'The form {lex} is an established Arabic lexical item — the feminine of '
                         '{base} — and {name} is the word itself used as a personal name rather '
                         'than a derived or diminutive form.',
               'apposition': 'feminine of {base}',
               'fa_from': 'arabic',
               'fa_meaning': 'پاکدامن، پارسا، عفیف',
               'surgeries': []},
    'afifa': {'kind': 'noun',
              'gloss': 'Pure and chaste',
              'root': 'ع ف ف',
              'root_tr': 'ʿ-f-f',
              'vow': ['F', 'K', None, 'F', None],
              'voc_tr': 'ʿafīfah',
              'verb_mid': None,
              'verb_tr': None,
              'variant': None,
              'usage': None,
              'morph_t': 'Feminine of the faʿīl-pattern adjective {base} (ʿafīf), built on the '
                         'root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the feminine of the "
                        'faʿīl-pattern adjective {base} (ʿafīf) built on the root {root} '
                        '({root_tr}).{tail}',
              'etym_t': 'The form {lex} is an established Arabic lexical item — the feminine of '
                        '{base} — and {name} is the word itself used as a personal name rather '
                        'than a derived or diminutive form.',
              'apposition': 'feminine of {base}',
              'fa_from': 'arabic',
              'fa_meaning': 'پاکدامن، پارسا، عفیف',
              'surgeries': []},
    'afifah': {'kind': 'noun',
               'gloss': 'Pure and chaste',
               'root': 'ع ف ف',
               'root_tr': 'ʿ-f-f',
               'vow': ['F', 'K', None, 'F', None],
               'voc_tr': 'ʿafīfah',
               'verb_mid': None,
               'verb_tr': None,
               'variant': 'Afifah is a variant romanization of Afifa.',
               'usage': None,
               'morph_t': 'Feminine of the faʿīl-pattern adjective {base} (ʿafīf), built on the '
                          'root {root}.',
               'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the feminine of the "
                         'faʿīl-pattern adjective {base} (ʿafīf) built on the root {root} '
                         '({root_tr}).{tail}',
               'etym_t': 'The form {lex} is an established Arabic lexical item — the feminine of '
                         '{base} — and {name} is the word itself used as a personal name rather '
                         'than a derived or diminutive form.',
               'apposition': 'feminine of {base}',
               'fa_from': 'arabic',
               'fa_meaning': 'پاکدامن، پارسا، عفیف',
               'surgeries': []},
    'ahd': {'kind': 'noun',
            'gloss': 'Covenant, pledge',
            'root': 'ع ه د',
            'root_tr': 'ʿ-h-d',
            'vow': ['F', 'S', None],
            'voc_tr': 'ʿahd',
            'verb_mid': None,
            'verb_tr': None,
            'variant': None,
            'usage': None,
            'morph_t': "Established noun from عَهِدَ (ʿahida, 'to know, to entrust'), built on "
                       'the root {root}.',
            'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the established word for a "
                      'covenant, built on the root {root} ({root_tr}).{tail}',
            'etym_t': 'The form {lex} is an established Arabic lexical item — the word for '
                      "'covenant, pledge' — and {name} is the word itself used as a personal name "
                      'rather than a derived or diminutive form.',
            'apposition': "established word for 'covenant'",
            'fa_from': 'arabic',
            'fa_meaning': 'عهد، پیمان، میثاق',
            'surgeries': []},
    'ahmad': {'kind': 'noun',
              'gloss': 'Most praiseworthy',
              'root': 'ح م د',
              'root_tr': 'ḥ-m-d',
              'vow': ['F', 'S', 'F', None],
              'voc_tr': 'ʾaḥmad',
              'verb_mid': None,
              'verb_tr': None,
              'variant': None,
              'usage': None,
              'morph_t': "Elative adjective (afʿal pattern) of حَمِدَ (ḥamida, 'to praise'), "
                         'built on the root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the elative of praise built "
                        'on the root {root} ({root_tr}).{tail}',
              'etym_t': 'The form {lex} is an established Arabic lexical item — the elative of '
                        'the root {root} — and {name} is the word itself used as a personal name '
                        'rather than a derived or diminutive form.',
              'apposition': 'elative form',
              'fa_from': 'arabic',
              'fa_meaning': 'بسیار ستوده، احمد، محمود',
              'surgeries': []},
    'ahmar': {'kind': 'noun',
              'gloss': 'Red',
              'root': 'ح م ر',
              'root_tr': 'ḥ-m-r',
              'vow': ['F', 'S', 'F', None],
              'voc_tr': 'ʾaḥmar',
              'verb_mid': None,
              'verb_tr': None,
              'variant': None,
              'usage': 'The colour term is attested as an epithet and, less often, as a personal '
                       'name.',
              'morph_t': 'Colour adjective (afʿal pattern) built on the root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the afʿal-pattern colour "
                        'adjective for red, built on the root {root} ({root_tr}).{tail}',
              'etym_t': 'The form {lex} is an established Arabic lexical item — the colour '
                        'adjective of the root {root} — and {name} is the colour term used as a '
                        'personal name rather than a derived or diminutive form.',
              'apposition': 'colour adjective',
              'fa_from': 'arabic',
              'fa_meaning': 'سرخ، قرمز',
              'surgeries': []},

    # ------------------------------------------------------------------
    # Batch #6 (tracker rows #51-#60) - content_revision v8.2
    # ------------------------------------------------------------------
    'ahsan': {'kind': 'noun',
              'gloss': 'Best, most beautiful',
              'root': 'ح س ن',
              'root_tr': 'ḥ-s-n',
              'vow': ['F', 'S', 'F', None],
              'voc_tr': 'ʾaḥsan',
              'verb_mid': None,
              'verb_tr': None,
              'variant': None,
              'usage': None,
              'morph_t': 'Elative adjective (afʿal pattern) built on the root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the elative ('better, more "
                        "beautiful') form built on the root {root} ({root_tr}).{tail}",
              'etym_t': 'The form {lex} is an established Arabic lexical item — the elative of '
                        'the root {root} — and {name} is the word itself used as a personal name '
                        'rather than a derived or diminutive form.',
              'apposition': 'elative form',
              'fa_from': 'arabic',
              'fa_meaning': 'بهترین، نیکوترین، زیباترین',
              'surgeries': []},
    'akbar': {'kind': 'noun',
              'gloss': 'Greatest',
              'root': 'ك ب ر',
              'root_tr': 'k-b-r',
              'vow': ['F', 'S', 'F', None],
              'voc_tr': 'ʾakbar',
              'verb_mid': None,
              'verb_tr': None,
              'variant': None,
              'usage': None,
              'morph_t': 'Elative adjective (afʿal pattern) built on the root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the elative ('greater, "
                        "greatest') form built on the root {root} ({root_tr}).{tail}",
              'etym_t': 'The form {lex} is an established Arabic lexical item — the elative of '
                        'the root {root} — and {name} is the word itself used as a personal name '
                        'rather than a derived or diminutive form.',
              'apposition': 'elative form',
              'fa_from': 'arabic',
              'fa_meaning': 'بزرگترین، برترین',
              'surgeries': []},
    'akif': {'kind': 'masc_participle',
             'gloss': 'Devoted, one who secludes himself in worship',
             'root': 'ع ك ف',
             'root_tr': 'ʿ-k-f',
             'vow': ['F', None, 'K', None],
             'voc_tr': 'ʿākif',
             'verb_mid': 'a',
             'verb_tr': 'ʿakafa',
             'verb_gloss_short': "'to devote oneself, to remain in worship'",
             'variant': None,
             'usage': None,
             'fa_from': 'arabic',
             'fa_meaning': 'مخلص، مشغول به عبادت',
             'surgeries': []},
    'akmal': {'kind': 'noun',
              'gloss': 'Most perfect, most complete',
              'root': 'ك م ل',
              'root_tr': 'k-m-l',
              'vow': ['F', 'S', 'F', None],
              'voc_tr': 'ʾakmal',
              'verb_mid': None,
              'verb_tr': None,
              'variant': None,
              'usage': None,
              'morph_t': 'Elative adjective (afʿal pattern) built on the root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the elative ('more "
                        "complete, most perfect') form built on the root {root} "
                        '({root_tr}).{tail}',
              'etym_t': 'The form {lex} is an established Arabic lexical item — the elative of '
                        'the root {root} — and {name} is the word itself used as a personal name '
                        'rather than a derived or diminutive form.',
              'apposition': 'elative form',
              'fa_from': 'arabic',
              'fa_meaning': 'کامل، تمامتر، بی عیب',
              'surgeries': []},
    'aleem': {'kind': 'noun',
              'gloss': 'Knowledgeable, all-knowing',
              'root': 'ع ل م',
              'root_tr': 'ʿ-l-m',
              'vow': ['F', 'K', None, None],
              'voc_tr': 'ʿalīm',
              'verb_mid': None,
              'verb_tr': None,
              'variant': 'Aleem is a variant romanization of Alim.',
              'usage': None,
              'morph_t': 'Faʿīl-pattern intensive adjective built on the root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the faʿīl-pattern adjective "
                        'of knowledge built on the root {root} ({root_tr}).{tail}',
              'etym_t': 'The form {lex} is an established Arabic lexical item — the faʿīl-pattern '
                        'adjective of the root {root} — and {name} is the word itself used as a '
                        'personal name rather than a derived or diminutive form.',
              'apposition': 'faʿīl-pattern adjective',
              'fa_from': 'arabic',
              'fa_meaning': 'دانا، عالم، آگاه',
              'surgeries': []},
    'alim': {'kind': 'noun',
             'gloss': 'Learned, all-knowing',
             'root': 'ع ل م',
             'root_tr': 'ʿ-l-m',
             'vow': ['F', 'K', None, None],
             'voc_tr': 'ʿalīm',
             'verb_mid': None,
             'verb_tr': None,
             'variant': None,
             'usage': None,
             'morph_t': 'Faʿīl-pattern intensive adjective built on the root {root}.',
             'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the faʿīl-pattern adjective "
                       'of knowledge built on the root {root} ({root_tr}).{tail}',
             'etym_t': 'The form {lex} is an established Arabic lexical item — the faʿīl-pattern '
                       'adjective of the root {root} — and {name} is the word itself used as a '
                       'personal name rather than a derived or diminutive form.',
             'apposition': 'faʿīl-pattern adjective',
             'fa_from': 'arabic',
             'fa_meaning': 'دانا، عالم، آگاه',
             'surgeries': []},
    'aleema': {'kind': 'noun',
               'gloss': 'Learned, knowledgeable',
               'root': 'ع ل م',
               'root_tr': 'ʿ-l-m',
               'vow': ['F', 'K', None, 'F', None],
               'voc_tr': 'ʿalīmah',
               'verb_mid': None,
               'verb_tr': None,
               'variant': 'Aleema is a variant romanization of Alima.',
               'usage': None,
               'morph_t': 'Feminine of the faʿīl-pattern adjective {base} (ʿalīm), built on the '
                          'root {root}.',
               'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the feminine of the "
                         'faʿīl-pattern adjective {base} (ʿalīm) built on the root {root} '
                         '({root_tr}).{tail}',
               'etym_t': 'The form {lex} is an established Arabic lexical item — the feminine of '
                         '{base} — and {name} is the word itself used as a personal name rather '
                         'than a derived or diminutive form.',
               'apposition': 'feminine of {base}',
               'fa_from': 'arabic',
               'fa_meaning': 'دانا، عالمه، فاضله',
               'surgeries': []},
    'alima': {'kind': 'noun',
              'gloss': 'Learned woman, scholar',
              'root': 'ع ل م',
              'root_tr': 'ʿ-l-m',
              'vow': ['F', 'K', None, 'F', None],
              'voc_tr': 'ʿalīmah',
              'verb_mid': None,
              'verb_tr': None,
              'variant': None,
              'usage': None,
              'morph_t': 'Feminine of the faʿīl-pattern adjective {base} (ʿalīm), built on the '
                         'root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the feminine of the "
                        'faʿīl-pattern adjective {base} (ʿalīm) built on the root {root} '
                        '({root_tr}).{tail}',
              'etym_t': 'The form {lex} is an established Arabic lexical item — the feminine of '
                        '{base} — and {name} is the word itself used as a personal name rather '
                        'than a derived or diminutive form.',
              'apposition': 'feminine of {base}',
              'fa_from': 'arabic',
              'fa_meaning': 'دانا، عالمه، فاضله',
              'surgeries': []},
    'alimah': {'kind': 'noun',
               'gloss': 'Learned woman, scholar',
               'root': 'ع ل م',
               'root_tr': 'ʿ-l-m',
               'vow': ['F', 'K', None, 'F', None],
               'voc_tr': 'ʿalīmah',
               'verb_mid': None,
               'verb_tr': None,
               'variant': 'Alimah is a variant romanization of Alima.',
               'usage': None,
               'morph_t': 'Feminine of the faʿīl-pattern adjective {base} (ʿalīm), built on the '
                          'root {root}.',
               'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the feminine of the "
                         'faʿīl-pattern adjective {base} (ʿalīm) built on the root {root} '
                         '({root_tr}).{tail}',
               'etym_t': 'The form {lex} is an established Arabic lexical item — the feminine of '
                         '{base} — and {name} is the word itself used as a personal name rather '
                         'than a derived or diminutive form.',
               'apposition': 'feminine of {base}',
               'fa_from': 'arabic',
               'fa_meaning': 'دانا، عالمه، فاضله',
               'surgeries': []},
    'amal': {'kind': 'noun',
             'gloss': 'Hope',
             'root': 'أ م ل',
             'root_tr': 'ʾ-m-l',
             'vow': ['F', 'F', None],
             'voc_tr': 'ʾamal',
             'verb_mid': None,
             'verb_tr': None,
             'variant': None,
             'usage': None,
             'morph_t': "Established noun from أَمَلَ (ʾamala, 'to hope'), built on the root "
                        '{root}.',
             'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the established word for "
                       'hope, built on the root {root} ({root_tr}).{tail}',
             'etym_t': 'The form {lex} is an established Arabic lexical item — the word for '
                       "'hope' — and {name} is the word itself used as a personal name rather "
                       'than a derived or diminutive form.',
             'apposition': "established word for 'hope'",
             'fa_from': 'arabic',
             'fa_meaning': 'امید، آرزو',
             'surgeries': []},

    # ------------------------------------------------------------------
    # Batch #7 (tracker rows #61-#70) - content_revision v8.2
    # ------------------------------------------------------------------
    'aman': {'kind': 'noun',
             'gloss': 'Peace, safety, trust',
             'root': 'أ م ن',
             'root_tr': 'ʾ-m-n',
             'vow': ['F', 'F', None, None],
             'voc_tr': 'ʾamān',
             'verb_mid': None,
             'verb_tr': None,
             'variant': None,
             'usage': None,
             'morph_t': 'Verbal noun (maṣdar) of safety and trust built on the root {root}.',
             'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the verbal noun of safety "
                       'and trust built on the root {root} ({root_tr}).{tail}',
             'etym_t': 'The form {lex} is an established Arabic lexical item — the verbal noun of '
                       'the root {root} — and {name} is the word itself used as a personal name '
                       'rather than a derived or diminutive form.',
             'apposition': 'verbal noun of safety',
             'fa_from': 'arabic',
             'fa_meaning': 'امن، امان، اطمینان',
             'surgeries': []},
    'amana': {'kind': 'noun',
              'gloss': 'Trust, faithfulness',
              'root': 'أ م ن',
              'root_tr': 'ʾ-m-n',
              'vow': ['F', 'F', None, 'F', None],
              'voc_tr': 'ʾamānah',
              'verb_mid': None,
              'verb_tr': None,
              'variant': 'Amana is a variant romanization of Amanah.',
              'usage': None,
              'morph_t': 'Feminine verbal noun (maṣdar) of trust built on the root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the feminine verbal noun of "
                        'trust built on the root {root} ({root_tr}).{tail}',
              'etym_t': 'The form {lex} is an established Arabic lexical item — the verbal noun '
                        'of the root {root} — and {name} is the word itself used as a personal '
                        'name rather than a derived or diminutive form.',
              'apposition': 'verbal noun of trust',
              'fa_from': 'arabic',
              'fa_meaning': 'امانت، ایمان، اعتماد',
              'surgeries': []},
    'amanah': {'kind': 'noun',
               'gloss': 'Faith, trust',
               'root': 'أ م ن',
               'root_tr': 'ʾ-m-n',
               'vow': ['F', 'F', None, 'F', None],
               'voc_tr': 'ʾamānah',
               'verb_mid': None,
               'verb_tr': None,
               'variant': None,
               'usage': None,
               'morph_t': 'Feminine verbal noun (maṣdar) of trust built on the root {root}.',
               'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the feminine verbal noun "
                         'of trust built on the root {root} ({root_tr}).{tail}',
               'etym_t': 'The form {lex} is an established Arabic lexical item — the verbal noun '
                         'of the root {root} — and {name} is the word itself used as a personal '
                         'name rather than a derived or diminutive form.',
               'apposition': 'verbal noun of trust',
               'fa_from': 'arabic',
               'fa_meaning': 'امانت، ایمان، اعتماد',
               'surgeries': []},
    'ameer': {'kind': 'noun',
              'gloss': 'Prince, commander',
              'root': 'أ م ر',
              'root_tr': 'ʾ-m-r',
              'vow': ['F', 'K', None, None],
              'voc_tr': 'ʾamīr',
              'verb_mid': None,
              'verb_tr': None,
              'variant': None,
              'usage': None,
              'morph_t': "Faʿīl-pattern noun with active sense, from أَمَرَ (ʾamara, 'to "
                         "command'), built on the root {root}.",
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the faʿīl form with active "
                        "sense from أَمَرَ (ʾamara, 'to command') built on the root {root} "
                        '({root_tr}).{tail}',
              'etym_t': 'The form {lex} is an established Arabic lexical item — the faʿīl-pattern '
                        'adjective of the root {root} — and {name} is the word itself used as a '
                        'personal name rather than a derived or diminutive form.',
              'apposition': 'faʿīl form of command',
              'fa_from': 'arabic',
              'fa_meaning': 'امیر، فرمانده، سردار',
              'surgeries': []},
    'ameera': {'kind': 'noun',
               'gloss': 'Princess, ruler',
               'root': 'أ م ر',
               'root_tr': 'ʾ-m-r',
               'vow': ['F', 'K', None, 'F', None],
               'voc_tr': 'ʾamīrah',
               'verb_mid': None,
               'verb_tr': None,
               'variant': None,
               'usage': None,
               'morph_t': 'Feminine of {base} (ʾamīr), the faʿīl form with active sense, built on '
                          'the root {root}.',
               'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the feminine of {base} "
                         "(ʾamīr, 'prince, commander') built on the root {root} "
                         '({root_tr}).{tail}',
               'etym_t': 'The form {lex} is an established Arabic lexical item — the feminine of '
                         '{base} — and {name} is the word itself used as a personal name rather '
                         'than a derived or diminutive form.',
               'apposition': 'feminine of {base}',
               'fa_from': 'arabic',
               'fa_meaning': 'امیره، شاهدخت، فرمانده',
               'surgeries': []},
    'ameerah': {'kind': 'noun',
                'gloss': 'Princess, ruler',
                'root': 'أ م ر',
                'root_tr': 'ʾ-m-r',
                'vow': ['F', 'K', None, 'F', None],
                'voc_tr': 'ʾamīrah',
                'verb_mid': None,
                'verb_tr': None,
                'variant': 'Ameerah is a variant romanization of Ameera.',
                'usage': None,
                'morph_t': 'Feminine of {base} (ʾamīr), the faʿīl form with active sense, built '
                           'on the root {root}.',
                'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the feminine of {base} "
                          "(ʾamīr, 'prince, commander') built on the root {root} "
                          '({root_tr}).{tail}',
                'etym_t': 'The form {lex} is an established Arabic lexical item — the feminine of '
                          '{base} — and {name} is the word itself used as a personal name rather '
                          'than a derived or diminutive form.',
                'apposition': 'feminine of {base}',
                'fa_from': 'arabic',
                'fa_meaning': 'امیره، شاهدخت، فرمانده',
                'surgeries': []},
    'ameen': {'kind': 'noun',
              'gloss': 'Trustworthy, honest',
              'root': 'أ م ن',
              'root_tr': 'ʾ-m-n',
              'vow': ['F', 'K', None, None],
              'voc_tr': 'ʾamīn',
              'verb_mid': None,
              'verb_tr': None,
              'variant': None,
              'usage': None,
              'morph_t': 'Faʿīl-pattern adjective built on the root {root}.',
              'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the faʿīl-pattern adjective "
                        'of trustworthiness built on the root {root} ({root_tr}).{tail}',
              'etym_t': 'The form {lex} is an established Arabic lexical item — the faʿīl-pattern '
                        'adjective of the root {root} — and {name} is the word itself used as a '
                        'personal name rather than a derived or diminutive form.',
              'apposition': 'faʿīl-pattern adjective',
              'fa_from': 'arabic',
              'fa_meaning': 'امین، درستکار، مورد اعتماد',
              'surgeries': []},
    'amin': {'kind': 'noun',
             'gloss': 'Trustworthy, honest',
             'root': 'أ م ن',
             'root_tr': 'ʾ-m-n',
             'vow': ['F', 'K', None, None],
             'voc_tr': 'ʾamīn',
             'verb_mid': None,
             'verb_tr': None,
             'variant': 'Amin is a variant romanization of Ameen.',
             'usage': None,
             'morph_t': 'Faʿīl-pattern adjective built on the root {root}.',
             'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the faʿīl-pattern adjective "
                       'of trustworthiness built on the root {root} ({root_tr}).{tail}',
             'etym_t': 'The form {lex} is an established Arabic lexical item — the faʿīl-pattern '
                       'adjective of the root {root} — and {name} is the word itself used as a '
                       'personal name rather than a derived or diminutive form.',
             'apposition': 'faʿīl-pattern adjective',
             'fa_from': 'arabic',
             'fa_meaning': 'امین، درستکار، مورد اعتماد',
             'surgeries': []},
    'ameena': {'kind': 'noun',
               'gloss': 'Trustworthy, dependable (feminine)',
               'root': 'أ م ن',
               'root_tr': 'ʾ-m-n',
               'vow': ['F', 'K', None, 'F', None],
               'voc_tr': 'ʾamīnah',
               'verb_mid': None,
               'verb_tr': None,
               'variant': None,
               'usage': None,
               'morph_t': 'Feminine of the faʿīl-pattern adjective {base} (ʾamīn), built on the '
                          'root {root}.',
               'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the feminine of the "
                         'faʿīl-pattern adjective {base} (ʾamīn) built on the root {root} '
                         '({root_tr}).{tail}',
               'etym_t': 'The form {lex} is an established Arabic lexical item — the feminine of '
                         '{base} — and {name} is the word itself used as a personal name rather '
                         'than a derived or diminutive form.',
               'apposition': 'feminine of {base}',
               'fa_from': 'arabic',
               'fa_meaning': 'امین، درستکار، قابل اعتماد',
               'surgeries': []},
    'ameenah': {'kind': 'noun',
                'gloss': 'Trustworthy, dependable (feminine)',
                'root': 'أ م ن',
                'root_tr': 'ʾ-m-n',
                'vow': ['F', 'K', None, 'F', None],
                'voc_tr': 'ʾamīnah',
                'verb_mid': None,
                'verb_tr': None,
                'variant': 'Ameenah is a variant romanization of Ameena.',
                'usage': None,
                'morph_t': 'Feminine of the faʿīl-pattern adjective {base} (ʾamīn), built on the '
                           'root {root}.',
                'body_t': "{name} is Arabic {voc} ({voc_tr}) '{short}', the feminine of the "
                          'faʿīl-pattern adjective {base} (ʾamīn) built on the root {root} '
                          '({root_tr}).{tail}',
                'etym_t': 'The form {lex} is an established Arabic lexical item — the feminine of '
                          '{base} — and {name} is the word itself used as a personal name rather '
                          'than a derived or diminutive form.',
                'apposition': 'feminine of {base}',
                'fa_from': 'arabic',
                'fa_meaning': 'امین، درستکار، قابل اعتماد',
                'surgeries': []}
}
